// Code generated by curve_generator. DO NOT EDIT.

package oscaa

import (
	"crypto/elliptic"
	"sync"

	. "github.com/RyuaNerin/elliptic2/internal"
	. "github.com/RyuaNerin/elliptic2/internal/curve"
	wp "github.com/RyuaNerin/elliptic2/internal/curve/weierstrassprime"
	. "github.com/RyuaNerin/elliptic2/internal/field"
)

var (
	sM2Once sync.Once

	sM2Curve elliptic.Curve
)

// https://neuromancer.sk/std/oscaa/SM2
func initSM2() {
	sM2Curve = NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `SM2`,
			BitSize: 256,
			P:       NewGFpModulusFromHex(`fffffffeffffffffffffffffffffffffffffffff00000000ffffffffffffffff`),
			A:       ParseGFpHex(`fffffffeffffffffffffffffffffffffffffffff00000000fffffffffffffffc`),
			B:       ParseGFpHex(`28e9fa9e9d9f5e344d5a9e4bcf6509a7f39789f515ab8f92ddbcbd414d940e93`),
			N:       ParseGFpHex(`fffffffeffffffffffffffffffffffff7203df6b21c6052b53bbf40939d54123`),
			Gx:      HI(`32c4ae2c1f1981195f9904466a39c9948fe30bbff2660be1715a4589334c74c7`),
			Gy:      HI(`bc3736a2f4f6779c59bdcee36b692153d0a9877cc62a474002df32e52139f0a0`),
		}),
		WithOID(`1.2.156.10197.1.301`),
	)
}
