// Code generated by curve_generator. DO NOT EDIT.

/*
package other is a collection of named elliptic curves.

An assortment of some other curves.

https://neuromancer.sk/std/other/
*/
package other

import (
	"crypto/elliptic"
)

// BADA55R256 returns a Curve which implements other/BADA55-R-256
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func BADA55R256() elliptic.Curve {
	bADA55R256Once.Do(initBADA55R256)
	return bADA55R256Curve
}

// BADA55VPR224 returns a Curve which implements other/BADA55-VPR-224
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func BADA55VPR224() elliptic.Curve {
	bADA55VPR224Once.Do(initBADA55VPR224)
	return bADA55VPR224Curve
}

// BADA55VPR2_224 returns a Curve which implements other/BADA55-VPR2-224
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func BADA55VPR2_224() elliptic.Curve {
	bADA55VPR2_224Once.Do(initBADA55VPR2_224)
	return bADA55VPR2_224Curve
}

// BADA55VR224 returns a Curve which implements other/BADA55-VR-224
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func BADA55VR224() elliptic.Curve {
	bADA55VR224Once.Do(initBADA55VR224)
	return bADA55VR224Curve
}

// BADA55VR256 returns a Curve which implements other/BADA55-VR-256
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func BADA55VR256() elliptic.Curve {
	bADA55VR256Once.Do(initBADA55VR256)
	return bADA55VR256Curve
}

// BADA55VR384 returns a Curve which implements other/BADA55-VR-384
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func BADA55VR384() elliptic.Curve {
	bADA55VR384Once.Do(initBADA55VR384)
	return bADA55VR384Curve
}

// Curve1174 returns a Curve which implements other/Curve1174
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Curve1174() elliptic.Curve {
	curve1174Once.Do(initCurve1174)
	return curve1174Curve
}

// Curve22103 returns a Curve which implements other/Curve22103
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Curve22103() elliptic.Curve {
	curve22103Once.Do(initCurve22103)
	return curve22103Curve
}

// Curve25519 returns a Curve which implements other/Curve25519
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Curve25519() elliptic.Curve {
	curve25519Once.Do(initCurve25519)
	return curve25519Curve
}

// Curve383187 returns a Curve which implements other/Curve383187
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Curve383187() elliptic.Curve {
	curve383187Once.Do(initCurve383187)
	return curve383187Curve
}

// Curve41417 returns a Curve which implements other/Curve41417
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Curve41417() elliptic.Curve {
	curve41417Once.Do(initCurve41417)
	return curve41417Curve
}

// Curve4417 returns a Curve which implements other/Curve4417
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Curve4417() elliptic.Curve {
	curve4417Once.Do(initCurve4417)
	return curve4417Curve
}

// Curve448 returns a Curve which implements other/Curve448
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Curve448() elliptic.Curve {
	curve448Once.Do(initCurve448)
	return curve448Curve
}

// Curve67254 returns a Curve which implements other/Curve67254
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Curve67254() elliptic.Curve {
	curve67254Once.Do(initCurve67254)
	return curve67254Curve
}

// E222 returns a Curve which implements other/E-222
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func E222() elliptic.Curve {
	e222Once.Do(initE222)
	return e222Curve
}

// E382 returns a Curve which implements other/E-382
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func E382() elliptic.Curve {
	e382Once.Do(initE382)
	return e382Curve
}

// E521 returns a Curve which implements other/E-521
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func E521() elliptic.Curve {
	e521Once.Do(initE521)
	return e521Curve
}

// Ed25519 returns a Curve which implements other/Ed25519
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Ed25519() elliptic.Curve {
	ed25519Once.Do(initEd25519)
	return ed25519Curve
}

// Ed448 returns a Curve which implements other/Ed448
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Ed448() elliptic.Curve {
	ed448Once.Do(initEd448)
	return ed448Curve
}

// Ed448Goldilocks returns a Curve which implements other/Ed448-Goldilocks
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Ed448Goldilocks() elliptic.Curve {
	ed448GoldilocksOnce.Do(initEd448Goldilocks)
	return ed448GoldilocksCurve
}

// Fp224BN returns a Curve which implements other/Fp224BN
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Fp224BN() elliptic.Curve {
	fp224BNOnce.Do(initFp224BN)
	return fp224BNCurve
}

// Fp254BNa returns a Curve which implements other/Fp254BNa
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Fp254BNa() elliptic.Curve {
	fp254BNaOnce.Do(initFp254BNa)
	return fp254BNaCurve
}

// Fp254BNb returns a Curve which implements other/Fp254BNb
// https://neuromancer.sk/std/other/
// Aliases:
//   - bn/bn254
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Fp254BNb() elliptic.Curve {
	fp254BNbOnce.Do(initFp254BNb)
	return fp254BNbCurve
}

// Fp256BN returns a Curve which implements other/Fp256BN
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Fp256BN() elliptic.Curve {
	fp256BNOnce.Do(initFp256BN)
	return fp256BNCurve
}

// Fp384BN returns a Curve which implements other/Fp384BN
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Fp384BN() elliptic.Curve {
	fp384BNOnce.Do(initFp384BN)
	return fp384BNCurve
}

// Fp512BN returns a Curve which implements other/Fp512BN
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Fp512BN() elliptic.Curve {
	fp512BNOnce.Do(initFp512BN)
	return fp512BNCurve
}

// JubJub returns a Curve which implements other/JubJub
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func JubJub() elliptic.Curve {
	jubJubOnce.Do(initJubJub)
	return jubJubCurve
}

// M221 returns a Curve which implements other/M-221
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func M221() elliptic.Curve {
	m221Once.Do(initM221)
	return m221Curve
}

// M383 returns a Curve which implements other/M-383
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func M383() elliptic.Curve {
	m383Once.Do(initM383)
	return m383Curve
}

// M511 returns a Curve which implements other/M-511
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func M511() elliptic.Curve {
	m511Once.Do(initM511)
	return m511Curve
}

// MDC201601 returns a Curve which implements other/MDC201601
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func MDC201601() elliptic.Curve {
	mDC201601Once.Do(initMDC201601)
	return mDC201601Curve
}

// Pallas returns a Curve which implements other/Pallas
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Pallas() elliptic.Curve {
	pallasOnce.Do(initPallas)
	return pallasCurve
}

// Tom256 returns a Curve which implements other/Tom-256
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Tom256() elliptic.Curve {
	tom256Once.Do(initTom256)
	return tom256Curve
}

// Tom384 returns a Curve which implements other/Tom-384
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Tom384() elliptic.Curve {
	tom384Once.Do(initTom384)
	return tom384Curve
}

// Tom521 returns a Curve which implements other/Tom-521
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Tom521() elliptic.Curve {
	tom521Once.Do(initTom521)
	return tom521Curve
}

// Tweedledee returns a Curve which implements other/Tweedledee
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Tweedledee() elliptic.Curve {
	tweedledeeOnce.Do(initTweedledee)
	return tweedledeeCurve
}

// Tweedledum returns a Curve which implements other/Tweedledum
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Tweedledum() elliptic.Curve {
	tweedledumOnce.Do(initTweedledum)
	return tweedledumCurve
}

// Vesta returns a Curve which implements other/Vesta
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Vesta() elliptic.Curve {
	vestaOnce.Do(initVesta)
	return vestaCurve
}

// Ssc160 returns a Curve which implements other/ssc-160
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Ssc160() elliptic.Curve {
	ssc160Once.Do(initSsc160)
	return ssc160Curve
}

// Ssc192 returns a Curve which implements other/ssc-192
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Ssc192() elliptic.Curve {
	ssc192Once.Do(initSsc192)
	return ssc192Curve
}

// Ssc224 returns a Curve which implements other/ssc-224
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Ssc224() elliptic.Curve {
	ssc224Once.Do(initSsc224)
	return ssc224Curve
}

// Ssc256 returns a Curve which implements other/ssc-256
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Ssc256() elliptic.Curve {
	ssc256Once.Do(initSsc256)
	return ssc256Curve
}

// Ssc288 returns a Curve which implements other/ssc-288
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Ssc288() elliptic.Curve {
	ssc288Once.Do(initSsc288)
	return ssc288Curve
}

// Ssc320 returns a Curve which implements other/ssc-320
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Ssc320() elliptic.Curve {
	ssc320Once.Do(initSsc320)
	return ssc320Curve
}

// Ssc384 returns a Curve which implements other/ssc-384
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Ssc384() elliptic.Curve {
	ssc384Once.Do(initSsc384)
	return ssc384Curve
}

// Ssc512 returns a Curve which implements other/ssc-512
// https://neuromancer.sk/std/other/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Ssc512() elliptic.Curve {
	ssc512Once.Do(initSsc512)
	return ssc512Curve
}
