// Code generated by curve_generator. DO NOT EDIT.

/*
package other is a collection of named elliptic curves.

An assortment of some other curves.

https://neuromancer.sk/std/other/
*/
package other

import (
	"crypto/elliptic"

	"github.com/RyuaNerin/elliptic2/internal/curves"
)

// BADA55R256 returns a Curve which implements other/BADA55-R-256
// https://neuromancer.sk/std/other/BADA55-R-256
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func BADA55R256() elliptic.Curve {
	return curves.OtherBADA55R256()
}

// BADA55VPR224 returns a Curve which implements other/BADA55-VPR-224
// https://neuromancer.sk/std/other/BADA55-VPR-224
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func BADA55VPR224() elliptic.Curve {
	return curves.OtherBADA55VPR224()
}

// BADA55VPR2_224 returns a Curve which implements other/BADA55-VPR2-224
// https://neuromancer.sk/std/other/BADA55-VPR2-224
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func BADA55VPR2_224() elliptic.Curve {
	return curves.OtherBADA55VPR2_224()
}

// BADA55VR224 returns a Curve which implements other/BADA55-VR-224
// https://neuromancer.sk/std/other/BADA55-VR-224
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func BADA55VR224() elliptic.Curve {
	return curves.OtherBADA55VR224()
}

// BADA55VR256 returns a Curve which implements other/BADA55-VR-256
// https://neuromancer.sk/std/other/BADA55-VR-256
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func BADA55VR256() elliptic.Curve {
	return curves.OtherBADA55VR256()
}

// BADA55VR384 returns a Curve which implements other/BADA55-VR-384
// https://neuromancer.sk/std/other/BADA55-VR-384
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func BADA55VR384() elliptic.Curve {
	return curves.OtherBADA55VR384()
}

// Curve1174 returns a Curve which implements other/Curve1174
// https://neuromancer.sk/std/other/Curve1174
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Curve1174() elliptic.Curve {
	return curves.OtherCurve1174()
}

// Curve22103 returns a Curve which implements other/Curve22103
// https://neuromancer.sk/std/other/Curve22103
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Curve22103() elliptic.Curve {
	return curves.OtherCurve22103()
}

// Curve25519 returns a Curve which implements other/Curve25519
// https://neuromancer.sk/std/other/Curve25519
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Curve25519() elliptic.Curve {
	return curves.OtherCurve25519()
}

// Curve383187 returns a Curve which implements other/Curve383187
// https://neuromancer.sk/std/other/Curve383187
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Curve383187() elliptic.Curve {
	return curves.OtherCurve383187()
}

// Curve41417 returns a Curve which implements other/Curve41417
// https://neuromancer.sk/std/other/Curve41417
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Curve41417() elliptic.Curve {
	return curves.OtherCurve41417()
}

// Curve4417 returns a Curve which implements other/Curve4417
// https://neuromancer.sk/std/other/Curve4417
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Curve4417() elliptic.Curve {
	return curves.OtherCurve4417()
}

// Curve448 returns a Curve which implements other/Curve448
// https://neuromancer.sk/std/other/Curve448
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Curve448() elliptic.Curve {
	return curves.OtherCurve448()
}

// Curve67254 returns a Curve which implements other/Curve67254
// https://neuromancer.sk/std/other/Curve67254
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Curve67254() elliptic.Curve {
	return curves.OtherCurve67254()
}

// E222 returns a Curve which implements other/E-222
// https://neuromancer.sk/std/other/E-222
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func E222() elliptic.Curve {
	return curves.OtherE222()
}

// E382 returns a Curve which implements other/E-382
// https://neuromancer.sk/std/other/E-382
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func E382() elliptic.Curve {
	return curves.OtherE382()
}

// E521 returns a Curve which implements other/E-521
// https://neuromancer.sk/std/other/E-521
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func E521() elliptic.Curve {
	return curves.OtherE521()
}

// Ed25519 returns a Curve which implements other/Ed25519
// https://neuromancer.sk/std/other/Ed25519
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Ed25519() elliptic.Curve {
	return curves.OtherEd25519()
}

// Ed448 returns a Curve which implements other/Ed448
// https://neuromancer.sk/std/other/Ed448
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Ed448() elliptic.Curve {
	return curves.OtherEd448()
}

// Ed448Goldilocks returns a Curve which implements other/Ed448-Goldilocks
// https://neuromancer.sk/std/other/Ed448-Goldilocks
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Ed448Goldilocks() elliptic.Curve {
	return curves.OtherEd448Goldilocks()
}

// Fp224BN returns a Curve which implements other/Fp224BN
// https://neuromancer.sk/std/other/Fp224BN
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Fp224BN() elliptic.Curve {
	return curves.OtherFp224BN()
}

// Fp254BNa returns a Curve which implements other/Fp254BNa
// https://neuromancer.sk/std/other/Fp254BNa
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Fp254BNa() elliptic.Curve {
	return curves.OtherFp254BNa()
}

// Fp254BNb returns a Curve which implements other/Fp254BNb
// https://neuromancer.sk/std/other/Fp254BNb
// Aliases:
//   - bn/bn254
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Fp254BNb() elliptic.Curve {
	return curves.BnBn254()
}

// Fp256BN returns a Curve which implements other/Fp256BN
// https://neuromancer.sk/std/other/Fp256BN
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Fp256BN() elliptic.Curve {
	return curves.OtherFp256BN()
}

// Fp384BN returns a Curve which implements other/Fp384BN
// https://neuromancer.sk/std/other/Fp384BN
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Fp384BN() elliptic.Curve {
	return curves.OtherFp384BN()
}

// Fp512BN returns a Curve which implements other/Fp512BN
// https://neuromancer.sk/std/other/Fp512BN
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Fp512BN() elliptic.Curve {
	return curves.OtherFp512BN()
}

// JubJub returns a Curve which implements other/JubJub
// https://neuromancer.sk/std/other/JubJub
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func JubJub() elliptic.Curve {
	return curves.OtherJubJub()
}

// M221 returns a Curve which implements other/M-221
// https://neuromancer.sk/std/other/M-221
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func M221() elliptic.Curve {
	return curves.OtherM221()
}

// M383 returns a Curve which implements other/M-383
// https://neuromancer.sk/std/other/M-383
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func M383() elliptic.Curve {
	return curves.OtherM383()
}

// M511 returns a Curve which implements other/M-511
// https://neuromancer.sk/std/other/M-511
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func M511() elliptic.Curve {
	return curves.OtherM511()
}

// MDC201601 returns a Curve which implements other/MDC201601
// https://neuromancer.sk/std/other/MDC201601
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func MDC201601() elliptic.Curve {
	return curves.OtherMDC201601()
}

// Pallas returns a Curve which implements other/Pallas
// https://neuromancer.sk/std/other/Pallas
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Pallas() elliptic.Curve {
	return curves.OtherPallas()
}

// Tom256 returns a Curve which implements other/Tom-256
// https://neuromancer.sk/std/other/Tom-256
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Tom256() elliptic.Curve {
	return curves.OtherTom256()
}

// Tom384 returns a Curve which implements other/Tom-384
// https://neuromancer.sk/std/other/Tom-384
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Tom384() elliptic.Curve {
	return curves.OtherTom384()
}

// Tom521 returns a Curve which implements other/Tom-521
// https://neuromancer.sk/std/other/Tom-521
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Tom521() elliptic.Curve {
	return curves.OtherTom521()
}

// Tweedledee returns a Curve which implements other/Tweedledee
// https://neuromancer.sk/std/other/Tweedledee
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Tweedledee() elliptic.Curve {
	return curves.OtherTweedledee()
}

// Tweedledum returns a Curve which implements other/Tweedledum
// https://neuromancer.sk/std/other/Tweedledum
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Tweedledum() elliptic.Curve {
	return curves.OtherTweedledum()
}

// Vesta returns a Curve which implements other/Vesta
// https://neuromancer.sk/std/other/Vesta
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Vesta() elliptic.Curve {
	return curves.OtherVesta()
}

// Ssc160 returns a Curve which implements other/ssc-160
// https://neuromancer.sk/std/other/ssc-160
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Ssc160() elliptic.Curve {
	return curves.OtherSsc160()
}

// Ssc192 returns a Curve which implements other/ssc-192
// https://neuromancer.sk/std/other/ssc-192
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Ssc192() elliptic.Curve {
	return curves.OtherSsc192()
}

// Ssc224 returns a Curve which implements other/ssc-224
// https://neuromancer.sk/std/other/ssc-224
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Ssc224() elliptic.Curve {
	return curves.OtherSsc224()
}

// Ssc256 returns a Curve which implements other/ssc-256
// https://neuromancer.sk/std/other/ssc-256
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Ssc256() elliptic.Curve {
	return curves.OtherSsc256()
}

// Ssc288 returns a Curve which implements other/ssc-288
// https://neuromancer.sk/std/other/ssc-288
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Ssc288() elliptic.Curve {
	return curves.OtherSsc288()
}

// Ssc320 returns a Curve which implements other/ssc-320
// https://neuromancer.sk/std/other/ssc-320
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Ssc320() elliptic.Curve {
	return curves.OtherSsc320()
}

// Ssc384 returns a Curve which implements other/ssc-384
// https://neuromancer.sk/std/other/ssc-384
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Ssc384() elliptic.Curve {
	return curves.OtherSsc384()
}

// Ssc512 returns a Curve which implements other/ssc-512
// https://neuromancer.sk/std/other/ssc-512
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Ssc512() elliptic.Curve {
	return curves.OtherSsc512()
}
