// Code generated by curve_generator. DO NOT EDIT.

package elliptic2_test

import (
	"crypto/elliptic"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/RyuaNerin/elliptic2"
	"github.com/RyuaNerin/elliptic2/bn"
	"github.com/RyuaNerin/elliptic2/nist"
	"github.com/RyuaNerin/elliptic2/oakley"
	"github.com/RyuaNerin/elliptic2/other"
	"github.com/RyuaNerin/elliptic2/secg"
	"github.com/RyuaNerin/elliptic2/wtls"
	"github.com/RyuaNerin/elliptic2/x962"
	"github.com/RyuaNerin/elliptic2/x963"
)

type namedEquivalentCurve struct {
	name  string
	curve elliptic2.Curve
	oid   string
}

func TestEquivalentCurveAliases(t *testing.T) {
	groups := [][]namedEquivalentCurve{
		{
			{"nist/B-163", nist.B163(), "1.3.132.0.15"},
			{"secg/sect163r2", secg.Sect163r2(), "1.3.132.0.15"},
			{"x963/ansit163r2", x963.Ansit163r2(), "1.3.132.0.15"},
		},
		{
			{"nist/B-233", nist.B233(), "1.3.132.0.27"},
			{"secg/sect233r1", secg.Sect233r1(), "1.3.132.0.27"},
			{"x963/ansit233r1", x963.Ansit233r1(), "1.3.132.0.27"},
			{"wtls/wap-wsg-idm-ecid-wtls11", wtls.WapWsgIdmEcidWtls11(), "2.23.43.1.4.11"},
		},
		{
			{"nist/B-283", nist.B283(), "1.3.132.0.17"},
			{"secg/sect283r1", secg.Sect283r1(), "1.3.132.0.17"},
			{"x963/ansit283r1", x963.Ansit283r1(), "1.3.132.0.17"},
		},
		{
			{"nist/B-409", nist.B409(), "1.3.132.0.37"},
			{"secg/sect409r1", secg.Sect409r1(), "1.3.132.0.37"},
			{"x963/ansit409r1", x963.Ansit409r1(), "1.3.132.0.37"},
		},
		{
			{"nist/B-571", nist.B571(), "1.3.132.0.39"},
			{"secg/sect571r1", secg.Sect571r1(), "1.3.132.0.39"},
			{"x963/ansit571r1", x963.Ansit571r1(), "1.3.132.0.39"},
		},
		{
			{"nist/K-163", nist.K163(), "1.3.132.0.1"},
			{"secg/sect163k1", secg.Sect163k1(), "1.3.132.0.1"},
			{"x963/ansit163k1", x963.Ansit163k1(), "1.3.132.0.1"},
			{"wtls/wap-wsg-idm-ecid-wtls3", wtls.WapWsgIdmEcidWtls3(), "2.23.43.1.4.3"},
		},
		{
			{"nist/K-233", nist.K233(), "1.3.132.0.26"},
			{"secg/sect233k1", secg.Sect233k1(), "1.3.132.0.26"},
			{"x963/ansit233k1", x963.Ansit233k1(), "1.3.132.0.26"},
			{"wtls/wap-wsg-idm-ecid-wtls10", wtls.WapWsgIdmEcidWtls10(), "2.23.43.1.4.10"},
		},
		{
			{"nist/K-283", nist.K283(), "1.3.132.0.16"},
			{"secg/sect283k1", secg.Sect283k1(), "1.3.132.0.16"},
			{"x963/ansit283k1", x963.Ansit283k1(), "1.3.132.0.16"},
		},
		{
			{"nist/K-409", nist.K409(), "1.3.132.0.36"},
			{"secg/sect409k1", secg.Sect409k1(), "1.3.132.0.36"},
			{"x963/ansit409k1", x963.Ansit409k1(), "1.3.132.0.36"},
		},
		{
			{"nist/K-571", nist.K571(), "1.3.132.0.38"},
			{"secg/sect571k1", secg.Sect571k1(), "1.3.132.0.38"},
			{"x963/ansit571k1", x963.Ansit571k1(), "1.3.132.0.38"},
		},
		{
			{"nist/P-192", nist.P192(), "1.2.840.10045.3.1.1"},
			{"secg/secp192r1", secg.Secp192r1(), "1.2.840.10045.3.1.1"},
			{"x962/prime192v1", x962.Prime192v1(), "1.2.840.10045.3.1.1"},
			{"oakley/192-bit Random ECP Group", oakley.Oakley192BitRandomECPGroup(), ""},
		},
		{
			{"nist/P-224", nist.P224(), "1.3.132.0.33"},
			{"crypto/elliptic.P224", elliptic.P224(), "1.3.132.0.33"},
			{"secg/secp224r1", secg.Secp224r1(), "1.3.132.0.33"},
			{"x963/ansip224r1", x963.Ansip224r1(), "1.3.132.0.33"},
			{"oakley/224-bit Random ECP Group", oakley.Oakley224BitRandomECPGroup(), ""},
			{"wtls/wap-wsg-idm-ecid-wtls12", wtls.WapWsgIdmEcidWtls12(), "2.23.43.1.4.12"},
		},
		{
			{"nist/P-256", nist.P256(), "1.2.840.10045.3.1.7"},
			{"crypto/elliptic.P256", elliptic.P256(), "1.2.840.10045.3.1.7"},
			{"secg/secp256r1", secg.Secp256r1(), "1.2.840.10045.3.1.7"},
			{"x962/prime256v1", x962.Prime256v1(), "1.2.840.10045.3.1.7"},
			{"oakley/256-bit Random ECP Group", oakley.Oakley256BitRandomECPGroup(), ""},
		},
		{
			{"nist/P-384", nist.P384(), "1.3.132.0.34"},
			{"crypto/elliptic.P384", elliptic.P384(), "1.3.132.0.34"},
			{"secg/secp384r1", secg.Secp384r1(), "1.3.132.0.34"},
			{"x963/ansip384r1", x963.Ansip384r1(), "1.3.132.0.34"},
			{"oakley/384-bit Random ECP Group", oakley.Oakley384BitRandomECPGroup(), ""},
		},
		{
			{"nist/P-521", nist.P521(), "1.3.132.0.35"},
			{"crypto/elliptic.P521", elliptic.P521(), "1.3.132.0.35"},
			{"secg/secp521r1", secg.Secp521r1(), "1.3.132.0.35"},
			{"x963/ansip521r1", x963.Ansip521r1(), "1.3.132.0.35"},
			{"oakley/521-bit Random ECP Group", oakley.Oakley521BitRandomECPGroup(), ""},
		},
		{
			{"secg/secp112r1", secg.Secp112r1(), "1.3.132.0.6"},
			{"wtls/wap-wsg-idm-ecid-wtls6", wtls.WapWsgIdmEcidWtls6(), "2.23.43.1.4.6"},
		},
		{
			{"secg/secp160k1", secg.Secp160k1(), "1.3.132.0.9"},
			{"x963/ansip160k1", x963.Ansip160k1(), "1.3.132.0.9"},
		},
		{
			{"secg/secp160r1", secg.Secp160r1(), "1.3.132.0.8"},
			{"x963/ansip160r1", x963.Ansip160r1(), "1.3.132.0.8"},
			{"wtls/wap-wsg-idm-ecid-wtls7", wtls.WapWsgIdmEcidWtls7(), "2.23.43.1.4.7"},
		},
		{
			{"secg/secp160r2", secg.Secp160r2(), "1.3.132.0.30"},
			{"x963/ansip160r2", x963.Ansip160r2(), "1.3.132.0.30"},
		},
		{
			{"secg/secp192k1", secg.Secp192k1(), "1.3.132.0.31"},
			{"x963/ansip192k1", x963.Ansip192k1(), "1.3.132.0.31"},
		},
		{
			{"secg/secp224k1", secg.Secp224k1(), "1.3.132.0.32"},
			{"x963/ansip224k1", x963.Ansip224k1(), "1.3.132.0.32"},
		},
		{
			{"secg/secp256k1", secg.Secp256k1(), "1.3.132.0.10"},
			{"x963/ansip256k1", x963.Ansip256k1(), "1.3.132.0.10"},
		},
		{
			{"secg/sect113r1", secg.Sect113r1(), "1.3.132.0.4"},
			{"wtls/wap-wsg-idm-ecid-wtls4", wtls.WapWsgIdmEcidWtls4(), "2.23.43.1.4.4"},
		},
		{
			{"secg/sect163r1", secg.Sect163r1(), "1.3.132.0.2"},
			{"x963/ansit163r1", x963.Ansit163r1(), "1.3.132.0.2"},
		},
		{
			{"secg/sect193r1", secg.Sect193r1(), "1.3.132.0.24"},
			{"x963/ansit193r1", x963.Ansit193r1(), "1.3.132.0.24"},
		},
		{
			{"secg/sect193r2", secg.Sect193r2(), "1.3.132.0.25"},
			{"x963/ansit193r2", x963.Ansit193r2(), "1.3.132.0.25"},
		},
		{
			{"secg/sect239k1", secg.Sect239k1(), "1.3.132.0.3"},
			{"x963/ansit239k1", x963.Ansit239k1(), "1.3.132.0.3"},
		},
		{
			{"x962/c2pnb163v1", x962.C2pnb163v1(), "1.2.840.10045.3.0.1"},
			{"wtls/wap-wsg-idm-ecid-wtls5", wtls.WapWsgIdmEcidWtls5(), "2.23.43.1.4.5"},
		},
		{
			{"bn/bn254", bn.Bn254(), ""},
			{"other/Fp254BNb", other.Fp254BNb(), ""},
		},
	}

	for _, group := range groups {
		t.Run(group[0].name, func(t *testing.T) {
			for idx1 := range group {
				if extended, ok := group[idx1].curve.(elliptic2.CurveExtended); ok {
					require.True(t, ok, "%s does not implement CurveExtended", group[idx1].name)
					require.Equal(t, group[idx1].oid, extended.OID().String(), "%s OID mismatch", group[idx1].name)
				}

				for idx2 := range group {
					require.True(t, elliptic2.IsEquivalentCurve(group[idx1].curve, group[idx2].curve), "%s and %s are not equivalent", group[idx1].name, group[idx2].name)

					sameOID := group[idx1].oid == group[idx2].oid
					require.Equal(t, sameOID, elliptic2.IsEquivalentCurveWithOID(group[idx1].curve, group[idx2].curve), "%s and %s OID equivalence mismatch", group[idx1].name, group[idx2].name)
				}
			}
		})
	}

	require.True(t, elliptic2.IsEquivalentCurve(elliptic.P256(), nist.P256()))
	require.True(t, elliptic2.IsEquivalentCurve(nist.P256(), elliptic.P256()))

	require.False(t, elliptic2.IsEquivalentCurve(nil, nil), "IsEquivalentCurve(nil, nil) = true")

	if len(groups) > 1 {
		require.False(t, elliptic2.IsEquivalentCurve(groups[0][0].curve, groups[1][0].curve), "unrelated curves %s and %s are equivalent", groups[0][0].name, groups[1][0].name)
	}
}
