from collections.abc import Iterator
from typing import Any, overload

class FiniteFieldElement:
    def __int__(self) -> int: ...
    def __add__(self, other: Any) -> FiniteFieldElement: ...
    def __radd__(self, other: Any) -> FiniteFieldElement: ...
    def __sub__(self, other: Any) -> FiniteFieldElement: ...
    def __rsub__(self, other: Any) -> FiniteFieldElement: ...
    def __mul__(self, other: Any) -> FiniteFieldElement: ...
    def __rmul__(self, other: Any) -> FiniteFieldElement: ...
    def __truediv__(self, other: Any) -> FiniteFieldElement: ...
    def __rtruediv__(self, other: Any) -> FiniteFieldElement: ...
    def __pow__(self, exponent: int) -> FiniteFieldElement: ...
    def __neg__(self) -> FiniteFieldElement: ...
    def to_integer(self) -> int: ...

class Polynomial:
    def __add__(self, other: Any) -> Polynomial: ...
    def __radd__(self, other: Any) -> Polynomial: ...
    def __pow__(self, exponent: int) -> Polynomial: ...

class PolynomialRing:
    def _first_ngens(self, count: int) -> tuple[Polynomial, ...]: ...

class FiniteField:
    def __call__(self, value: Any) -> FiniteFieldElement: ...
    def __getitem__(self, name: str) -> PolynomialRing: ...
    def from_integer(self, value: int) -> FiniteFieldElement: ...

class Point:
    def __iter__(self) -> Iterator[FiniteFieldElement]: ...
    @overload
    def __getitem__(self, index: int) -> FiniteFieldElement: ...
    @overload
    def __getitem__(self, index: slice) -> tuple[FiniteFieldElement, ...]: ...
    def __add__(self, other: Point) -> Point: ...
    def __mul__(self, scalar: int) -> Point: ...
    def __rmul__(self, scalar: int) -> Point: ...

class EllipticCurveObject:
    def __call__(self, *coordinates: Any) -> Point: ...
    def set_order(
        self, value: int, check: bool = ..., num_checks: int = ...
    ) -> None: ...
    def random_point(self) -> Point: ...
    def is_on_curve(self, x: Any, y: Any) -> bool: ...

def GF(order: int, name: str = ..., modulus: Any = ...) -> FiniteField: ...
def EllipticCurve(field: FiniteField, coefficients: Any) -> EllipticCurveObject: ...
def set_random_seed(seed: int) -> None: ...
