// Code generated by curve_generator. DO NOT EDIT.

/*
package bn is a collection of named elliptic curves.

BN (Barreto, Naehrig curves) from: A Family of Implementation-Friendly BN Elliptic Curves - <https://eprint.iacr.org/2010/429.pdf>.

https://neuromancer.sk/std/bn/
*/
package bn

import (
	"crypto/elliptic"
)

// Bn158 returns a Curve which implements bn/bn158
// https://neuromancer.sk/std/bn/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Bn158() elliptic.Curve {
	bn158Once.Do(initBn158)
	return bn158Curve
}

// Bn190 returns a Curve which implements bn/bn190
// https://neuromancer.sk/std/bn/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Bn190() elliptic.Curve {
	bn190Once.Do(initBn190)
	return bn190Curve
}

// Bn222 returns a Curve which implements bn/bn222
// https://neuromancer.sk/std/bn/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Bn222() elliptic.Curve {
	bn222Once.Do(initBn222)
	return bn222Curve
}

// Bn254 returns a Curve which implements bn/bn254
// https://neuromancer.sk/std/bn/
// Aliases:
//   - other/Fp254BNb
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Bn254() elliptic.Curve {
	bn254Once.Do(initBn254)
	return bn254Curve
}

// Bn286 returns a Curve which implements bn/bn286
// https://neuromancer.sk/std/bn/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Bn286() elliptic.Curve {
	bn286Once.Do(initBn286)
	return bn286Curve
}

// Bn318 returns a Curve which implements bn/bn318
// https://neuromancer.sk/std/bn/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Bn318() elliptic.Curve {
	bn318Once.Do(initBn318)
	return bn318Curve
}

// Bn350 returns a Curve which implements bn/bn350
// https://neuromancer.sk/std/bn/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Bn350() elliptic.Curve {
	bn350Once.Do(initBn350)
	return bn350Curve
}

// Bn382 returns a Curve which implements bn/bn382
// https://neuromancer.sk/std/bn/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Bn382() elliptic.Curve {
	bn382Once.Do(initBn382)
	return bn382Curve
}

// Bn414 returns a Curve which implements bn/bn414
// https://neuromancer.sk/std/bn/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Bn414() elliptic.Curve {
	bn414Once.Do(initBn414)
	return bn414Curve
}

// Bn446 returns a Curve which implements bn/bn446
// https://neuromancer.sk/std/bn/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Bn446() elliptic.Curve {
	bn446Once.Do(initBn446)
	return bn446Curve
}

// Bn478 returns a Curve which implements bn/bn478
// https://neuromancer.sk/std/bn/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Bn478() elliptic.Curve {
	bn478Once.Do(initBn478)
	return bn478Curve
}

// Bn510 returns a Curve which implements bn/bn510
// https://neuromancer.sk/std/bn/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Bn510() elliptic.Curve {
	bn510Once.Do(initBn510)
	return bn510Curve
}

// Bn542 returns a Curve which implements bn/bn542
// https://neuromancer.sk/std/bn/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Bn542() elliptic.Curve {
	bn542Once.Do(initBn542)
	return bn542Curve
}

// Bn574 returns a Curve which implements bn/bn574
// https://neuromancer.sk/std/bn/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Bn574() elliptic.Curve {
	bn574Once.Do(initBn574)
	return bn574Curve
}

// Bn606 returns a Curve which implements bn/bn606
// https://neuromancer.sk/std/bn/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Bn606() elliptic.Curve {
	bn606Once.Do(initBn606)
	return bn606Curve
}

// Bn638 returns a Curve which implements bn/bn638
// https://neuromancer.sk/std/bn/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Bn638() elliptic.Curve {
	bn638Once.Do(initBn638)
	return bn638Curve
}
