// Code generated by curve_generator. DO NOT EDIT.

/*
package bn is a collection of named elliptic curves.

BN (Barreto, Naehrig curves) from: A Family of Implementation-Friendly BN Elliptic Curves - <https://eprint.iacr.org/2010/429.pdf>.

https://neuromancer.sk/std/bn/
*/
package bn

import (
	"crypto/elliptic"

	"github.com/RyuaNerin/elliptic2/internal/curves"
)

// Bn158 returns a Curve which implements bn/bn158
// https://neuromancer.sk/std/bn/bn158
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Bn158() elliptic.Curve {
	return curves.BnBn158()
}

// Bn190 returns a Curve which implements bn/bn190
// https://neuromancer.sk/std/bn/bn190
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Bn190() elliptic.Curve {
	return curves.BnBn190()
}

// Bn222 returns a Curve which implements bn/bn222
// https://neuromancer.sk/std/bn/bn222
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Bn222() elliptic.Curve {
	return curves.BnBn222()
}

// Bn254 returns a Curve which implements bn/bn254
// https://neuromancer.sk/std/bn/bn254
// Aliases:
//   - other/Fp254BNb
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Bn254() elliptic.Curve {
	return curves.BnBn254()
}

// Bn286 returns a Curve which implements bn/bn286
// https://neuromancer.sk/std/bn/bn286
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Bn286() elliptic.Curve {
	return curves.BnBn286()
}

// Bn318 returns a Curve which implements bn/bn318
// https://neuromancer.sk/std/bn/bn318
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Bn318() elliptic.Curve {
	return curves.BnBn318()
}

// Bn350 returns a Curve which implements bn/bn350
// https://neuromancer.sk/std/bn/bn350
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Bn350() elliptic.Curve {
	return curves.BnBn350()
}

// Bn382 returns a Curve which implements bn/bn382
// https://neuromancer.sk/std/bn/bn382
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Bn382() elliptic.Curve {
	return curves.BnBn382()
}

// Bn414 returns a Curve which implements bn/bn414
// https://neuromancer.sk/std/bn/bn414
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Bn414() elliptic.Curve {
	return curves.BnBn414()
}

// Bn446 returns a Curve which implements bn/bn446
// https://neuromancer.sk/std/bn/bn446
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Bn446() elliptic.Curve {
	return curves.BnBn446()
}

// Bn478 returns a Curve which implements bn/bn478
// https://neuromancer.sk/std/bn/bn478
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Bn478() elliptic.Curve {
	return curves.BnBn478()
}

// Bn510 returns a Curve which implements bn/bn510
// https://neuromancer.sk/std/bn/bn510
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Bn510() elliptic.Curve {
	return curves.BnBn510()
}

// Bn542 returns a Curve which implements bn/bn542
// https://neuromancer.sk/std/bn/bn542
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Bn542() elliptic.Curve {
	return curves.BnBn542()
}

// Bn574 returns a Curve which implements bn/bn574
// https://neuromancer.sk/std/bn/bn574
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Bn574() elliptic.Curve {
	return curves.BnBn574()
}

// Bn606 returns a Curve which implements bn/bn606
// https://neuromancer.sk/std/bn/bn606
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Bn606() elliptic.Curve {
	return curves.BnBn606()
}

// Bn638 returns a Curve which implements bn/bn638
// https://neuromancer.sk/std/bn/bn638
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Bn638() elliptic.Curve {
	return curves.BnBn638()
}
