// Code generated by curve_generator. DO NOT EDIT.

/*
package secg is a collection of named elliptic curves.

SEC 2: Recommended Elliptic Curve Domain Parameters version 2.0  January 27, 2010

https://neuromancer.sk/std/secg/
*/
package secg

import (
	"crypto/elliptic"
)

// Secp112r1 returns a Curve which implements secg/secp112r1
// https://neuromancer.sk/std/secg/
//
// OID: 1.3.132.0.6
// Aliases:
//   - wtls/wap-wsg-idm-ecid-wtls6
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Secp112r1() elliptic.Curve {
	secp112r1Once.Do(initSecp112r1)
	return secp112r1Curve
}

// Secp112r2 returns a Curve which implements secg/secp112r2
// https://neuromancer.sk/std/secg/
//
// OID: 1.3.132.0.7
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Secp112r2() elliptic.Curve {
	secp112r2Once.Do(initSecp112r2)
	return secp112r2Curve
}

// Secp128r1 returns a Curve which implements secg/secp128r1
// https://neuromancer.sk/std/secg/
//
// OID: 1.3.132.0.28
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Secp128r1() elliptic.Curve {
	secp128r1Once.Do(initSecp128r1)
	return secp128r1Curve
}

// Secp128r2 returns a Curve which implements secg/secp128r2
// https://neuromancer.sk/std/secg/
//
// OID: 1.3.132.0.29
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Secp128r2() elliptic.Curve {
	secp128r2Once.Do(initSecp128r2)
	return secp128r2Curve
}

// Secp160k1 returns a Curve which implements secg/secp160k1
// https://neuromancer.sk/std/secg/
//
// OID: 1.3.132.0.9
// Aliases:
//   - x963/ansip160k1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Secp160k1() elliptic.Curve {
	secp160k1Once.Do(initSecp160k1)
	return secp160k1Curve
}

// Secp160r1 returns a Curve which implements secg/secp160r1
// https://neuromancer.sk/std/secg/
//
// OID: 1.3.132.0.8
// Aliases:
//   - wtls/wap-wsg-idm-ecid-wtls7
//   - x963/ansip160r1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Secp160r1() elliptic.Curve {
	secp160r1Once.Do(initSecp160r1)
	return secp160r1Curve
}

// Secp160r2 returns a Curve which implements secg/secp160r2
// https://neuromancer.sk/std/secg/
//
// OID: 1.3.132.0.30
// Aliases:
//   - x963/ansip160r2
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Secp160r2() elliptic.Curve {
	secp160r2Once.Do(initSecp160r2)
	return secp160r2Curve
}

// Secp192k1 returns a Curve which implements secg/secp192k1
// https://neuromancer.sk/std/secg/
//
// OID: 1.3.132.0.31
// Aliases:
//   - x963/ansip192k1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Secp192k1() elliptic.Curve {
	secp192k1Once.Do(initSecp192k1)
	return secp192k1Curve
}

// Secp192r1 returns a Curve which implements secg/secp192r1
// https://neuromancer.sk/std/secg/
//
// OID: 1.2.840.10045.3.1.1
// Aliases:
//   - nist/P-192
//   - x962/prime192v1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Secp192r1() elliptic.Curve {
	secp192r1Once.Do(initSecp192r1)
	return secp192r1Curve
}

// Secp224k1 returns a Curve which implements secg/secp224k1
// https://neuromancer.sk/std/secg/
//
// OID: 1.3.132.0.32
// Aliases:
//   - x963/ansip224k1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Secp224k1() elliptic.Curve {
	secp224k1Once.Do(initSecp224k1)
	return secp224k1Curve
}

// Secp224r1 returns a Curve which implements secg/secp224r1
// https://neuromancer.sk/std/secg/
//
// OID: 1.3.132.0.33
// Aliases:
//   - nist/P-224
//   - wtls/wap-wsg-idm-ecid-wtls12
//   - x963/ansip224r1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Secp224r1() elliptic.Curve {
	secp224r1Once.Do(initSecp224r1)
	return secp224r1Curve
}

// Secp256k1 returns a Curve which implements secg/secp256k1
// https://neuromancer.sk/std/secg/
//
// OID: 1.3.132.0.10
// Aliases:
//   - x963/ansip256k1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Secp256k1() elliptic.Curve {
	secp256k1Once.Do(initSecp256k1)
	return secp256k1Curve
}

// Secp256r1 returns a Curve which implements secg/secp256r1
// https://neuromancer.sk/std/secg/
//
// OID: 1.2.840.10045.3.1.7
// Aliases:
//   - nist/P-256
//   - x962/prime256v1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Secp256r1() elliptic.Curve {
	secp256r1Once.Do(initSecp256r1)
	return secp256r1Curve
}

// Secp384r1 returns a Curve which implements secg/secp384r1
// https://neuromancer.sk/std/secg/
//
// OID: 1.3.132.0.34
// Aliases:
//   - nist/P-384
//   - x963/ansip384r1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Secp384r1() elliptic.Curve {
	secp384r1Once.Do(initSecp384r1)
	return secp384r1Curve
}

// Secp521r1 returns a Curve which implements secg/secp521r1
// https://neuromancer.sk/std/secg/
//
// OID: 1.3.132.0.35
// Aliases:
//   - nist/P-521
//   - x963/ansip521r1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Secp521r1() elliptic.Curve {
	secp521r1Once.Do(initSecp521r1)
	return secp521r1Curve
}

// Sect113r1 returns a Curve which implements secg/sect113r1
// https://neuromancer.sk/std/secg/
//
// OID: 1.3.132.0.4
// Aliases:
//   - wtls/wap-wsg-idm-ecid-wtls4
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Sect113r1() elliptic.Curve {
	sect113r1Once.Do(initSect113r1)
	return sect113r1Curve
}

// Sect113r2 returns a Curve which implements secg/sect113r2
// https://neuromancer.sk/std/secg/
//
// OID: 1.3.132.0.5
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Sect113r2() elliptic.Curve {
	sect113r2Once.Do(initSect113r2)
	return sect113r2Curve
}

// Sect131r1 returns a Curve which implements secg/sect131r1
// https://neuromancer.sk/std/secg/
//
// OID: 1.3.132.0.22
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Sect131r1() elliptic.Curve {
	sect131r1Once.Do(initSect131r1)
	return sect131r1Curve
}

// Sect131r2 returns a Curve which implements secg/sect131r2
// https://neuromancer.sk/std/secg/
//
// OID: 1.3.132.0.23
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Sect131r2() elliptic.Curve {
	sect131r2Once.Do(initSect131r2)
	return sect131r2Curve
}

// Sect163k1 returns a Curve which implements secg/sect163k1
// https://neuromancer.sk/std/secg/
//
// OID: 1.3.132.0.1
// Aliases:
//   - nist/K-163
//   - x963/ansit163k1
//   - wtls/wap-wsg-idm-ecid-wtls3
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Sect163k1() elliptic.Curve {
	sect163k1Once.Do(initSect163k1)
	return sect163k1Curve
}

// Sect163r1 returns a Curve which implements secg/sect163r1
// https://neuromancer.sk/std/secg/
//
// OID: 1.3.132.0.2
// Aliases:
//   - x963/ansit163r1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Sect163r1() elliptic.Curve {
	sect163r1Once.Do(initSect163r1)
	return sect163r1Curve
}

// Sect163r2 returns a Curve which implements secg/sect163r2
// https://neuromancer.sk/std/secg/
//
// OID: 1.3.132.0.15
// Aliases:
//   - nist/B-163
//   - x963/ansit163r2
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Sect163r2() elliptic.Curve {
	sect163r2Once.Do(initSect163r2)
	return sect163r2Curve
}

// Sect193r1 returns a Curve which implements secg/sect193r1
// https://neuromancer.sk/std/secg/
//
// OID: 1.3.132.0.24
// Aliases:
//   - x963/ansit193r1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Sect193r1() elliptic.Curve {
	sect193r1Once.Do(initSect193r1)
	return sect193r1Curve
}

// Sect193r2 returns a Curve which implements secg/sect193r2
// https://neuromancer.sk/std/secg/
//
// OID: 1.3.132.0.25
// Aliases:
//   - x963/ansit193r2
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Sect193r2() elliptic.Curve {
	sect193r2Once.Do(initSect193r2)
	return sect193r2Curve
}

// Sect233k1 returns a Curve which implements secg/sect233k1
// https://neuromancer.sk/std/secg/
//
// OID: 1.3.132.0.26
// Aliases:
//   - nist/K-233
//   - wtls/wap-wsg-idm-ecid-wtls10
//   - x963/ansit233k1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Sect233k1() elliptic.Curve {
	sect233k1Once.Do(initSect233k1)
	return sect233k1Curve
}

// Sect233r1 returns a Curve which implements secg/sect233r1
// https://neuromancer.sk/std/secg/
//
// OID: 1.3.132.0.27
// Aliases:
//   - nist/B-233
//   - wtls/wap-wsg-idm-ecid-wtls11
//   - x963/ansit233r1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Sect233r1() elliptic.Curve {
	sect233r1Once.Do(initSect233r1)
	return sect233r1Curve
}

// Sect239k1 returns a Curve which implements secg/sect239k1
// https://neuromancer.sk/std/secg/
//
// OID: 1.3.132.0.3
// Aliases:
//   - x963/ansit239k1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Sect239k1() elliptic.Curve {
	sect239k1Once.Do(initSect239k1)
	return sect239k1Curve
}

// Sect283k1 returns a Curve which implements secg/sect283k1
// https://neuromancer.sk/std/secg/
//
// OID: 1.3.132.0.16
// Aliases:
//   - nist/K-283
//   - x963/ansit283k1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Sect283k1() elliptic.Curve {
	sect283k1Once.Do(initSect283k1)
	return sect283k1Curve
}

// Sect283r1 returns a Curve which implements secg/sect283r1
// https://neuromancer.sk/std/secg/
//
// OID: 1.3.132.0.17
// Aliases:
//   - nist/B-283
//   - x963/ansit283r1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Sect283r1() elliptic.Curve {
	sect283r1Once.Do(initSect283r1)
	return sect283r1Curve
}

// Sect409k1 returns a Curve which implements secg/sect409k1
// https://neuromancer.sk/std/secg/
//
// OID: 1.3.132.0.36
// Aliases:
//   - nist/K-409
//   - x963/ansit409k1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Sect409k1() elliptic.Curve {
	sect409k1Once.Do(initSect409k1)
	return sect409k1Curve
}

// Sect409r1 returns a Curve which implements secg/sect409r1
// https://neuromancer.sk/std/secg/
//
// OID: 1.3.132.0.37
// Aliases:
//   - nist/B-409
//   - x963/ansit409r1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Sect409r1() elliptic.Curve {
	sect409r1Once.Do(initSect409r1)
	return sect409r1Curve
}

// Sect571k1 returns a Curve which implements secg/sect571k1
// https://neuromancer.sk/std/secg/
//
// OID: 1.3.132.0.38
// Aliases:
//   - nist/K-571
//   - x963/ansit571k1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Sect571k1() elliptic.Curve {
	sect571k1Once.Do(initSect571k1)
	return sect571k1Curve
}

// Sect571r1 returns a Curve which implements secg/sect571r1
// https://neuromancer.sk/std/secg/
//
// OID: 1.3.132.0.39
// Aliases:
//   - nist/B-571
//   - x963/ansit571r1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Sect571r1() elliptic.Curve {
	sect571r1Once.Do(initSect571r1)
	return sect571r1Curve
}
