// Code generated by curve_generator. DO NOT EDIT.

package secg

import (
	"crypto/elliptic"
	"sync"

	. "github.com/RyuaNerin/elliptic2/internal"
	. "github.com/RyuaNerin/elliptic2/internal/curve"
	wb "github.com/RyuaNerin/elliptic2/internal/curve/weierstrassbinary"
	wp "github.com/RyuaNerin/elliptic2/internal/curve/weierstrassprime"
	. "github.com/RyuaNerin/elliptic2/internal/field"
)

var (
	secp112r1Once sync.Once
	secp112r2Once sync.Once
	secp128r1Once sync.Once
	secp128r2Once sync.Once
	secp160k1Once sync.Once
	secp160r1Once sync.Once
	secp160r2Once sync.Once
	secp192k1Once sync.Once
	secp192r1Once sync.Once
	secp224k1Once sync.Once
	secp224r1Once sync.Once
	secp256k1Once sync.Once
	secp256r1Once sync.Once
	secp384r1Once sync.Once
	secp521r1Once sync.Once
	sect113r1Once sync.Once
	sect113r2Once sync.Once
	sect131r1Once sync.Once
	sect131r2Once sync.Once
	sect163k1Once sync.Once
	sect163r1Once sync.Once
	sect163r2Once sync.Once
	sect193r1Once sync.Once
	sect193r2Once sync.Once
	sect233k1Once sync.Once
	sect233r1Once sync.Once
	sect239k1Once sync.Once
	sect283k1Once sync.Once
	sect283r1Once sync.Once
	sect409k1Once sync.Once
	sect409r1Once sync.Once
	sect571k1Once sync.Once
	sect571r1Once sync.Once

	secp112r1Curve elliptic.Curve
	secp112r2Curve elliptic.Curve
	secp128r1Curve elliptic.Curve
	secp128r2Curve elliptic.Curve
	secp160k1Curve elliptic.Curve
	secp160r1Curve elliptic.Curve
	secp160r2Curve elliptic.Curve
	secp192k1Curve elliptic.Curve
	secp192r1Curve elliptic.Curve
	secp224k1Curve elliptic.Curve
	secp224r1Curve elliptic.Curve
	secp256k1Curve elliptic.Curve
	secp256r1Curve elliptic.Curve
	secp384r1Curve elliptic.Curve
	secp521r1Curve elliptic.Curve
	sect113r1Curve elliptic.Curve
	sect113r2Curve elliptic.Curve
	sect131r1Curve elliptic.Curve
	sect131r2Curve elliptic.Curve
	sect163k1Curve elliptic.Curve
	sect163r1Curve elliptic.Curve
	sect163r2Curve elliptic.Curve
	sect193r1Curve elliptic.Curve
	sect193r2Curve elliptic.Curve
	sect233k1Curve elliptic.Curve
	sect233r1Curve elliptic.Curve
	sect239k1Curve elliptic.Curve
	sect283k1Curve elliptic.Curve
	sect283r1Curve elliptic.Curve
	sect409k1Curve elliptic.Curve
	sect409r1Curve elliptic.Curve
	sect571k1Curve elliptic.Curve
	sect571r1Curve elliptic.Curve
)

// https://neuromancer.sk/std/secg/secp112r1
func initSecp112r1() {
	secp112r1Curve = NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `secp112r1`,
			BitSize: 112,
			P:       NewGFpModulusFromHex(`db7c2abf62e35e668076bead208b`),
			A:       ParseGFpHex(`db7c2abf62e35e668076bead2088`),
			B:       ParseGFpHex(`659ef8ba043916eede8911702b22`),
			N:       HI(`db7c2abf62e35e7628dfac6561c5`),
			Gx:      HI(`9487239995a5ee76b55f9c2f098`),
			Gy:      HI(`a89ce5af8724c0a23e0e0ff77500`),
		}),
		WithOID(`1.3.132.0.6`),
	)
}

// https://neuromancer.sk/std/secg/secp112r2
func initSecp112r2() {
	secp112r2Curve = NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `secp112r2`,
			BitSize: 112,
			P:       NewGFpModulusFromHex(`db7c2abf62e35e668076bead208b`),
			A:       ParseGFpHex(`6127c24c05f38a0aaaf65c0ef02c`),
			B:       ParseGFpHex(`51def1815db5ed74fcc34c85d709`),
			N:       HI(`36df0aafd8b8d7597ca10520d04b`),
			Gx:      HI(`4ba30ab5e892b4e1649dd0928643`),
			Gy:      HI(`adcd46f5882e3747def36e956e97`),
		}),
		WithOID(`1.3.132.0.7`),
	)
}

// https://neuromancer.sk/std/secg/secp128r1
func initSecp128r1() {
	secp128r1Curve = NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `secp128r1`,
			BitSize: 128,
			P:       NewGFpModulusFromHex(`fffffffdffffffffffffffffffffffff`),
			A:       ParseGFpHex(`fffffffdfffffffffffffffffffffffc`),
			B:       ParseGFpHex(`e87579c11079f43dd824993c2cee5ed3`),
			N:       HI(`fffffffe0000000075a30d1b9038a115`),
			Gx:      HI(`161ff7528b899b2d0c28607ca52c5b86`),
			Gy:      HI(`cf5ac8395bafeb13c02da292dded7a83`),
		}),
		WithOID(`1.3.132.0.28`),
	)
}

// https://neuromancer.sk/std/secg/secp128r2
func initSecp128r2() {
	secp128r2Curve = NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `secp128r2`,
			BitSize: 128,
			P:       NewGFpModulusFromHex(`fffffffdffffffffffffffffffffffff`),
			A:       ParseGFpHex(`d6031998d1b3bbfebf59cc9bbff9aee1`),
			B:       ParseGFpHex(`5eeefca380d02919dc2c6558bb6d8a5d`),
			N:       HI(`3fffffff7fffffffbe0024720613b5a3`),
			Gx:      HI(`7b6aa5d85e572983e6fb32a7cdebc140`),
			Gy:      HI(`27b6916a894d3aee7106fe805fc34b44`),
		}),
		WithOID(`1.3.132.0.29`),
	)
}

// https://neuromancer.sk/std/secg/secp160k1
func initSecp160k1() {
	secp160k1Curve = NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `secp160k1`,
			BitSize: 160,
			P:       NewGFpModulusFromHex(`fffffffffffffffffffffffffffffffeffffac73`),
			A:       ParseGFpHex(``),
			B:       ParseGFpHex(`7`),
			N:       HI(`100000000000000000001b8fa16dfab9aca16b6b3`),
			Gx:      HI(`3b4c382ce37aa192a4019e763036f4f5dd4d7ebb`),
			Gy:      HI(`938cf935318fdced6bc28286531733c3f03c4fee`),
		}),
		WithOID(`1.3.132.0.9`),
	)
}

// https://neuromancer.sk/std/secg/secp160r1
func initSecp160r1() {
	secp160r1Curve = NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `secp160r1`,
			BitSize: 160,
			P:       NewGFpModulusFromHex(`ffffffffffffffffffffffffffffffff7fffffff`),
			A:       ParseGFpHex(`ffffffffffffffffffffffffffffffff7ffffffc`),
			B:       ParseGFpHex(`1c97befc54bd7a8b65acf89f81d4d4adc565fa45`),
			N:       HI(`100000000000000000001f4c8f927aed3ca752257`),
			Gx:      HI(`4a96b5688ef573284664698968c38bb913cbfc82`),
			Gy:      HI(`23a628553168947d59dcc912042351377ac5fb32`),
		}),
		WithOID(`1.3.132.0.8`),
	)
}

// https://neuromancer.sk/std/secg/secp160r2
func initSecp160r2() {
	secp160r2Curve = NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `secp160r2`,
			BitSize: 160,
			P:       NewGFpModulusFromHex(`fffffffffffffffffffffffffffffffeffffac73`),
			A:       ParseGFpHex(`fffffffffffffffffffffffffffffffeffffac70`),
			B:       ParseGFpHex(`b4e134d3fb59eb8bab57274904664d5af50388ba`),
			N:       HI(`100000000000000000000351ee786a818f3a1a16b`),
			Gx:      HI(`52dcb034293a117e1f4ff11b30f7199d3144ce6d`),
			Gy:      HI(`feaffef2e331f296e071fa0df9982cfea7d43f2e`),
		}),
		WithOID(`1.3.132.0.30`),
	)
}

// https://neuromancer.sk/std/secg/secp192k1
func initSecp192k1() {
	secp192k1Curve = NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `secp192k1`,
			BitSize: 192,
			P:       NewGFpModulusFromHex(`fffffffffffffffffffffffffffffffffffffffeffffee37`),
			A:       ParseGFpHex(``),
			B:       ParseGFpHex(`3`),
			N:       HI(`fffffffffffffffffffffffe26f2fc170f69466a74defd8d`),
			Gx:      HI(`db4ff10ec057e9ae26b07d0280b7f4341da5d1b1eae06c7d`),
			Gy:      HI(`9b2f2f6d9c5628a7844163d015be86344082aa88d95e2f9d`),
		}),
		WithOID(`1.3.132.0.31`),
	)
}

// https://neuromancer.sk/std/secg/secp192r1
func initSecp192r1() {
	secp192r1Curve = NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `secp192r1`,
			BitSize: 192,
			P:       NewGFpModulusFromHex(`fffffffffffffffffffffffffffffffeffffffffffffffff`),
			A:       ParseGFpHex(`fffffffffffffffffffffffffffffffefffffffffffffffc`),
			B:       ParseGFpHex(`64210519e59c80e70fa7e9ab72243049feb8deecc146b9b1`),
			N:       HI(`ffffffffffffffffffffffff99def836146bc9b1b4d22831`),
			Gx:      HI(`188da80eb03090f67cbf20eb43a18800f4ff0afd82ff1012`),
			Gy:      HI(`7192b95ffc8da78631011ed6b24cdd573f977a11e794811`),
		}),
		WithOID(`1.2.840.10045.3.1.1`),
	)
}

// https://neuromancer.sk/std/secg/secp224k1
func initSecp224k1() {
	secp224k1Curve = NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `secp224k1`,
			BitSize: 224,
			P:       NewGFpModulusFromHex(`fffffffffffffffffffffffffffffffffffffffffffffffeffffe56d`),
			A:       ParseGFpHex(``),
			B:       ParseGFpHex(`5`),
			N:       HI(`10000000000000000000000000001dce8d2ec6184caf0a971769fb1f7`),
			Gx:      HI(`a1455b334df099df30fc28a169a467e9e47075a90f7e650eb6b7a45c`),
			Gy:      HI(`7e089fed7fba344282cafbd6f7e319f7c0b0bd59e2ca4bdb556d61a5`),
		}),
		WithOID(`1.3.132.0.32`),
	)
}

// https://neuromancer.sk/std/secg/secp224r1
func initSecp224r1() {
	secp224r1Curve = NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `secp224r1`,
			BitSize: 224,
			P:       NewGFpModulusFromHex(`ffffffffffffffffffffffffffffffff000000000000000000000001`),
			A:       ParseGFpHex(`fffffffffffffffffffffffffffffffefffffffffffffffffffffffe`),
			B:       ParseGFpHex(`b4050a850c04b3abf54132565044b0b7d7bfd8ba270b39432355ffb4`),
			N:       HI(`ffffffffffffffffffffffffffff16a2e0b8f03e13dd29455c5c2a3d`),
			Gx:      HI(`b70e0cbd6bb4bf7f321390b94a03c1d356c21122343280d6115c1d21`),
			Gy:      HI(`bd376388b5f723fb4c22dfe6cd4375a05a07476444d5819985007e34`),
		}),
		WithOID(`1.3.132.0.33`),
	)
}

// https://neuromancer.sk/std/secg/secp256k1
func initSecp256k1() {
	secp256k1Curve = NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `secp256k1`,
			BitSize: 256,
			P:       NewGFpModulusFromHex(`fffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffc2f`),
			A:       ParseGFpHex(``),
			B:       ParseGFpHex(`7`),
			N:       HI(`fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141`),
			Gx:      HI(`79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798`),
			Gy:      HI(`483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8`),
		}),
		WithOID(`1.3.132.0.10`),
	)
}

// https://neuromancer.sk/std/secg/secp256r1
func initSecp256r1() {
	secp256r1Curve = NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `secp256r1`,
			BitSize: 256,
			P:       NewGFpModulusFromHex(`ffffffff00000001000000000000000000000000ffffffffffffffffffffffff`),
			A:       ParseGFpHex(`ffffffff00000001000000000000000000000000fffffffffffffffffffffffc`),
			B:       ParseGFpHex(`5ac635d8aa3a93e7b3ebbd55769886bc651d06b0cc53b0f63bce3c3e27d2604b`),
			N:       HI(`ffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551`),
			Gx:      HI(`6b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c296`),
			Gy:      HI(`4fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5`),
		}),
		WithOID(`1.2.840.10045.3.1.7`),
	)
}

// https://neuromancer.sk/std/secg/secp384r1
func initSecp384r1() {
	secp384r1Curve = NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `secp384r1`,
			BitSize: 384,
			P:       NewGFpModulusFromHex(`fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeffffffff0000000000000000ffffffff`),
			A:       ParseGFpHex(`fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeffffffff0000000000000000fffffffc`),
			B:       ParseGFpHex(`b3312fa7e23ee7e4988e056be3f82d19181d9c6efe8141120314088f5013875ac656398d8a2ed19d2a85c8edd3ec2aef`),
			N:       HI(`ffffffffffffffffffffffffffffffffffffffffffffffffc7634d81f4372ddf581a0db248b0a77aecec196accc52973`),
			Gx:      HI(`aa87ca22be8b05378eb1c71ef320ad746e1d3b628ba79b9859f741e082542a385502f25dbf55296c3a545e3872760ab7`),
			Gy:      HI(`3617de4a96262c6f5d9e98bf9292dc29f8f41dbd289a147ce9da3113b5f0b8c00a60b1ce1d7e819d7a431d7c90ea0e5f`),
		}),
		WithOID(`1.3.132.0.34`),
	)
}

// https://neuromancer.sk/std/secg/secp521r1
func initSecp521r1() {
	secp521r1Curve = NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `secp521r1`,
			BitSize: 521,
			P:       NewGFpModulusFromHex(`1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff`),
			A:       ParseGFpHex(`1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc`),
			B:       ParseGFpHex(`51953eb9618e1c9a1f929a21a0b68540eea2da725b99b315f3b8b489918ef109e156193951ec7e937b1652c0bd3bb1bf073573df883d2c34f1ef451fd46b503f00`),
			N:       HI(`1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffa51868783bf2f966b7fcc0148f709a5d03bb5c9b8899c47aebb6fb71e91386409`),
			Gx:      HI(`c6858e06b70404e9cd9e3ecb662395b4429c648139053fb521f828af606b4d3dbaa14b5e77efe75928fe1dc127a2ffa8de3348b3c1856a429bf97e7e31c2e5bd66`),
			Gy:      HI(`11839296a789a3bc0045c8a5fb42c7d1bd998f54449579b446817afbd17273e662c97ee72995ef42640c550b9013fad0761353c7086a272c24088be94769fd16650`),
		}),
		WithOID(`1.3.132.0.35`),
	)
}

// https://neuromancer.sk/std/secg/sect113r1
func initSect113r1() {
	sect113r1Curve = NewCurve(
		wb.Build(&wb.CurveParams{
			Name:    `sect113r1`,
			BitSize: 113,
			Poly:    NewGF2mModulusFromPolynomials(113, 9, 0),
			A2:      ParseGF2mHex(`3088250ca6e7c7fe649ce85820f7`),
			A6:      ParseGF2mHex(`e8bee4d3e2260744188be0e9c723`),
			N:       HI(`100000000000000d9ccec8a39e56f`),
			Gx:      HI(`9d73616f35f4ab1407d73562c10f`),
			Gy:      HI(`a52830277958ee84d1315ed31886`),
		}),
		WithOID(`1.3.132.0.4`),
	)
}

// https://neuromancer.sk/std/secg/sect113r2
func initSect113r2() {
	sect113r2Curve = NewCurve(
		wb.Build(&wb.CurveParams{
			Name:    `sect113r2`,
			BitSize: 113,
			Poly:    NewGF2mModulusFromPolynomials(113, 9, 0),
			A2:      ParseGF2mHex(`689918dbec7e5a0dd6dfc0aa55c7`),
			A6:      ParseGF2mHex(`95e9a9ec9b297bd4bf36e059184f`),
			N:       HI(`10000000000000108789b2496af93`),
			Gx:      HI(`1a57a6a7b26ca5ef52fcdb8164797`),
			Gy:      HI(`b3adc94ed1fe674c06e695baba1d`),
		}),
		WithOID(`1.3.132.0.5`),
	)
}

// https://neuromancer.sk/std/secg/sect131r1
func initSect131r1() {
	sect131r1Curve = NewCurve(
		wb.Build(&wb.CurveParams{
			Name:    `sect131r1`,
			BitSize: 131,
			Poly:    NewGF2mModulusFromPolynomials(131, 8, 3, 2, 0),
			A2:      ParseGF2mHex(`7a11b09a76b562144418ff3ff8c2570b8`),
			A6:      ParseGF2mHex(`217c05610884b63b9c6c7291678f9d341`),
			N:       HI(`400000000000000023123953a9464b54d`),
			Gx:      HI(`81baf91fdf9833c40f9c181343638399`),
			Gy:      HI(`78c6e7ea38c001f73c8134b1b4ef9e150`),
		}),
		WithOID(`1.3.132.0.22`),
	)
}

// https://neuromancer.sk/std/secg/sect131r2
func initSect131r2() {
	sect131r2Curve = NewCurve(
		wb.Build(&wb.CurveParams{
			Name:    `sect131r2`,
			BitSize: 131,
			Poly:    NewGF2mModulusFromPolynomials(131, 8, 3, 2, 0),
			A2:      ParseGF2mHex(`3e5a88919d7cafcbf415f07c2176573b2`),
			A6:      ParseGF2mHex(`4b8266a46c55657ac734ce38f018f2192`),
			N:       HI(`400000000000000016954a233049ba98f`),
			Gx:      HI(`356dcd8f2f95031ad652d23951bb366a8`),
			Gy:      HI(`648f06d867940a5366d9e265de9eb240f`),
		}),
		WithOID(`1.3.132.0.23`),
	)
}

// https://neuromancer.sk/std/secg/sect163k1
func initSect163k1() {
	sect163k1Curve = NewCurve(
		wb.Build(&wb.CurveParams{
			Name:    `sect163k1`,
			BitSize: 163,
			Poly:    NewGF2mModulusFromPolynomials(163, 7, 6, 3, 0),
			A2:      ParseGF2mHex(`1`),
			A6:      ParseGF2mHex(`1`),
			N:       HI(`4000000000000000000020108a2e0cc0d99f8a5ef`),
			Gx:      HI(`2fe13c0537bbc11acaa07d793de4e6d5e5c94eee8`),
			Gy:      HI(`289070fb05d38ff58321f2e800536d538ccdaa3d9`),
		}),
		WithOID(`1.3.132.0.1`),
	)
}

// https://neuromancer.sk/std/secg/sect163r1
func initSect163r1() {
	sect163r1Curve = NewCurve(
		wb.Build(&wb.CurveParams{
			Name:    `sect163r1`,
			BitSize: 163,
			Poly:    NewGF2mModulusFromPolynomials(163, 7, 6, 3, 0),
			A2:      ParseGF2mHex(`7b6882caaefa84f9554ff8428bd88e246d2782ae2`),
			A6:      ParseGF2mHex(`713612dcddcb40aab946bda29ca91f73af958afd9`),
			N:       HI(`3ffffffffffffffffffff48aab689c29ca710279b`),
			Gx:      HI(`369979697ab43897789566789567f787a7876a654`),
			Gy:      HI(`435edb42efafb2989d51fefce3c80988f41ff883`),
		}),
		WithOID(`1.3.132.0.2`),
	)
}

// https://neuromancer.sk/std/secg/sect163r2
func initSect163r2() {
	sect163r2Curve = NewCurve(
		wb.Build(&wb.CurveParams{
			Name:    `sect163r2`,
			BitSize: 163,
			Poly:    NewGF2mModulusFromPolynomials(163, 7, 6, 3, 0),
			A2:      ParseGF2mHex(`1`),
			A6:      ParseGF2mHex(`20a601907b8c953ca1481eb10512f78744a3205fd`),
			N:       HI(`40000000000000000000292fe77e70c12a4234c33`),
			Gx:      HI(`3f0eba16286a2d57ea0991168d4994637e8343e36`),
			Gy:      HI(`d51fbc6c71a0094fa2cdd545b11c5c0c797324f1`),
		}),
		WithOID(`1.3.132.0.15`),
	)
}

// https://neuromancer.sk/std/secg/sect193r1
func initSect193r1() {
	sect193r1Curve = NewCurve(
		wb.Build(&wb.CurveParams{
			Name:    `sect193r1`,
			BitSize: 193,
			Poly:    NewGF2mModulusFromPolynomials(193, 15, 0),
			A2:      ParseGF2mHex(`17858feb7a98975169e171f77b4087de098ac8a911df7b01`),
			A6:      ParseGF2mHex(`fdfb49bfe6c3a89facadaa7a1e5bbc7cc1c2e5d831478814`),
			N:       HI(`1000000000000000000000000c7f34a778f443acc920eba49`),
			Gx:      HI(`1f481bc5f0ff84a74ad6cdf6fdef4bf6179625372d8c0c5e1`),
			Gy:      HI(`25e399f2903712ccf3ea9e3a1ad17fb0b3201b6af7ce1b05`),
		}),
		WithOID(`1.3.132.0.24`),
	)
}

// https://neuromancer.sk/std/secg/sect193r2
func initSect193r2() {
	sect193r2Curve = NewCurve(
		wb.Build(&wb.CurveParams{
			Name:    `sect193r2`,
			BitSize: 193,
			Poly:    NewGF2mModulusFromPolynomials(193, 15, 0),
			A2:      ParseGF2mHex(`163f35a5137c2ce3ea6ed8667190b0bc43ecd69977702709b`),
			A6:      ParseGF2mHex(`c9bb9e8927d4d64c377e2ab2856a5b16e3efb7f61d4316ae`),
			N:       HI(`10000000000000000000000015aab561b005413ccd4ee99d5`),
			Gx:      HI(`d9b67d192e0367c803f39e1a7e82ca14a651350aae617e8f`),
			Gy:      HI(`1ce94335607c304ac29e7defbd9ca01f596f927224cdecf6c`),
		}),
		WithOID(`1.3.132.0.25`),
	)
}

// https://neuromancer.sk/std/secg/sect233k1
func initSect233k1() {
	sect233k1Curve = NewCurve(
		wb.Build(&wb.CurveParams{
			Name:    `sect233k1`,
			BitSize: 233,
			Poly:    NewGF2mModulusFromPolynomials(233, 74, 0),
			A2:      ParseGF2mHex(``),
			A6:      ParseGF2mHex(`1`),
			N:       HI(`8000000000000000000000000000069d5bb915bcd46efb1ad5f173abdf`),
			Gx:      HI(`17232ba853a7e731af129f22ff4149563a419c26bf50a4c9d6eefad6126`),
			Gy:      HI(`1db537dece819b7f70f555a67c427a8cd9bf18aeb9b56e0c11056fae6a3`),
		}),
		WithOID(`1.3.132.0.26`),
	)
}

// https://neuromancer.sk/std/secg/sect233r1
func initSect233r1() {
	sect233r1Curve = NewCurve(
		wb.Build(&wb.CurveParams{
			Name:    `sect233r1`,
			BitSize: 233,
			Poly:    NewGF2mModulusFromPolynomials(233, 74, 0),
			A2:      ParseGF2mHex(`1`),
			A6:      ParseGF2mHex(`66647ede6c332c7f8c0923bb58213b333b20e9ce4281fe115f7d8f90ad`),
			N:       HI(`1000000000000000000000000000013e974e72f8a6922031d2603cfe0d7`),
			Gx:      HI(`fac9dfcbac8313bb2139f1bb755fef65bc391f8b36f8f8eb7371fd558b`),
			Gy:      HI(`1006a08a41903350678e58528bebf8a0beff867a7ca36716f7e01f81052`),
		}),
		WithOID(`1.3.132.0.27`),
	)
}

// https://neuromancer.sk/std/secg/sect239k1
func initSect239k1() {
	sect239k1Curve = NewCurve(
		wb.Build(&wb.CurveParams{
			Name:    `sect239k1`,
			BitSize: 239,
			Poly:    NewGF2mModulusFromPolynomials(239, 158, 0),
			A2:      ParseGF2mHex(``),
			A6:      ParseGF2mHex(`1`),
			N:       HI(`2000000000000000000000000000005a79fec67cb6e91f1c1da800e478a5`),
			Gx:      HI(`29a0b6a887a983e9730988a68727a8b2d126c44cc2cc7b2a6555193035dc`),
			Gy:      HI(`76310804f12e549bdb011c103089e73510acb275fc312a5dc6b76553f0ca`),
		}),
		WithOID(`1.3.132.0.3`),
	)
}

// https://neuromancer.sk/std/secg/sect283k1
func initSect283k1() {
	sect283k1Curve = NewCurve(
		wb.Build(&wb.CurveParams{
			Name:    `sect283k1`,
			BitSize: 283,
			Poly:    NewGF2mModulusFromPolynomials(283, 12, 7, 5, 0),
			A2:      ParseGF2mHex(``),
			A6:      ParseGF2mHex(`1`),
			N:       HI(`1ffffffffffffffffffffffffffffffffffe9ae2ed07577265dff7f94451e061e163c61`),
			Gx:      HI(`503213f78ca44883f1a3b8162f188e553cd265f23c1567a16876913b0c2ac2458492836`),
			Gy:      HI(`1ccda380f1c9e318d90f95d07e5426fe87e45c0e8184698e45962364e34116177dd2259`),
		}),
		WithOID(`1.3.132.0.16`),
	)
}

// https://neuromancer.sk/std/secg/sect283r1
func initSect283r1() {
	sect283r1Curve = NewCurve(
		wb.Build(&wb.CurveParams{
			Name:    `sect283r1`,
			BitSize: 283,
			Poly:    NewGF2mModulusFromPolynomials(283, 12, 7, 5, 0),
			A2:      ParseGF2mHex(`1`),
			A6:      ParseGF2mHex(`27b680ac8b8596da5a4af8a19a0303fca97fd7645309fa2a581485af6263e313b79a2f5`),
			N:       HI(`3ffffffffffffffffffffffffffffffffffef90399660fc938a90165b042a7cefadb307`),
			Gx:      HI(`5f939258db7dd90e1934f8c70b0dfec2eed25b8557eac9c80e2e198f8cdbecd86b12053`),
			Gy:      HI(`3676854fe24141cb98fe6d4b20d02b4516ff702350eddb0826779c813f0df45be8112f4`),
		}),
		WithOID(`1.3.132.0.17`),
	)
}

// https://neuromancer.sk/std/secg/sect409k1
func initSect409k1() {
	sect409k1Curve = NewCurve(
		wb.Build(&wb.CurveParams{
			Name:    `sect409k1`,
			BitSize: 409,
			Poly:    NewGF2mModulusFromPolynomials(409, 87, 0),
			A2:      ParseGF2mHex(``),
			A6:      ParseGF2mHex(`1`),
			N:       HI(`7ffffffffffffffffffffffffffffffffffffffffffffffffffe5f83b2d4ea20400ec4557d5ed3e3e7ca5b4b5c83b8e01e5fcf`),
			Gx:      HI(`60f05f658f49c1ad3ab1890f7184210efd0987e307c84c27accfb8f9f67cc2c460189eb5aaaa62ee222eb1b35540cfe9023746`),
			Gy:      HI(`1e369050b7c4e42acba1dacbf04299c3460782f918ea427e6325165e9ea10e3da5f6c42e9c55215aa9ca27a5863ec48d8e0286b`),
		}),
		WithOID(`1.3.132.0.36`),
	)
}

// https://neuromancer.sk/std/secg/sect409r1
func initSect409r1() {
	sect409r1Curve = NewCurve(
		wb.Build(&wb.CurveParams{
			Name:    `sect409r1`,
			BitSize: 409,
			Poly:    NewGF2mModulusFromPolynomials(409, 87, 0),
			A2:      ParseGF2mHex(`1`),
			A6:      ParseGF2mHex(`21a5c2c8ee9feb5c4b9a753b7b476b7fd6422ef1f3dd674761fa99d6ac27c8a9a197b272822f6cd57a55aa4f50ae317b13545f`),
			N:       HI(`10000000000000000000000000000000000000000000000000001e2aad6a612f33307be5fa47c3c9e052f838164cd37d9a21173`),
			Gx:      HI(`15d4860d088ddb3496b0c6064756260441cde4af1771d4db01ffe5b34e59703dc255a868a1180515603aeab60794e54bb7996a7`),
			Gy:      HI(`61b1cfab6be5f32bbfa78324ed106a7636b9c5a7bd198d0158aa4f5488d08f38514f1fdf4b4f40d2181b3681c364ba0273c706`),
		}),
		WithOID(`1.3.132.0.37`),
	)
}

// https://neuromancer.sk/std/secg/sect571k1
func initSect571k1() {
	sect571k1Curve = NewCurve(
		wb.Build(&wb.CurveParams{
			Name:    `sect571k1`,
			BitSize: 571,
			Poly:    NewGF2mModulusFromPolynomials(571, 10, 5, 2, 0),
			A2:      ParseGF2mHex(``),
			A6:      ParseGF2mHex(`1`),
			N:       HI(`20000000000000000000000000000000000000000000000000000000000000000000000131850e1f19a63e4b391a8db917f4138b630d84be5d639381e91deb45cfe778f637c1001`),
			Gx:      HI(`26eb7a859923fbc82189631f8103fe4ac9ca2970012d5d46024804801841ca44370958493b205e647da304db4ceb08cbbd1ba39494776fb988b47174dca88c7e2945283a01c8972`),
			Gy:      HI(`349dc807f4fbf374f4aeade3bca95314dd58cec9f307a54ffc61efc006d8a2c9d4979c0ac44aea74fbebbb9f772aedcb620b01a7ba7af1b320430c8591984f601cd4c143ef1c7a3`),
		}),
		WithOID(`1.3.132.0.38`),
	)
}

// https://neuromancer.sk/std/secg/sect571r1
func initSect571r1() {
	sect571r1Curve = NewCurve(
		wb.Build(&wb.CurveParams{
			Name:    `sect571r1`,
			BitSize: 571,
			Poly:    NewGF2mModulusFromPolynomials(571, 10, 5, 2, 0),
			A2:      ParseGF2mHex(`1`),
			A6:      ParseGF2mHex(`2f40e7e2221f295de297117b7f3d62f5c6a97ffcb8ceff1cd6ba8ce4a9a18ad84ffabbd8efa59332be7ad6756a66e294afd185a78ff12aa520e4de739baca0c7ffeff7f2955727a`),
			N:       HI(`3ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe661ce18ff55987308059b186823851ec7dd9ca1161de93d5174d66e8382e9bb2fe84e47`),
			Gx:      HI(`303001d34b856296c16c0d40d3cd7750a93d1d2955fa80aa5f40fc8db7b2abdbde53950f4c0d293cdd711a35b67fb1499ae60038614f1394abfa3b4c850d927e1e7769c8eec2d19`),
			Gy:      HI(`37bf27342da639b6dccfffeb73d69d78c6c27a6009cbbca1980f8533921e8a684423e43bab08a576291af8f461bb2a8b3531d2f0485c19b16e2f1516e23dd3c1a4827af1b8ac15b`),
		}),
		WithOID(`1.3.132.0.39`),
	)
}
