// Code generated by curve_generator. DO NOT EDIT.
package weierstrassprime

import (
	"github.com/RyuaNerin/elliptic2/internal/curve"
)

func (op *affineOp) add(dst, p1, p2 *curve.GFpCoordinate) {
	/**
	https://hyperelliptic.org/EFD/g1p/auto-shortw-affine.html#addition-add

	x3 = (y2-y1)**2/(x2-x1)**2-x1-x2
	y3 = (2*x1+x2)*(y2-y1)/(x2-x1)-(y2-y1)**3/(x2-x1)**3-y1

	| Operation                 | Expression
	|  1: dy = y2 - y1          | 1: dy = y2 - y1
	|  2: dx = x2 - x1          | 2: dx = x2 - x1
	|  3: _0 = dx**-1           |
	|  4: dyx = dy * _0         | 3: dyx = dy * dx**-1
	|  5: dyx2 = dyx**2         | 4: dyx2 = dyx**2
	|  6: x3 = dyx2 - x1        |
	|  7: x3 = x3 - x2          | 5: x3 = dyx2 - x1 - x2
	|  8: _1 = dyx2 * dyx       |
	|  9: y3 = 2 * x1           |
	| 10: y3 = y3 + x2          |
	| 11: y3 = y3 * dyx         |
	| 12: y3 = y3 - _1          |
	| 13: y3 = y3 - y1          | 6: y3 = (2 * x1 + x2) * dyx - dyx2 * dyx - y1
	*/

	x1, y1 := &p1[0], &p1[1]
	x2, y2 := &p2[0], &p2[1]
	x3, y3 := &dst[0], &dst[1]

	_0, _1 := &op.t[0], &op.t[1]

	x3.Sub(y2, y1)  // 1: dy = y2 - y1
	y3.Sub(x2, x1)  // 2: dx = x2 - x1
	_0.Inv(y3)      // 3: _0 = dx**-1
	_1.Mul(x3, _0)  // 4: dyx = dy * _0
	_1.ReduceSoft() //
	y3.Sqr(_1)      // 5: dyx2 = dyx**2
	y3.ReduceSoft() //
	x3.Sub(y3, x1)  // 6: x3 = dyx2 - x1
	x3.Sub(x3, x2)  // 7: x3 = x3 - x2
	x3.Reduce()     //
	_0.Mul(y3, _1)  // 8: _1 = dyx2 * dyx
	_0.ReduceSoft() //
	y3.Lsh(x1, 1)   // 9: y3 = 2 * x1
	y3.Add(y3, x2)  // 10: y3 = y3 + x2
	y3.Mul(y3, _1)  // 11: y3 = y3 * dyx
	y3.ReduceSoft() //
	y3.Sub(y3, _0)  // 12: y3 = y3 - _1
	y3.Sub(y3, y1)  // 13: y3 = y3 - y1
	y3.Reduce()     //
}
