// Code generated by curve_generator. DO NOT EDIT.
package weierstrassprime

import (
	"github.com/RyuaNerin/elliptic2/internal/curve"
)

func (op *affineOp) dbl(dst, p1 *curve.GFpCoordinate) {
	/**
	https://hyperelliptic.org/EFD/g1p/auto-shortw.html

	x3 = (3*x1**2+a)**2/(2*y1)**2-x1-x1
	y3 = (2*x1+x1)*(3*x12+a)/(2*y1)-(3*x12+a)**3/(2*y1)**3-y1

	| Operation                 | Expression
	|  1: _0 = x1**2            |
	|  2: n = 3 * _0            |
	|  3: n = n + a             | 1: n = 3 * x1**2 + a
	|  4: d = 2 * y1            | 2: d = 2 * y1
	|  5: _1 = d**-1            |
	|  6: nd = n * _1           | 3: nd = n * d**-1
	|  7: nd2 = nd**2           | 4: nd2 = nd**2
	|  8: _2 = 2 * x1           |
	|  9: x3 = nd2 - _2         | 5: x3 = nd2 - 2 * x1
	| 10: _3 = nd2 * nd         |
	| 11: y3 = 3 * x1           |
	| 12: y3 = y3 * nd          |
	| 13: y3 = y3 - _3          |
	| 14: y3 = y3 - y1          | 6: y3 = 3 * x1 * nd - nd2 * nd - y1
	*/

	a := op.A

	x1, y1 := &p1[0], &p1[1]
	x3, y3 := &dst[0], &dst[1]

	_0, _1 := &op.t[0], &op.t[1]

	x3.Sqr(x1)      // 1: _0 = x1**2
	x3.ReduceSoft() //
	y3.Lsh(x3, 1)   //
	y3.Add(y3, x3)  // 2: n = 3 * _0
	y3.Reduce()     //
	x3.Add(y3, a)   // 3: n = n + a
	y3.Lsh(y1, 1)   // 4: d = 2 * y1
	_0.Inv(y3)      // 5: _1 = d**-1
	_1.Mul(x3, _0)  // 6: nd = n * _1
	_1.ReduceSoft() //
	y3.Sqr(_1)      // 7: nd2 = nd**2
	y3.ReduceSoft() //
	_0.Lsh(x1, 1)   // 8: _2 = 2 * x1
	x3.Sub(y3, _0)  // 9: x3 = nd2 - _2
	x3.Reduce()     //
	_0.Mul(y3, _1)  // 10: _3 = nd2 * nd
	_0.ReduceSoft() //
	y3.Lsh(x1, 1)   //
	y3.Add(y3, x1)  // 11: y3 = 3 * x1
	y3.Mul(y3, _1)  // 12: y3 = y3 * nd
	y3.ReduceSoft() //
	y3.Sub(y3, _0)  // 13: y3 = y3 - _3
	y3.Sub(y3, y1)  // 14: y3 = y3 - y1
	y3.Reduce()     //
}
