// Code generated by curve_generator. DO NOT EDIT.
package weierstrassprime

import (
	"github.com/RyuaNerin/elliptic2/internal/curve"
)

// a4 = 0
func (op *jacobianOp) dbl2009l(dst, p1 *curve.GFpCoordinate) {
	/**
	https://hyperelliptic.org/EFD/g1p/auto-shortw-jacobian-0.html#doubling-dbl-2009-l

	The "dbl-2009-l" doubling formulas [database entry; Sage verification script; Sage output; three-operand code]:

	Cost: 2M + 5S + 6add + 3*2 + 1*3 + 1*8.
	Source: 2009.04.01 Lange.

	| Operation                 | Expression
	|  1: A = X1**2             | 1: A = X1**2
	|  2: B = Y1**2             | 2: B = Y1**2
	|  3: C = B**2              | 3: C = B**2
	|  4: _0 = X1 + B           |
	|  5: _0 = _0**2            |
	|  6: _0 = _0 - A           |
	|  7: _0 = _0 - C           |
	|  8: D = 2 * _0            | 4: D = 2 * ((X1 + B)**2 - A - C)
	|  9: E = 3 * A             | 5: E = 3 * A
	| 10: F = E**2              | 6: F = E**2
	| 11: _1 = 2 * D            |
	| 12: X3 = F - _1           | 7: X3 = F - 2 * D
	| 13: _2 = 8 * C            |
	| 14: _3 = D - X3           |
	| 15: Y3 = E * _3           |
	| 16: Y3 = Y3 - _2          | 8: Y3 = E * (D - X3) - 8 * C
	| 17: Z3 = 2 * Y1           |
	| 18: Z3 = Z3 * Z1          | 9: Z3 = 2 * Y1 * Z1
	*/

	X1, Y1, Z1 := &p1[0], &p1[1], &p1[2]
	X3, Y3, Z3 := &dst[0], &dst[1], &dst[2]

	_0, _1, _2 := &op.t[0], &op.t[1], &op.t[2]

	X3.Sqr(X1)      // 1: A = X1**2
	X3.ReduceSoft() //
	Y3.Sqr(Y1)      // 2: B = Y1**2
	Y3.ReduceSoft() //
	Z3.Sqr(Y3)      // 3: C = B**2
	Z3.ReduceSoft() //
	_0.Add(X1, Y3)  // 4: _0 = X1 + B
	Y3.Sqr(_0)      // 5: _0 = _0**2
	Y3.Reduce()     //
	_0.Sub(Y3, X3)  // 6: _0 = _0 - A
	Y3.Sub(_0, Z3)  // 7: _0 = _0 - C
	_0.Lsh(Y3, 1)   // 8: D = 2 * _0
	_1.Lsh(X3, 1)   //
	_1.Add(_1, X3)  // 9: E = 3 * A
	Y3.Sqr(_1)      // 10: F = E**2
	Y3.Reduce()     //
	_2.Lsh(_0, 1)   // 11: _1 = 2 * D
	X3.Sub(Y3, _2)  // 12: X3 = F - _1
	X3.Reduce()     //
	_2.Lsh(Z3, 3)   // 13: _2 = 8 * C
	Z3.Sub(_0, X3)  // 14: _3 = D - X3
	Y3.Mul(_1, Z3)  // 15: Y3 = E * _3
	Y3.ReduceSoft() //
	Y3.Sub(Y3, _2)  // 16: Y3 = Y3 - _2
	Y3.Reduce()     //
	Z3.Lsh(Y1, 1)   // 17: Z3 = 2 * Y1
	Z3.Mul(Z3, Z1)  // 18: Z3 = Z3 * Z1
	Z3.Reduce()     //
}
