// Code generated by curve_generator. DO NOT EDIT.
package weierstrassprime

import (
	"github.com/RyuaNerin/elliptic2/internal/curve"
)

func (op *jacobianOp) madd2007bl(dst, p1, p2 *curve.GFpCoordinate) {
	/**
	https://hyperelliptic.org/EFD/g1p/auto-shortw-jacobian.html#addition-madd-2007-bl

	The "madd-2007-bl" addition formulas [database entry; Sage verification script; Sage output; three-operand code]:

	Assumptions: Z2=1.
	Cost: 7M + 4S + 9add + 3*2 + 1*4.
	Source: 2007 Bernstein-Lange.

	| Operation                 | Expression
	|  1: Z1Z1 = Z1**2          | 1: Z1Z1 = Z1**2
	|  2: U2 = X2 * Z1Z1        | 2: U2 = X2 * Z1Z1
	|  3: S2 = Y2 * Z1          |
	|  4: S2 = S2 * Z1Z1        | 3: S2 = Y2 * Z1 * Z1Z1
	|  5: H = U2 - X1           | 4: H = U2 - X1
	|  6: HH = H**2             | 5: HH = H**2
	|  7: I = 4 * HH            | 6: I = 4 * HH
	|  8: J = H * I             | 7: J = H * I
	|  9: _0 = S2 - Y1          |
	| 10: r = 2 * _0            | 8: r = 2 * (S2 - Y1)
	| 11: V = X1 * I            | 9: V = X1 * I
	| 12: _1 = 2 * V            |
	| 13: X3 = r**2             |
	| 14: X3 = X3 - J           |
	| 15: X3 = X3 - _1          | 10: X3 = r**2 - J - 2 * V
	| 16: _2 = 2 * Y1           |
	| 17: _2 = _2 * J           |
	| 18: _3 = V - X3           |
	| 19: Y3 = r * _3           |
	| 20: Y3 = Y3 - _2          | 11: Y3 = r * (V - X3) - 2 * Y1 * J
	| 21: Z3 = Z1 + H           |
	| 22: Z3 = Z3**2            |
	| 23: Z3 = Z3 - Z1Z1        |
	| 24: Z3 = Z3 - HH          | 12: Z3 = (Z1 + H)**2 - Z1Z1 - HH
	*/

	X1, Y1, Z1 := &p1[0], &p1[1], &p1[2]
	X2, Y2 := &p2[0], &p2[1]
	X3, Y3, Z3 := &dst[0], &dst[1], &dst[2]

	_0, _1, _2 := &op.t[0], &op.t[1], &op.t[2]

	X3.Sqr(Z1)      // 1: Z1Z1 = Z1**2
	X3.ReduceSoft() //
	Y3.Mul(X2, X3)  // 2: U2 = X2 * Z1Z1
	Y3.Reduce()     //
	Z3.Mul(Y2, Z1)  // 3: S2 = Y2 * Z1
	Z3.ReduceSoft() //
	_0.Mul(Z3, X3)  // 4: S2 = S2 * Z1Z1
	_0.ReduceSoft() //
	_1.Sub(Y3, X1)  // 5: H = U2 - X1
	Y3.Sqr(_1)      // 6: HH = H**2
	Y3.ReduceSoft() //
	Z3.Add(Z1, _1)  // 21: Z3 = Z1 + H
	_2.Lsh(Y3, 2)   // 7: I = 4 * HH
	Z3.Sqr(Z3)      // 22: Z3 = Z3**2
	Z3.ReduceSoft() //
	Z3.Sub(Z3, X3)  // 23: Z3 = Z3 - Z1Z1
	X3.Sub(_0, Y1)  // 9: _0 = S2 - Y1
	Z3.Sub(Z3, Y3)  // 24: Z3 = Z3 - HH
	Z3.Reduce()     //
	_0.Mul(_1, _2)  // 8: J = H * I
	_0.ReduceSoft() //
	Y3.Mul(X1, _2)  // 11: V = X1 * I
	Y3.ReduceSoft() //
	_1.Lsh(X3, 1)   // 10: r = 2 * _0
	_2.Lsh(Y3, 1)   // 12: _1 = 2 * V
	X3.Sqr(_1)      // 13: X3 = r**2
	X3.ReduceSoft() //
	X3.Sub(X3, _0)  // 14: X3 = X3 - J
	X3.Sub(X3, _2)  // 15: X3 = X3 - _1
	X3.Reduce()     //
	_2.Sub(Y3, X3)  // 18: _3 = V - X3
	Y3.Mul(_1, _2)  // 19: Y3 = r * _3
	Y3.ReduceSoft() //
	_1.Lsh(Y1, 1)   // 16: _2 = 2 * Y1
	_2.Mul(_1, _0)  // 17: _2 = _2 * J
	_2.ReduceSoft() //
	Y3.Sub(Y3, _2)  // 20: Y3 = Y3 - _2
	Y3.Reduce()     //
}
