// Code generated by curve_generator. DO NOT EDIT.
package weierstrassprime

import (
	"github.com/RyuaNerin/elliptic2/internal/curve"
)

// a4 = -3
func (op *jacobianOp) dbl2001b(dst, p1 *curve.GFpCoordinate) {
	/**
	https://hyperelliptic.org/EFD/g1p/auto-shortw-jacobian-3.html#doubling-dbl-2001-b

	The "dbl-2001-b" doubling formulas [database entry; Sage verification script; Sage output; three-operand code]:

	Cost: 3M + 5S + 8add + 1*3 + 1*4 + 2*8.
	Source: 2001 Bernstein "A software implementation of NIST P-224".

	| Operation                 | Expression
	|  1: delta = Z1**2         | 1: delta = Z1**2
	|  2: gamma = Y1**2         | 2: gamma = Y1**2
	|  3: beta = X1 * gamma     | 3: beta = X1 * gamma
	|  4: _0 = X1 + delta       |
	|  5: _1 = X1 - delta       |
	|  6: alpha = 3 * _1        |
	|  7: alpha = alpha * _0    | 4: alpha = 3 * (X1 - delta) * (X1 + delta)
	|  8: _2 = 8 * beta         |
	|  9: X3 = alpha**2         |
	| 10: X3 = X3 - _2          | 5: X3 = alpha**2 - 8 * beta
	| 11: _4 = gamma**2         |
	| 12: _3 = 8 * _4           |
	| 13: _5 = 4 * beta         |
	| 14: _5 = _5 - X3          |
	| 15: Y3 = alpha * _5       |
	| 16: Y3 = Y3 - _3          | 6: Y3 = alpha * (4 * beta - X3) - 8 * gamma**2
	| 17: Z3 = Y1 + Z1          |
	| 18: Z3 = Z3**2            |
	| 19: Z3 = Z3 - gamma       |
	| 20: Z3 = Z3 - delta       | 7: Z3 = (Y1 + Z1)**2 - gamma - delta
	*/

	X1, Y1, Z1 := &p1[0], &p1[1], &p1[2]
	X3, Y3, Z3 := &dst[0], &dst[1], &dst[2]

	_0, _1, _2 := &op.t[0], &op.t[1], &op.t[2]

	Y3.Sqr(Z1)      // 1: delta = Z1**2
	Y3.Reduce()     //
	X3.Add(X1, Y3)  // 4: _0 = X1 + delta
	_0.Sub(X1, Y3)  // 5: _1 = X1 - delta
	Z3.Add(Y1, Z1)  // 17: Z3 = Y1 + Z1
	Z3.Sqr(Z3)      // 18: Z3 = Z3**2
	Z3.ReduceSoft() //
	_1.Sqr(Y1)      // 2: gamma = Y1**2
	_1.ReduceSoft() //
	_2.Lsh(_0, 1)   //
	_2.Add(_2, _0)  // 6: alpha = 3 * _1
	_0.Mul(_2, X3)  // 7: alpha = alpha * _0
	_0.ReduceSoft() //
	_2.Mul(X1, _1)  // 3: beta = X1 * gamma
	_2.ReduceSoft() //
	X3.Sqr(_1)      // 11: _4 = gamma**2
	X3.ReduceSoft() //
	Z3.Sub(Z3, _1)  // 19: Z3 = Z3 - gamma
	_1.Lsh(X3, 3)   // 12: _3 = 8 * _4
	X3.Sqr(_0)      // 9: X3 = alpha**2
	X3.ReduceSoft() //
	Z3.Sub(Z3, Y3)  // 20: Z3 = Z3 - delta
	Z3.Reduce()     //
	Y3.Lsh(_2, 3)   // 8: _2 = 8 * beta
	Y3.Reduce()     //
	X3.Sub(X3, Y3)  // 10: X3 = X3 - _2
	X3.Reduce()     //
	Y3.Lsh(_2, 2)   // 13: _5 = 4 * beta
	Y3.Reduce()     //
	_2.Sub(Y3, X3)  // 14: _5 = _5 - X3
	Y3.Mul(_0, _2)  // 15: Y3 = alpha * _5
	Y3.ReduceSoft() //
	Y3.Sub(Y3, _1)  // 16: Y3 = Y3 - _3
	Y3.Reduce()     //
}
