// Code generated by curve_generator. DO NOT EDIT.
package weierstrassprime

import (
	"github.com/RyuaNerin/elliptic2/internal/curve"
)

func (op *jacobianOp) add2007bl(dst, p1, p2 *curve.GFpCoordinate) {
	/**
	https://hyperelliptic.org/EFD/g1p/auto-shortw-jacobian.html#addition-add-2007-bl

	The "add-2007-bl" addition formulas [database entry; Sage verification script; Sage output; three-operand code]:

	Cost: 11M + 5S + 9add + 4*2.
	Cost: 10M + 4S + 9add + 4*2 dependent upon the first point.
	Source: 2007 Bernstein-Lange; note that the improvement from 12M+4S to 11M+5S was already mentioned in 2001 Bernstein http://cr.yp.to/talks.html#2001.10.29.

	| Operation                 | Expression
	|  1: Z1Z1 = Z1**2          | 1: Z1Z1 = Z1**2
	|  2: Z2Z2 = Z2**2          | 2: Z2Z2 = Z2**2
	|  3: U1 = X1 * Z2Z2        | 3: U1 = X1 * Z2Z2
	|  4: U2 = X2 * Z1Z1        | 4: U2 = X2 * Z1Z1
	|  5: S1 = Y1 * Z2          |
	|  6: S1 = S1 * Z2Z2        | 5: S1 = Y1 * Z2 * Z2Z2
	|  7: S2 = Y2 * Z1          |
	|  8: S2 = S2 * Z1Z1        | 6: S2 = Y2 * Z1 * Z1Z1
	|  9: H = U2 - U1           | 7: H = U2 - U1
	| 10: I = 2 * H             |
	| 11: I = I**2              | 8: I = (2 * H)**2
	| 12: J = H * I             | 9: J = H * I
	| 13: _0 = S2 - S1          |
	| 14: r = 2 * _0            | 10: r = 2 * (S2 - S1)
	| 15: V = U1 * I            | 11: V = U1 * I
	| 16: _1 = 2 * V            |
	| 17: X3 = r**2             |
	| 18: X3 = X3 - J           |
	| 19: X3 = X3 - _1          | 12: X3 = r**2 - J - 2 * V
	| 20: _2 = 2 * S1           |
	| 21: _2 = _2 * J           |
	| 22: _3 = V - X3           |
	| 23: Y3 = r * _3           |
	| 24: Y3 = Y3 - _2          | 13: Y3 = r * (V - X3) - 2 * S1 * J
	| 25: Z3 = Z1 + Z2          |
	| 26: Z3 = Z3**2            |
	| 27: Z3 = Z3 - Z1Z1        |
	| 28: Z3 = Z3 - Z2Z2        |
	| 29: Z3 = Z3 * H           | 14: Z3 = ((Z1 + Z2)**2 - Z1Z1 - Z2Z2) * H
	*/

	X1, Y1, Z1 := &p1[0], &p1[1], &p1[2]
	X2, Y2, Z2 := &p2[0], &p2[1], &p2[2]
	X3, Y3, Z3 := &dst[0], &dst[1], &dst[2]

	_0, _1, _2, _3 := &op.t[0], &op.t[1], &op.t[2], &op.t[3]

	X3.Sqr(Z1)      // 1: Z1Z1 = Z1**2
	X3.ReduceSoft() //
	Y3.Mul(X2, X3)  // 4: U2 = X2 * Z1Z1
	Y3.Reduce()     //
	_0.Mul(Y1, Z2)  // 5: S1 = Y1 * Z2
	_0.ReduceSoft() //
	Z3.Mul(Y2, Z1)  // 7: S2 = Y2 * Z1
	Z3.ReduceSoft() //
	_1.Mul(Z3, X3)  // 8: S2 = S2 * Z1Z1
	_1.ReduceSoft() //
	Z3.Add(Z1, Z2)  // 25: Z3 = Z1 + Z2
	_2.Sqr(Z2)      // 2: Z2Z2 = Z2**2
	_2.ReduceSoft() //
	Z3.Sqr(Z3)      // 26: Z3 = Z3**2
	Z3.ReduceSoft() //
	Z3.Sub(Z3, X3)  // 27: Z3 = Z3 - Z1Z1
	X3.Mul(X1, _2)  // 3: U1 = X1 * Z2Z2
	X3.ReduceSoft() //
	Z3.Sub(Z3, _2)  // 28: Z3 = Z3 - Z2Z2
	_3.Mul(_0, _2)  // 6: S1 = S1 * Z2Z2
	_3.ReduceSoft() //
	_0.Sub(Y3, X3)  // 9: H = U2 - U1
	Y3.Lsh(_0, 1)   // 10: I = 2 * H
	_2.Sqr(Y3)      // 11: I = I**2
	_2.ReduceSoft() //
	Y3.Mul(X3, _2)  // 15: V = U1 * I
	Y3.ReduceSoft() //
	X3.Sub(_1, _3)  // 13: _0 = S2 - S1
	_1.Mul(_0, _2)  // 12: J = H * I
	_1.ReduceSoft() //
	_2.Lsh(X3, 1)   // 14: r = 2 * _0
	X3.Lsh(_3, 1)   // 20: _2 = 2 * S1
	_3.Mul(X3, _1)  // 21: _2 = _2 * J
	_3.ReduceSoft() //
	X3.Sqr(_2)      // 17: X3 = r**2
	X3.ReduceSoft() //
	X3.Sub(X3, _1)  // 18: X3 = X3 - J
	_1.Lsh(Y3, 1)   // 16: _1 = 2 * V
	X3.Sub(X3, _1)  // 19: X3 = X3 - _1
	X3.Reduce()     //
	_1.Sub(Y3, X3)  // 22: _3 = V - X3
	Y3.Mul(_2, _1)  // 23: Y3 = r * _3
	Y3.ReduceSoft() //
	Y3.Sub(Y3, _3)  // 24: Y3 = Y3 - _2
	Y3.Reduce()     //
	Z3.Mul(Z3, _0)  // 29: Z3 = Z3 * H
	Z3.Reduce()     //
}
