//go:build amd64 || arm64 || ppc64 || ppc64le || mips64 || mips64le || riscv64 || s390x || loong64

// Code generated by reduce_generator.py. DO NOT EDIT.

package gf2mreduce

import "math/big"

func init() {
	funcMap[0x134db6dd] = Reduce113_113_9_0
	funcMap[0xdf1248e8] = Reduce163_163_7_6_3_0
	funcMap[0x03943b0d] = Reduce163_163_8_2_1_0
	funcMap[0xd30917df] = Reduce191_191_9_0
	funcMap[0x88ad7e7b] = Reduce193_193_15_0
	funcMap[0xae49fdbe] = Reduce233_233_74_0
	funcMap[0x5d47ccca] = Reduce239_239_36_0
	funcMap[0x99e1e559] = Reduce283_283_12_7_5_0
	funcMap[0x94e14618] = Reduce409_409_87_0
	funcMap[0x002486f5] = Reduce571_571_10_5_2_0

	reduces = [][]int{
		{113, 9, 0},
		{163, 7, 6, 3, 0},
		{163, 8, 2, 1, 0},
		{191, 9, 0},
		{193, 15, 0},
		{233, 74, 0},
		{239, 36, 0},
		{283, 12, 7, 5, 0},
		{409, 87, 0},
		{571, 10, 5, 2, 0},
	}
}

// GF(2^113) fast reduction
// f(x) = x^113 + x^9 + 1
// Type: trinomial
// n = 2 words, m_word_idx = 1, m_bit_idx = 49
func Reduce113_113_9_0(result []big.Word, prod []big.Word) {
	_ = result[1]
	_ = prod[3]
	clear(result[2:])

	r0 := prod[0]
	r1 := prod[1]
	r2 := prod[2]
	r3 := prod[3]

	// r3 reduction (bits 192-255), baseShift = 79
	r1 ^= (r3 << 24) ^ (r3 << 15)
	r2 ^= (r3 >> 40) ^ (r3 >> 49)

	// r2 reduction (bits 128-191), baseShift = 15
	r0 ^= (r2 << 24) ^ (r2 << 15)
	r1 ^= (r2 >> 40) ^ (r2 >> 49)

	// r1 upper bits (bits 113-127)
	t := r1 >> 49
	r0 ^= (t << 9) ^ t
	r1 &= 0x1FFFFFFFFFFFF

	result[0] = r0
	result[1] = r1
}

// GF(2^163) fast reduction
// f(x) = x^163 + x^7 + x^6 + x^3 + 1
// Type: pentanomial
// n = 3 words, m_word_idx = 2, m_bit_idx = 35
func Reduce163_163_7_6_3_0(result []big.Word, prod []big.Word) {
	_ = result[2]
	_ = prod[5]
	clear(result[3:])

	r0 := prod[0]
	r1 := prod[1]
	r2 := prod[2]
	r3 := prod[3]
	r4 := prod[4]
	r5 := prod[5]

	// r5 reduction (bits 320-383), baseShift = 157
	r2 ^= (r5 << 36) ^ (r5 << 35) ^ (r5 << 32) ^ (r5 << 29)
	r3 ^= (r5 >> 28) ^ (r5 >> 29) ^ (r5 >> 32) ^ (r5 >> 35)

	// r4 reduction (bits 256-319), baseShift = 93
	r1 ^= (r4 << 36) ^ (r4 << 35) ^ (r4 << 32) ^ (r4 << 29)
	r2 ^= (r4 >> 28) ^ (r4 >> 29) ^ (r4 >> 32) ^ (r4 >> 35)

	// r3 reduction (bits 192-255), baseShift = 29
	r0 ^= (r3 << 36) ^ (r3 << 35) ^ (r3 << 32) ^ (r3 << 29)
	r1 ^= (r3 >> 28) ^ (r3 >> 29) ^ (r3 >> 32) ^ (r3 >> 35)

	// r2 upper bits (bits 163-191)
	t := r2 >> 35
	r0 ^= (t << 7) ^ (t << 6) ^ (t << 3) ^ t
	r2 &= 0x7FFFFFFFF

	result[0] = r0
	result[1] = r1
	result[2] = r2
}

// GF(2^163) fast reduction
// f(x) = x^163 + x^8 + x^2 + x^1 + 1
// Type: pentanomial
// n = 3 words, m_word_idx = 2, m_bit_idx = 35
func Reduce163_163_8_2_1_0(result []big.Word, prod []big.Word) {
	_ = result[2]
	_ = prod[5]
	clear(result[3:])

	r0 := prod[0]
	r1 := prod[1]
	r2 := prod[2]
	r3 := prod[3]
	r4 := prod[4]
	r5 := prod[5]

	// r5 reduction (bits 320-383), baseShift = 157
	r2 ^= (r5 << 37) ^ (r5 << 31) ^ (r5 << 30) ^ (r5 << 29)
	r3 ^= (r5 >> 27) ^ (r5 >> 33) ^ (r5 >> 34) ^ (r5 >> 35)

	// r4 reduction (bits 256-319), baseShift = 93
	r1 ^= (r4 << 37) ^ (r4 << 31) ^ (r4 << 30) ^ (r4 << 29)
	r2 ^= (r4 >> 27) ^ (r4 >> 33) ^ (r4 >> 34) ^ (r4 >> 35)

	// r3 reduction (bits 192-255), baseShift = 29
	r0 ^= (r3 << 37) ^ (r3 << 31) ^ (r3 << 30) ^ (r3 << 29)
	r1 ^= (r3 >> 27) ^ (r3 >> 33) ^ (r3 >> 34) ^ (r3 >> 35)

	// r2 upper bits (bits 163-191)
	t := r2 >> 35
	r0 ^= (t << 8) ^ (t << 2) ^ (t << 1) ^ t
	r2 &= 0x7FFFFFFFF

	result[0] = r0
	result[1] = r1
	result[2] = r2
}

// GF(2^191) fast reduction
// f(x) = x^191 + x^9 + 1
// Type: trinomial
// n = 3 words, m_word_idx = 2, m_bit_idx = 63
func Reduce191_191_9_0(result []big.Word, prod []big.Word) {
	_ = result[2]
	_ = prod[5]
	clear(result[3:])

	r0 := prod[0]
	r1 := prod[1]
	r2 := prod[2]
	r3 := prod[3]
	r4 := prod[4]
	r5 := prod[5]

	// r5 reduction (bits 320-383), baseShift = 129
	r2 ^= (r5 << 10) ^ (r5 << 1)
	r3 ^= (r5 >> 54) ^ (r5 >> 63)

	// r4 reduction (bits 256-319), baseShift = 65
	r1 ^= (r4 << 10) ^ (r4 << 1)
	r2 ^= (r4 >> 54) ^ (r4 >> 63)

	// r3 reduction (bits 192-255), baseShift = 1
	r0 ^= (r3 << 10) ^ (r3 << 1)
	r1 ^= (r3 >> 54) ^ (r3 >> 63)

	// r2 upper bits (bits 191-191)
	t := r2 >> 63
	r0 ^= (t << 9) ^ t
	r2 &= 0x7FFFFFFFFFFFFFFF

	result[0] = r0
	result[1] = r1
	result[2] = r2
}

// GF(2^193) fast reduction
// f(x) = x^193 + x^15 + 1
// Type: trinomial
// n = 4 words, m_word_idx = 3, m_bit_idx = 1
func Reduce193_193_15_0(result []big.Word, prod []big.Word) {
	_ = result[3]
	_ = prod[7]
	clear(result[4:])

	r0 := prod[0]
	r1 := prod[1]
	r2 := prod[2]
	r3 := prod[3]
	r4 := prod[4]
	r5 := prod[5]
	r6 := prod[6]
	r7 := prod[7]

	// r7 reduction (bits 448-511), baseShift = 255
	r3 ^= (r7 << 63)
	r4 ^= (r7 << 14) ^ (r7 >> 1)
	r5 ^= (r7 >> 50)

	// r6 reduction (bits 384-447), baseShift = 191
	r2 ^= (r6 << 63)
	r3 ^= (r6 << 14) ^ (r6 >> 1)
	r4 ^= (r6 >> 50)

	// r5 reduction (bits 320-383), baseShift = 127
	r1 ^= (r5 << 63)
	r2 ^= (r5 << 14) ^ (r5 >> 1)
	r3 ^= (r5 >> 50)

	// r4 reduction (bits 256-319), baseShift = 63
	r0 ^= (r4 << 63)
	r1 ^= (r4 << 14) ^ (r4 >> 1)
	r2 ^= (r4 >> 50)

	// r3 upper bits (bits 193-255)
	t := r3 >> 1
	r0 ^= (t << 15) ^ t
	r1 ^= (t >> 49)
	r3 &= 0x1

	result[0] = r0
	result[1] = r1
	result[2] = r2
	result[3] = r3
}

// GF(2^233) fast reduction
// f(x) = x^233 + x^74 + 1
// Type: trinomial
// n = 4 words, m_word_idx = 3, m_bit_idx = 41
func Reduce233_233_74_0(result []big.Word, prod []big.Word) {
	_ = result[3]
	_ = prod[7]
	clear(result[4:])

	r0 := prod[0]
	r1 := prod[1]
	r2 := prod[2]
	r3 := prod[3]
	r4 := prod[4]
	r5 := prod[5]
	r6 := prod[6]
	r7 := prod[7]

	// r7 reduction (bits 448-511), baseShift = 215
	r3 ^= (r7 << 23)
	r4 ^= (r7 << 33) ^ (r7 >> 41)
	r5 ^= (r7 >> 31)

	// r6 reduction (bits 384-447), baseShift = 151
	r2 ^= (r6 << 23)
	r3 ^= (r6 << 33) ^ (r6 >> 41)
	r4 ^= (r6 >> 31)

	// r5 reduction (bits 320-383), baseShift = 87
	r1 ^= (r5 << 23)
	r2 ^= (r5 << 33) ^ (r5 >> 41)
	r3 ^= (r5 >> 31)

	// r4 reduction (bits 256-319), baseShift = 23
	r0 ^= (r4 << 23)
	r1 ^= (r4 << 33) ^ (r4 >> 41)
	r2 ^= (r4 >> 31)

	// r3 upper bits (bits 233-255)
	t := r3 >> 41
	r0 ^= t
	r1 ^= (t << 10)
	r3 &= 0x1FFFFFFFFFF

	result[0] = r0
	result[1] = r1
	result[2] = r2
	result[3] = r3
}

// GF(2^239) fast reduction
// f(x) = x^239 + x^36 + 1
// Type: trinomial
// n = 4 words, m_word_idx = 3, m_bit_idx = 47
func Reduce239_239_36_0(result []big.Word, prod []big.Word) {
	_ = result[3]
	_ = prod[7]
	clear(result[4:])

	r0 := prod[0]
	r1 := prod[1]
	r2 := prod[2]
	r3 := prod[3]
	r4 := prod[4]
	r5 := prod[5]
	r6 := prod[6]
	r7 := prod[7]

	// r7 reduction (bits 448-511), baseShift = 209
	r3 ^= (r7 << 53) ^ (r7 << 17)
	r4 ^= (r7 >> 11) ^ (r7 >> 47)

	// r6 reduction (bits 384-447), baseShift = 145
	r2 ^= (r6 << 53) ^ (r6 << 17)
	r3 ^= (r6 >> 11) ^ (r6 >> 47)

	// r5 reduction (bits 320-383), baseShift = 81
	r1 ^= (r5 << 53) ^ (r5 << 17)
	r2 ^= (r5 >> 11) ^ (r5 >> 47)

	// r4 reduction (bits 256-319), baseShift = 17
	r0 ^= (r4 << 53) ^ (r4 << 17)
	r1 ^= (r4 >> 11) ^ (r4 >> 47)

	// r3 upper bits (bits 239-255)
	t := r3 >> 47
	r0 ^= (t << 36) ^ t
	r3 &= 0x7FFFFFFFFFFF

	result[0] = r0
	result[1] = r1
	result[2] = r2
	result[3] = r3
}

// GF(2^283) fast reduction
// f(x) = x^283 + x^12 + x^7 + x^5 + 1
// Type: pentanomial
// n = 5 words, m_word_idx = 4, m_bit_idx = 27
func Reduce283_283_12_7_5_0(result []big.Word, prod []big.Word) {
	_ = result[4]
	_ = prod[9]
	clear(result[5:])

	r0 := prod[0]
	r1 := prod[1]
	r2 := prod[2]
	r3 := prod[3]
	r4 := prod[4]
	r5 := prod[5]
	r6 := prod[6]
	r7 := prod[7]
	r8 := prod[8]
	r9 := prod[9]

	// r9 reduction (bits 576-639), baseShift = 293
	r4 ^= (r9 << 49) ^ (r9 << 44) ^ (r9 << 42) ^ (r9 << 37)
	r5 ^= (r9 >> 15) ^ (r9 >> 20) ^ (r9 >> 22) ^ (r9 >> 27)

	// r8 reduction (bits 512-575), baseShift = 229
	r3 ^= (r8 << 49) ^ (r8 << 44) ^ (r8 << 42) ^ (r8 << 37)
	r4 ^= (r8 >> 15) ^ (r8 >> 20) ^ (r8 >> 22) ^ (r8 >> 27)

	// r7 reduction (bits 448-511), baseShift = 165
	r2 ^= (r7 << 49) ^ (r7 << 44) ^ (r7 << 42) ^ (r7 << 37)
	r3 ^= (r7 >> 15) ^ (r7 >> 20) ^ (r7 >> 22) ^ (r7 >> 27)

	// r6 reduction (bits 384-447), baseShift = 101
	r1 ^= (r6 << 49) ^ (r6 << 44) ^ (r6 << 42) ^ (r6 << 37)
	r2 ^= (r6 >> 15) ^ (r6 >> 20) ^ (r6 >> 22) ^ (r6 >> 27)

	// r5 reduction (bits 320-383), baseShift = 37
	r0 ^= (r5 << 49) ^ (r5 << 44) ^ (r5 << 42) ^ (r5 << 37)
	r1 ^= (r5 >> 15) ^ (r5 >> 20) ^ (r5 >> 22) ^ (r5 >> 27)

	// r4 upper bits (bits 283-319)
	t := r4 >> 27
	r0 ^= (t << 12) ^ (t << 7) ^ (t << 5) ^ t
	r4 &= 0x7FFFFFF

	result[0] = r0
	result[1] = r1
	result[2] = r2
	result[3] = r3
	result[4] = r4
}

// GF(2^409) fast reduction
// f(x) = x^409 + x^87 + 1
// Type: trinomial
// n = 7 words, m_word_idx = 6, m_bit_idx = 25
func Reduce409_409_87_0(result []big.Word, prod []big.Word) {
	_ = result[6]
	_ = prod[13]
	clear(result[7:])

	r0 := prod[0]
	r1 := prod[1]
	r2 := prod[2]
	r3 := prod[3]
	r4 := prod[4]
	r5 := prod[5]
	r6 := prod[6]
	r7 := prod[7]
	r8 := prod[8]
	r9 := prod[9]
	r10 := prod[10]
	r11 := prod[11]
	r12 := prod[12]
	r13 := prod[13]

	// r13 reduction (bits 832-895), baseShift = 423
	r6 ^= (r13 << 39)
	r7 ^= (r13 << 62) ^ (r13 >> 25)
	r8 ^= (r13 >> 2)

	// r12 reduction (bits 768-831), baseShift = 359
	r5 ^= (r12 << 39)
	r6 ^= (r12 << 62) ^ (r12 >> 25)
	r7 ^= (r12 >> 2)

	// r11 reduction (bits 704-767), baseShift = 295
	r4 ^= (r11 << 39)
	r5 ^= (r11 << 62) ^ (r11 >> 25)
	r6 ^= (r11 >> 2)

	// r10 reduction (bits 640-703), baseShift = 231
	r3 ^= (r10 << 39)
	r4 ^= (r10 << 62) ^ (r10 >> 25)
	r5 ^= (r10 >> 2)

	// r9 reduction (bits 576-639), baseShift = 167
	r2 ^= (r9 << 39)
	r3 ^= (r9 << 62) ^ (r9 >> 25)
	r4 ^= (r9 >> 2)

	// r8 reduction (bits 512-575), baseShift = 103
	r1 ^= (r8 << 39)
	r2 ^= (r8 << 62) ^ (r8 >> 25)
	r3 ^= (r8 >> 2)

	// r7 reduction (bits 448-511), baseShift = 39
	r0 ^= (r7 << 39)
	r1 ^= (r7 << 62) ^ (r7 >> 25)
	r2 ^= (r7 >> 2)

	// r6 upper bits (bits 409-447)
	t := r6 >> 25
	r0 ^= t
	r1 ^= (t << 23)
	r6 &= 0x1FFFFFF

	result[0] = r0
	result[1] = r1
	result[2] = r2
	result[3] = r3
	result[4] = r4
	result[5] = r5
	result[6] = r6
}

// GF(2^571) fast reduction
// f(x) = x^571 + x^10 + x^5 + x^2 + 1
// Type: pentanomial
// n = 9 words, m_word_idx = 8, m_bit_idx = 59
func Reduce571_571_10_5_2_0(result []big.Word, prod []big.Word) {
	_ = result[8]
	_ = prod[17]
	clear(result[9:])

	r0 := prod[0]
	r1 := prod[1]
	r2 := prod[2]
	r3 := prod[3]
	r4 := prod[4]
	r5 := prod[5]
	r6 := prod[6]
	r7 := prod[7]
	r8 := prod[8]
	r9 := prod[9]
	r10 := prod[10]
	r11 := prod[11]
	r12 := prod[12]
	r13 := prod[13]
	r14 := prod[14]
	r15 := prod[15]
	r16 := prod[16]
	r17 := prod[17]

	// r17 reduction (bits 1088-1151), baseShift = 517
	r8 ^= (r17 << 15) ^ (r17 << 10) ^ (r17 << 7) ^ (r17 << 5)
	r9 ^= (r17 >> 49) ^ (r17 >> 54) ^ (r17 >> 57) ^ (r17 >> 59)

	// r16 reduction (bits 1024-1087), baseShift = 453
	r7 ^= (r16 << 15) ^ (r16 << 10) ^ (r16 << 7) ^ (r16 << 5)
	r8 ^= (r16 >> 49) ^ (r16 >> 54) ^ (r16 >> 57) ^ (r16 >> 59)

	// r15 reduction (bits 960-1023), baseShift = 389
	r6 ^= (r15 << 15) ^ (r15 << 10) ^ (r15 << 7) ^ (r15 << 5)
	r7 ^= (r15 >> 49) ^ (r15 >> 54) ^ (r15 >> 57) ^ (r15 >> 59)

	// r14 reduction (bits 896-959), baseShift = 325
	r5 ^= (r14 << 15) ^ (r14 << 10) ^ (r14 << 7) ^ (r14 << 5)
	r6 ^= (r14 >> 49) ^ (r14 >> 54) ^ (r14 >> 57) ^ (r14 >> 59)

	// r13 reduction (bits 832-895), baseShift = 261
	r4 ^= (r13 << 15) ^ (r13 << 10) ^ (r13 << 7) ^ (r13 << 5)
	r5 ^= (r13 >> 49) ^ (r13 >> 54) ^ (r13 >> 57) ^ (r13 >> 59)

	// r12 reduction (bits 768-831), baseShift = 197
	r3 ^= (r12 << 15) ^ (r12 << 10) ^ (r12 << 7) ^ (r12 << 5)
	r4 ^= (r12 >> 49) ^ (r12 >> 54) ^ (r12 >> 57) ^ (r12 >> 59)

	// r11 reduction (bits 704-767), baseShift = 133
	r2 ^= (r11 << 15) ^ (r11 << 10) ^ (r11 << 7) ^ (r11 << 5)
	r3 ^= (r11 >> 49) ^ (r11 >> 54) ^ (r11 >> 57) ^ (r11 >> 59)

	// r10 reduction (bits 640-703), baseShift = 69
	r1 ^= (r10 << 15) ^ (r10 << 10) ^ (r10 << 7) ^ (r10 << 5)
	r2 ^= (r10 >> 49) ^ (r10 >> 54) ^ (r10 >> 57) ^ (r10 >> 59)

	// r9 reduction (bits 576-639), baseShift = 5
	r0 ^= (r9 << 15) ^ (r9 << 10) ^ (r9 << 7) ^ (r9 << 5)
	r1 ^= (r9 >> 49) ^ (r9 >> 54) ^ (r9 >> 57) ^ (r9 >> 59)

	// r8 upper bits (bits 571-575)
	t := r8 >> 59
	r0 ^= (t << 10) ^ (t << 5) ^ (t << 2) ^ t
	r8 &= 0x7FFFFFFFFFFFFFF

	result[0] = r0
	result[1] = r1
	result[2] = r2
	result[3] = r3
	result[4] = r4
	result[5] = r5
	result[6] = r6
	result[7] = r7
	result[8] = r8
}
