// Code generated by curve_generator. DO NOT EDIT.
package weierstrassbinary

import (
	"github.com/RyuaNerin/elliptic2/internal/curve"
)

func (op *affineOp) dbl(dst, p1 *curve.GF2mCoordinate) {
	/**
	https://hyperelliptic.org/EFD/g12o/auto-shortw-affine.html#doubling-dbl

	The "dbl" doubling formulas [database entry; Sage verification script; Sage output; three-operand code]:

	Cost: 1I + 2M + 1S + 6add.
	Explicit formulas:
	lambda = X1+Y1/X1
	X3 = lambda2+lambda+a2
	Y3 = lambda*(X1+X3)+X3+Y1

	| Operation                 | Expression
	|  1: _1 = X1**-1           |
	|  2: _0 = Y1 * _1          |
	|  3: Lambda = X1 + _0      | 1: Lambda = X1 + Y1 * X1**-1
	|  4: X3 = Lambda**2        |
	|  5: X3 = X3 + Lambda      |
	|  6: X3 = X3 + a2          | 2: X3 = Lambda**2 + Lambda + a2
	|  7: _2 = X1 + X3          |
	|  8: Y3 = Lambda * _2      |
	|  9: Y3 = Y3 + X3          |
	| 10: Y3 = Y3 + Y1          | 3: Y3 = Lambda * (X1 + X3) + X3 + Y1
	*/

	a2 := op.A2

	X1, Y1 := &p1[0], &p1[1]
	X3, Y3 := &dst[0], &dst[1]

	_0, _1 := &op.t[0], &op.t[1]

	X3.Inv(X1)     // 1: _1 = X1**-1
	Y3.Mul(Y1, X3) // 2: _0 = Y1 * _1
	_0.Add(X1, Y3) // 3: Lambda = X1 + _0
	X3.Sqr(_0)     // 4: X3 = Lambda**2
	X3.Add(X3, _0) // 5: X3 = X3 + Lambda
	X3.Add(X3, a2) // 6: X3 = X3 + a2
	_1.Add(X1, X3) // 7: _2 = X1 + X3
	Y3.Mul(_0, _1) // 8: Y3 = Lambda * _2
	Y3.Add(Y3, X3) // 9: Y3 = Y3 + X3
	Y3.Add(Y3, Y1) // 10: Y3 = Y3 + Y1
}
