// Code generated by curve_generator. DO NOT EDIT.
package weierstrassbinary

import (
	"github.com/RyuaNerin/elliptic2/internal/curve"
)

func (op *jacobianOp) dbl2005dl(dst, p1 *curve.GF2mCoordinate) {
	/**
	ttps://hyperelliptic.org/EFD/g12o/auto-shortw-jacobian.html#doubling-dbl-2005-dl

	The "mdbl-2008-bl" doubling formulas [database entry; Sage verification script; Sage output; three-operand code]:

	Assumptions: Z1=1.
	Cost: 1M + 2S + 1*a6 + 5add.
	Source: 2008 Bernstein-Lange.

	| Operation                 | Expression
	|  1: A = X1**2             | 1: A = X1**2
	|  2: B = A**2              | 2: B = A**2
	|  3: C = Z1**2             | 3: C = Z1**2
	|  4: D = C**2              | 4: D = C**2
	|  5: _1 = D**2             |
	|  6: _0 = a6 * _1          |
	|  7: X3 = B + _0           | 5: X3 = B + a6 * D**2
	|  8: Z3 = X1 * C           | 6: Z3 = X1 * C
	|  9: _3 = Y1 * Z1          |
	| 10: _2 = A + _3           |
	| 11: _2 = _2 + Z3          |
	| 12: _2 = _2 * X3          |
	| 13: Y3 = B * Z3           |
	| 14: Y3 = Y3 + _2          | 7: Y3 = B * Z3 + (A + Y1 * Z1 + Z3) * X3
	*/

	a6 := op.A6

	X1, Y1, Z1 := &p1[0], &p1[1], &p1[2]
	X3, Y3, Z3 := &dst[0], &dst[1], &dst[2]

	_0, _1 := &op.t[0], &op.t[1]

	X3.Sqr(X1)     // 1: A = X1**2
	Y3.Sqr(Z1)     // 3: C = Z1**2
	Z3.Sqr(Y3)     // 4: D = C**2
	_0.Sqr(Z3)     // 5: _1 = D**2
	_1.Mul(Y1, Z1) // 9: _3 = Y1 * Z1
	Z3.Mul(X1, Y3) // 8: Z3 = X1 * C
	Y3.Mul(a6, _0) // 6: _0 = a6 * _1
	_0.Add(X3, _1) // 10: _2 = A + _3
	_1.Sqr(X3)     // 2: B = A**2
	X3.Add(_1, Y3) // 7: X3 = B + _0
	Y3.Add(_0, Z3) // 11: _2 = _2 + Z3
	_0.Mul(Y3, X3) // 12: _2 = _2 * X3
	Y3.Mul(_1, Z3) // 13: Y3 = B * Z3
	Y3.Add(Y3, _0) // 14: Y3 = Y3 + _2
}
