// Code generated by curve_generator. DO NOT EDIT.
package weierstrassbinary

import (
	"github.com/RyuaNerin/elliptic2/internal/curve"
)

func (op *jacobianOp) add2005dl(dst, p1, p2 *curve.GF2mCoordinate) {
	/**
	https://hyperelliptic.org/EFD/g12o/auto-shortw-jacobian.html#addition-add-2005-dl

	The "add-2005-dl" addition formulas [database entry; Sage verification script; Sage output; three-operand code]:

	Cost: 14M + 5S + 1*a2 + 7add.
	Cost: 13M + 4S + 1*a2 + 7add dependent upon the first point.
	Source: 2005 Doche-Lange.

	| Operation                 | Expression
	|  1: O1 = Z1**2            | 1: O1 = Z1**2
	|  2: O2 = Z2**2            | 2: O2 = Z2**2
	|  3: A = X1 * O2           | 3: A = X1 * O2
	|  4: B = X2 * O1           | 4: B = X2 * O1
	|  5: E = A + B             | 5: E = A + B
	|  6: G = E * Z1            | 6: G = E * Z1
	|  7: Z3 = G * Z2           | 7: Z3 = G * Z2
	|  8: C = Y1 * O2           |
	|  9: C = C * Z2            | 8: C = Y1 * O2 * Z2
	| 10: D = Y2 * O1           |
	| 11: D = D * Z1            | 9: D = Y2 * O1 * Z1
	| 12: F = C + D             | 10: F = C + D
	| 13: I = F + Z3            | 11: I = F + Z3
	| 14: _1 = E**2             |
	| 15: _0 = E * _1           |
	| 16: _2 = F * I            |
	| 17: _3 = Z3**2            |
	| 18: X3 = a2 * _3          |
	| 19: X3 = X3 + _2          |
	| 20: X3 = X3 + _0          | 12: X3 = a2 * Z3**2 + F * I + E * E**2
	| 21: _4 = G * Y2           |
	| 22: H = F * X2            |
	| 23: H = H + _4            | 13: H = F * X2 + G * Y2
	| 24: _5 = G**2             |
	| 25: _5 = _5 * H           |
	| 26: Y3 = I * X3           |
	| 27: Y3 = Y3 + _5          | 14: Y3 = I * X3 + G**2 * H
	*/

	a2 := op.A2

	X1, Y1, Z1 := &p1[0], &p1[1], &p1[2]
	X2, Y2, Z2 := &p2[0], &p2[1], &p2[2]
	X3, Y3, Z3 := &dst[0], &dst[1], &dst[2]

	_0, _1, _2, _3 := &op.t[0], &op.t[1], &op.t[2], &op.t[3]

	X3.Sqr(Z1)     // 1: O1 = Z1**2
	Y3.Mul(X2, X3) // 4: B = X2 * O1
	Z3.Sqr(Z2)     // 2: O2 = Z2**2
	_0.Mul(X1, Z3) // 3: A = X1 * O2
	_1.Add(_0, Y3) // 5: E = A + B
	Y3.Mul(_1, Z1) // 6: G = E * Z1
	_0.Mul(Y1, Z3) // 8: C = Y1 * O2
	_2.Mul(_0, Z2) // 9: C = C * Z2
	Z3.Mul(Y3, Z2) // 7: Z3 = G * Z2
	_0.Sqr(Z3)     // 17: _3 = Z3**2
	_3.Mul(Y2, X3) // 10: D = Y2 * O1
	X3.Mul(_3, Z1) // 11: D = D * Z1
	_3.Add(_2, X3) // 12: F = C + D
	_2.Sqr(_1)     // 14: _1 = E**2
	X3.Mul(a2, _0) // 18: X3 = a2 * _3
	_0.Mul(_1, _2) // 15: _0 = E * _1
	_1.Add(_3, Z3) // 13: I = F + Z3
	_2.Mul(_3, _1) // 16: _2 = F * I
	X3.Add(X3, _2) // 19: X3 = X3 + _2
	_2.Mul(_3, X2) // 22: H = F * X2
	_3.Mul(Y3, Y2) // 21: _4 = G * Y2
	X3.Add(X3, _0) // 20: X3 = X3 + _0
	_0.Sqr(Y3)     // 24: _5 = G**2
	Y3.Mul(_1, X3) // 26: Y3 = I * X3
	_1.Add(_2, _3) // 23: H = H + _4
	_2.Mul(_0, _1) // 25: _5 = _5 * H
	Y3.Add(Y3, _2) // 27: Y3 = Y3 + _5
}
