// Code generated by curve_generator. DO NOT EDIT.
package weierstrassbinary

import (
	"github.com/RyuaNerin/elliptic2/internal/curve"
)

func (op *jacobianOp) madd2008bl(dst, p1, p2 *curve.GF2mCoordinate) {
	/**
	https://hyperelliptic.org/EFD/g12o/auto-shortw-jacobian.html#addition-madd-2008-bl

	The "madd-2008-bl" addition formulas [database entry; Sage verification script; Sage output; three-operand code]:

	Assumptions: Z2=1.
	Cost: 10M + 3S + 1*a2 + 7add.
	Source: 2005 Doche-Lange.

	| Operation                 | Expression
	|  1: O1 = Z1**2            | 1: O1 = Z1**2
	|  2: B = X2 * O1           | 2: B = X2 * O1
	|  3: E = X1 + B            | 3: E = X1 + B
	|  4: Z3 = E * Z1           | 4: Z3 = E * Z1
	|  5: D = Y2 * O1           |
	|  6: D = D * Z1            | 5: D = Y2 * O1 * Z1
	|  7: F = Y1 + D            | 6: F = Y1 + D
	|  8: I = F + Z3            | 7: I = F + Z3
	|  9: G = Z3**2             | 8: G = Z3**2
	| 10: _1 = E**2             |
	| 11: _0 = E * _1           |
	| 12: _2 = F * I            |
	| 13: X3 = a2 * G           |
	| 14: X3 = X3 + _2          |
	| 15: X3 = X3 + _0          | 9: X3 = a2 * G + F * I + E * E**2
	| 16: _3 = Z3 * Y2          |
	| 17: H = F * X2            |
	| 18: H = H + _3            | 10: H = F * X2 + Z3 * Y2
	| 19: _4 = G * H            |
	| 20: Y3 = I * X3           |
	| 21: Y3 = Y3 + _4          | 11: Y3 = I * X3 + G * H
	*/

	a2 := op.A2

	X1, Y1, Z1 := &p1[0], &p1[1], &p1[2]
	X2, Y2 := &p2[0], &p2[1]
	X3, Y3, Z3 := &dst[0], &dst[1], &dst[2]

	_0, _1, _2, _3 := &op.t[0], &op.t[1], &op.t[2], &op.t[3]

	X3.Sqr(Z1)     // 1: O1 = Z1**2
	Y3.Mul(X2, X3) // 2: B = X2 * O1
	_0.Add(X1, Y3) // 3: E = X1 + B
	Z3.Mul(_0, Z1) // 4: Z3 = E * Z1
	Y3.Mul(Y2, X3) // 5: D = Y2 * O1
	X3.Mul(Y3, Z1) // 6: D = D * Z1
	Y3.Add(Y1, X3) // 7: F = Y1 + D
	_1.Add(Y3, Z3) // 8: I = F + Z3
	_2.Sqr(Z3)     // 9: G = Z3**2
	X3.Sqr(_0)     // 10: _1 = E**2
	_3.Mul(_0, X3) // 11: _0 = E * _1
	_0.Mul(Y3, _1) // 12: _2 = F * I
	X3.Mul(a2, _2) // 13: X3 = a2 * G
	X3.Add(X3, _0) // 14: X3 = X3 + _2
	X3.Add(X3, _3) // 15: X3 = X3 + _0
	_0.Mul(Z3, Y2) // 16: _3 = Z3 * Y2
	_3.Mul(Y3, X2) // 17: H = F * X2
	Y3.Add(_3, _0) // 18: H = H + _3
	_0.Mul(_2, Y3) // 19: _4 = G * H
	Y3.Mul(_1, X3) // 20: Y3 = I * X3
	Y3.Add(Y3, _0) // 21: Y3 = Y3 + _4
}
