// Code generated by curve_generator. DO NOT EDIT.
package weierstrassbinary

import (
	"github.com/RyuaNerin/elliptic2/internal/curve"
)

func (op *lambdaOp) dbl2013olar(dst, p1 *curve.GF2mCoordinate) {
	/**
	https://hyperelliptic.org/EFD/g12o/auto-shortw-lambda.html#doubling-dbl-2013-olar

	The "dbl-2013-olar" doubling formulas [database entry; Sage verification script; Sage output; three-operand code]:

	Cost: 4M + 4S + 1*a2 + 5add.
	Source: 2013 Oliveira-López-Aranha-Rodríguez-Henríquez "Lambda coordinates for binary elliptic curves"; database entry contributed by Chitchanok Chuengsatiansup.

	| Operation                 | Expression
	|  1: A = Z1**2             | 1: A = Z1**2
	|  2: B = L1**2             | 2: B = L1**2
	|  3: C = L1 * Z1           | 3: C = L1 * Z1
	|  4: D = a2 * A            | 4: D = a2 * A
	|  5: E = B + C             |
	|  6: E = E + D             | 5: E = B + C + D
	|  7: X3 = E**2             | 6: X3 = E**2
	|  8: Z3 = E * A            | 7: Z3 = E * A
	|  9: F = X1 * Z1           | 8: F = X1 * Z1
	| 10: _0 = E * C            |
	| 11: L3 = F**2             |
	| 12: L3 = L3 + X3          |
	| 13: L3 = L3 + _0          |
	| 14: L3 = L3 + Z3          | 9: L3 = F**2 + X3 + E * C + Z3
	*/

	a2 := op.A2

	X1, L1, Z1 := &p1[0], &p1[1], &p1[2]
	X3, L3, Z3 := &dst[0], &dst[1], &dst[2]

	_0, _1 := &op.t[0], &op.t[1]

	L3.Mul(L1, Z1) // 3: C = L1 * Z1
	X3.Sqr(L1)     // 2: B = L1**2
	Z3.Add(X3, L3) // 5: E = B + C
	_0.Sqr(Z1)     // 1: A = Z1**2
	X3.Mul(a2, _0) // 4: D = a2 * A
	_1.Add(Z3, X3) // 6: E = E + D
	X3.Sqr(_1)     // 7: X3 = E**2
	Z3.Mul(_1, _0) // 8: Z3 = E * A
	_0.Mul(_1, L3) // 10: _0 = E * C
	_1.Mul(X1, Z1) // 9: F = X1 * Z1
	L3.Sqr(_1)     // 11: L3 = F**2
	L3.Add(L3, X3) // 12: L3 = L3 + X3
	L3.Add(L3, _0) // 13: L3 = L3 + _0
	L3.Add(L3, Z3) // 14: L3 = L3 + Z3
}
