// Code generated by curve_generator. DO NOT EDIT.
package weierstrassbinary

import (
	"github.com/RyuaNerin/elliptic2/internal/curve"
)

func (op *lambdaOp) add2013olar(dst, p1, p2 *curve.GF2mCoordinate) {
	/**
	https://hyperelliptic.org/EFD/g12o/auto-shortw-lambda.html#addition-add-2013-olar

	The "add-2013-olar" addition formulas [database entry; Sage verification script; Sage output; three-operand code]:

	Cost: 11M + 2S + 5add.
	Source: 2013 Oliveira-López-Aranha-Rodríguez-Henríquez "Lambda coordinates for binary elliptic curves"; database entry contributed by Chitchanok Chuengsatiansup.

	| Operation                 | Expression
	|  1: A = L1 * Z2           | 1: A = L1 * Z2
	|  2: B = L2 * Z1           | 2: B = L2 * Z1
	|  3: C = A + B             | 3: C = A + B
	|  4: D = X1 * Z2           | 4: D = X1 * Z2
	|  5: E = X2 * Z1           | 5: E = X2 * Z1
	|  6: F = D + E             | 6: F = D + E
	|  7: G = F**2              | 7: G = F**2
	|  8: I = C * E             | 8: I = C * E
	|  9: J = C * G             | 9: J = C * G
	| 10: K = J * Z2            | 10: K = J * Z2
	| 11: _1 = L1 + Z1          |
	| 12: _0 = K * _1           |
	| 13: L3 = I + G            |
	| 14: L3 = L3**2            |
	| 15: L3 = L3 + _0          | 11: L3 = (I + G)**2 + K * (L1 + Z1)
	| 16: H = C * D             | 12: H = C * D
	| 17: X3 = H * I            | 13: X3 = H * I
	| 18: Z3 = K * Z1           | 14: Z3 = K * Z1
	*/

	X1, L1, Z1 := &p1[0], &p1[1], &p1[2]
	X2, L2, Z2 := &p2[0], &p2[1], &p2[2]
	X3, L3, Z3 := &dst[0], &dst[1], &dst[2]

	_0, _1 := &op.t[0], &op.t[1]

	X3.Mul(L1, Z2) // 1: A = L1 * Z2
	L3.Mul(X1, Z2) // 4: D = X1 * Z2
	Z3.Mul(L2, Z1) // 2: B = L2 * Z1
	_0.Add(X3, Z3) // 3: C = A + B
	X3.Mul(X2, Z1) // 5: E = X2 * Z1
	Z3.Add(L3, X3) // 6: F = D + E
	_1.Mul(_0, X3) // 8: I = C * E
	X3.Sqr(Z3)     // 7: G = F**2
	Z3.Mul(_0, L3) // 16: H = C * D
	L3.Mul(_0, X3) // 9: J = C * G
	_0.Mul(L3, Z2) // 10: K = J * Z2
	L3.Add(_1, X3) // 13: L3 = I + G
	X3.Mul(Z3, _1) // 17: X3 = H * I
	Z3.Add(L1, Z1) // 11: _1 = L1 + Z1
	_1.Mul(_0, Z3) // 12: _0 = K * _1
	Z3.Mul(_0, Z1) // 18: Z3 = K * Z1
	L3.Sqr(L3)     // 14: L3 = L3**2
	L3.Add(L3, _1) // 15: L3 = L3 + _0
}
