// Code generated by curve_generator. DO NOT EDIT.

package curves

import (
	"crypto/elliptic"
	"sync"

	. "github.com/RyuaNerin/elliptic2/internal"
	. "github.com/RyuaNerin/elliptic2/internal/curve"
	wp "github.com/RyuaNerin/elliptic2/internal/curve/weierstrassprime"
	"github.com/RyuaNerin/elliptic2/internal/curves/oids"
	. "github.com/RyuaNerin/elliptic2/internal/field"
)

var anssiFRP256v1 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `FRP256v1`,
			BitSize: 256,
			P:       NewGFpModulusFromHex(`f1fd178c0b3ad58f10126de8ce42435b3961adbcabc8ca6de8fcf353d86e9c03`),
			A:       ParseGFpHex(`f1fd178c0b3ad58f10126de8ce42435b3961adbcabc8ca6de8fcf353d86e9c00`),
			B:       ParseGFpHex(`ee353fca5428a9300d4aba754a44c00fdfec0c9ae4b1a1803075ed967b7bb73f`),
			N:       HI(`f1fd178c0b3ad58f10126de8ce42435b53dc67e140d2bf941ffdd459c6d655e1`),
			Gx:      HI(`b6b3d4c356c139eb31183d4749d423958c27d2dcaf98b70164c97a2dd98f5cff`),
			Gy:      HI(`6142e0f7c8b204911f9271f0f3ecef8c2701c307e8e4c9e183115a1554062cfb`),
		}),
		WithOIDRaw(oids.OIDAnssiFRP256v1),
	)
})

// AnssiFRP256v1 returns the predefined anssi/FRP256v1 curve.
func AnssiFRP256v1() elliptic.Curve { return anssiFRP256v1() }
