// Code generated by curve_generator. DO NOT EDIT.

package curves

import (
	"crypto/elliptic"
	"sync"

	. "github.com/RyuaNerin/elliptic2/internal"
	. "github.com/RyuaNerin/elliptic2/internal/curve"
	t "github.com/RyuaNerin/elliptic2/internal/curve/twistededwards"
	wp "github.com/RyuaNerin/elliptic2/internal/curve/weierstrassprime"
	. "github.com/RyuaNerin/elliptic2/internal/field"
)

var blsBLS12_377 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `BLS12-377`,
			BitSize: 377,
			P:       NewGFpModulusFromHex(`1ae3a4617c510eac63b05c06ca1493b1a22d9f300f5138f1ef3622fba094800170b5d44300000008508c00000000001`),
			A:       ParseGFpHex(``),
			B:       ParseGFpHex(`1`),
			N:       HI(`12ab655e9a2ca55660b44d1e5c37b00159aa76fed00000010a11800000000001`),
			Gx:      HI(`8848defe740a67c8fc6225bf87ff5485951e2caa9d41bb188282c8bd37cb5cd5481512ffcd394eeab9b16eb21be9ef`),
			Gy:      HI(`1914a69c5102eff1f674f5d30afeec4bd7fb348ca3e52d96d182ad44fb82305c2fe3d3634a9591afd82de55559c8ea6`),
		}),
	)
})

// BlsBLS12_377 returns the predefined bls/BLS12-377 curve.
func BlsBLS12_377() elliptic.Curve { return blsBLS12_377() }

var blsBLS12_381 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `BLS12-381`,
			BitSize: 381,
			P:       NewGFpModulusFromHex(`1a0111ea397fe69a4b1ba7b6434bacd764774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffaaab`),
			A:       ParseGFpHex(``),
			B:       ParseGFpHex(`4`),
			N:       HI(`73eda753299d7d483339d80809a1d80553bda402fffe5bfeffffffff00000001`),
			Gx:      HI(`17f1d3a73197d7942695638c4fa9ac0fc3688c4f9774b905a14e3a3f171bac586c55e83ff97a1aeffb3af00adb22c6bb`),
			Gy:      HI(`8b3f481e3aaa0f1a09e30ed741d8ae4fcf5e095d5d00af600db18cb2c04b3edd03cc744a2888ae40caa232946c5e7e1`),
		}),
	)
})

// BlsBLS12_381 returns the predefined bls/BLS12-381 curve.
func BlsBLS12_381() elliptic.Curve { return blsBLS12_381() }

var blsBLS12_446 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `BLS12-446`,
			BitSize: 446,
			P:       NewGFpModulusFromHex(`3cdee0fb28c5e535200fc34965aad6400095a4b78a02fe320f75a64bbac71602824e6dc3e23acdee56ee4528c573b5cc311c0026aab0aaab`),
			A:       ParseGFpHex(``),
			B:       ParseGFpHex(`1`),
			N:       HI(`511b70539f27995b34995830fa4d04c98ccc4c050bc7bb9b0e8d8ca34610428001400040001`),
			Gx:      HI(`297792b2d03de39d64faca6d49fcf7a8850144ca24fc5d815c082a3aa87d1a16929e56228c136123ba51421ae89cacd5b4789a38ce39035a`),
			Gy:      HI(`dc40ddcbab2823a7870b5c688aa04fee40369d913e4f2f0947a152fe1c27a79b7f787e9c35b869c3846fac4f12a70d0fe22d2e244268cc`),
		}),
	)
})

// BlsBLS12_446 returns the predefined bls/BLS12-446 curve.
func BlsBLS12_446() elliptic.Curve { return blsBLS12_446() }

var blsBLS12_455 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `BLS12-455`,
			BitSize: 455,
			P:       NewGFpModulusFromHex(`55555955557955572aa00e0f95b49203003f665e3a5b1d56234bd93954fcb314b8b3db9994ace86d1ba6c589556b2aa956aaa00001800002ab`),
			A:       ParseGFpHex(``),
			B:       ParseGFpHex(`a`),
			N:       HI(`10000080000380002e0000f10004f00025e000750001d1000a00000400001c00007ffffc00001`),
			Gx:      HI(`3018df4c2336d178e6ea61540353aba01923e3890b3295848906dfc90e0c43008e4751ffc913dc1ff3df33d11db57bada7a9297195acfb2fa`),
			Gy:      HI(`19a8a9c4c3ac2ffb4c6b380d17b8282e029615052eaa6416c16c8f36f251d87c272657f0702cc58c4e072628d7bad3c0e9b3a8aebfc6b2357c`),
		}),
	)
})

// BlsBLS12_455 returns the predefined bls/BLS12-455 curve.
func BlsBLS12_455() elliptic.Curve { return blsBLS12_455() }

var blsBLS12_638 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `BLS12-638`,
			BitSize: 638,
			P:       NewGFpModulusFromHex(`3cb868653d300b3fe80015554dd25db0fc01dcde95d4000000631bbd421715013955555555529c005c75d6c2ab00000000000ac79600d2abaaaaaaaaaaaaaa93eaf3ff000aaaaaaaaaaaaaaabeab000b`),
			A:       ParseGFpHex(``),
			B:       ParseGFpHex(`4`),
			N:       HI(`50f94035ff4000fffffffffff9406bfdc0040000000000000035fb801dffbfffffffffffffff401bff80000000000000000000ffc01`),
			Gx:      HI(`160f63a3a3b297f113075ed79466138e85b025f7fe724b78e32d7afc4d734bdd54f871092b8d1966d491c0f45a48a8bba5586095dffcc1410b7e26ed16baf98c1117959134c24a17a7be31e1afbf844f`),
			Gy:      HI(`2d340b33877480a9785e86ed2edcafc170b82568cb21b708b79fc6da3748461fcd80697e486695f3cae76fcb1781e784f6812f57be05dfc850426650ded8b40a464b00a35718228ec8e02b52b59d876e`),
		}),
	)
})

// BlsBLS12_638 returns the predefined bls/BLS12-638 curve.
func BlsBLS12_638() elliptic.Curve { return blsBLS12_638() }

var blsBLS24_477 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `BLS24-477`,
			BitSize: 477,
			P:       NewGFpModulusFromHex(`167278fac63bd5b007ebb8f693a2ab3dbd9f92cf437c399d928e94bfe9a04a009fda9e8cf9226901de62aea9dcea48bf1a0ebbf8860a5e7ad000152b`),
			A:       ParseGFpHex(``),
			B:       ParseGFpHex(`4`),
			N:       HI(`57f52ee445cc41781fcd53d13e45f6acdfe4f9f2a3cd414e71238afc9fcfc7d38caef64f4ff79f90013ffffff0000001`),
			Gx:      HI(`15dfd8e4893a408a34b600532b51cc86cab3af07103cfcf3ec7b9af836904cfb60ab0fa8ac91ee6255e5ef6286fa0c24df9d76ea50599c2e103e40ad`),
			Gy:      HI(`a683957a59b1b488fa657e11b44815056bde33c09d6aad392d299f89c7841b91a683bf01b7e70547e48e0fbe1ca9e991983131470f886ba9b6fce2e`),
		}),
	)
})

// BlsBLS24_477 returns the predefined bls/BLS24-477 curve.
func BlsBLS24_477() elliptic.Curve { return blsBLS24_477() }

var blsBLS48_581G1 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `BLS48-581-G1`,
			BitSize: 581,
			P:       NewGFpModulusFromHex(`1280f73ff3476f313824e31d47012a0056e84f8d122131bb3be6c0f1f3975444a48ae43af6e082acd9cd30394f4736daf68367a5513170ee0a578fdf721a4a48ac3edc154e6565912b`),
			A:       ParseGFpHex(``),
			B:       ParseGFpHex(`1`),
			N:       HI(`2386f8a925e2885e233a9ccc1615c0d6c635387a3f0b3cbe003fad6bc972c2e6e741969d34c4c92016a85c7cd0562303c4ccbe599467c24da118a5fe6fcd671c01`),
			Gx:      HI(`2af59b7ac340f2baf2b73df1e93f860de3f257e0e86868cf61abdbaedffb9f7544550546a9df6f9645847665d859236ebdbc57db368b11786cb74da5d3a1e6d8c3bce8732315af640`),
			Gy:      HI(`cefda44f6531f91f86b3a2d1fb398a488a553c9efeb8a52e991279dd41b720ef7bb7beffb98aee53e80f678584c3ef22f487f77c2876d1b2e35f37aef7b926b576dbb5de3e2587a70`),
		}),
	)
})

// BlsBLS48_581G1 returns the predefined bls/BLS48-581-G1 curve.
func BlsBLS48_581G1() elliptic.Curve { return blsBLS48_581G1() }

var blsBandersnatch = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		t.Build(&t.CurveParams{
			Name:    `Bandersnatch`,
			BitSize: 255,
			P:       NewGFpModulusFromHex(`73eda753299d7d483339d80809a1d80553bda402fffe5bfeffffffff00000001`),
			A:       ParseGFpHex(`-5`),
			D:       ParseGFpHex(`6389c12633c267cbc66e3bf86be3b6d8cb66677177e54f92b369f2f5188d58e7`),
			N:       HI(`1cfb69d4ca675f520cce760202687600ff8f87007419047174fd06b52876e7e1`),
		}),
	)
})

// BlsBandersnatch returns the predefined bls/Bandersnatch curve.
func BlsBandersnatch() elliptic.Curve { return blsBandersnatch() }
