// Code generated by curve_generator. DO NOT EDIT.

package curves

import (
	"crypto/elliptic"
	"sync"

	. "github.com/RyuaNerin/elliptic2/internal"
	. "github.com/RyuaNerin/elliptic2/internal/curve"
	wp "github.com/RyuaNerin/elliptic2/internal/curve/weierstrassprime"
	. "github.com/RyuaNerin/elliptic2/internal/field"
)

var bnBn158 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `bn158`,
			BitSize: 158,
			P:       NewGFpModulusFromHex(`24240d8241d5445106c8442084001384e0000013`),
			A:       ParseGFpHex(``),
			B:       ParseGFpHex(`11`),
			N:       HI(`24240d8241d5445106c7e3f07e0010842000000d`),
			Gx:      HI(`24240d8241d5445106c8442084001384e0000012`),
			Gy:      HI(`4`),
		}),
	)
})

// BnBn158 returns the predefined bn/bn158 curve.
func BnBn158() elliptic.Curve { return bnBn158() }

var bnBn190 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `bn190`,
			BitSize: 190,
			P:       NewGFpModulusFromHex(`240001b0000948001e60004134005f10005dc0003a800013`),
			A:       ParseGFpHex(``),
			B:       ParseGFpHex(`1001`),
			N:       HI(`240001b0000948001e600040d4005cd0005760003180000d`),
			Gx:      HI(`240001b0000948001e60004134005f10005dc0003a800012`),
			Gy:      HI(`40`),
		}),
	)
})

// BnBn190 returns the predefined bn/bn190 curve.
func BnBn190() elliptic.Curve { return bnBn190() }

var bnBn222 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `bn222`,
			BitSize: 222,
			P:       NewGFpModulusFromHex(`23dc0d7dc02402cde486f4c00015b5215c0000004c6ce00000000067`),
			A:       ParseGFpHex(``),
			B:       ParseGFpHex(`101`),
			N:       HI(`23dc0d7dc02402cde486f4c00015555156000000496da00000000061`),
			Gx:      HI(`23dc0d7dc02402cde486f4c00015b5215c0000004c6ce00000000066`),
			Gy:      HI(`10`),
		}),
	)
})

// BnBn222 returns the predefined bn/bn222 curve.
func BnBn222() elliptic.Curve { return bnBn222() }

var bnBn254 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `bn254`,
			BitSize: 254,
			P:       NewGFpModulusFromHex(`2523648240000001ba344d80000000086121000000000013a700000000000013`),
			A:       ParseGFpHex(``),
			B:       ParseGFpHex(`2`),
			N:       HI(`2523648240000001ba344d8000000007ff9f800000000010a10000000000000d`),
			Gx:      HI(`2523648240000001ba344d80000000086121000000000013a700000000000012`),
			Gy:      HI(`1`),
		}),
	)
})

// BnBn254 returns the predefined bn/bn254 curve.
func BnBn254() elliptic.Curve { return bnBn254() }

var bnBn286 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `bn286`,
			BitSize: 286,
			P:       NewGFpModulusFromHex(`240900d8991b25b0e2cb51dda534a205391892080a008108000853813800138000000013`),
			A:       ParseGFpHex(``),
			B:       ParseGFpHex(`2`),
			N:       HI(`240900d8991b25b0e2cb51dda534a205391831fc099fc0fc0007f081080010800000000d`),
			Gx:      HI(`240900d8991b25b0e2cb51dda534a205391892080a008108000853813800138000000012`),
			Gy:      HI(`1`),
		}),
	)
})

// BnBn286 returns the predefined bn/bn286 curve.
func BnBn286() elliptic.Curve { return bnBn286() }

var bnBn318 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `bn318`,
			BitSize: 318,
			P:       NewGFpModulusFromHex(`24009000d800900024075015f015f0075000008f411e808f4000000004e484e4800000000000101b`),
			A:       ParseGFpHex(``),
			B:       ParseGFpHex(`2`),
			N:       HI(`24009000d800900024075015f015f0075000008ee11dc08ee000000004db84db8000000000000fe5`),
			Gx:      HI(`24009000d800900024075015f015f0075000008f411e808f4000000004e484e4800000000000101a`),
			Gy:      HI(`1`),
		}),
	)
})

// BnBn318 returns the predefined bn/bn318 curve.
func BnBn318() elliptic.Curve { return bnBn318() }

var bnBn350 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `bn350`,
			BitSize: 350,
			P:       NewGFpModulusFromHex(`23ffb80035ffee24020a01cafd738ec3f24b475ebc0ad0f6a0530fd78443fdf01a3ff64084000004e0000013`),
			A:       ParseGFpHex(``),
			B:       ParseGFpHex(`2`),
			N:       HI(`23ffb80035ffee24020a01cafd738ec3f24b475ebc0a70f70052f7d78413fe08173ff7c07e0000042000000d`),
			Gx:      HI(`23ffb80035ffee24020a01cafd738ec3f24b475ebc0ad0f6a0530fd78443fdf01a3ff64084000004e0000012`),
			Gy:      HI(`1`),
		}),
	)
})

// BnBn350 returns the predefined bn/bn350 curve.
func BnBn350() elliptic.Curve { return bnBn350() }

var bnBn382 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `bn382`,
			BitSize: 382,
			P:       NewGFpModulusFromHex(`240026400f3d82b2e42de125b00158405b710818ac00000840046200950400000000001380052e000000000000000013`),
			A:       ParseGFpHex(``),
			B:       ParseGFpHex(`2`),
			N:       HI(`240026400f3d82b2e42de125b00158405b710818ac000007e0042f008e3e00000000001080046200000000000000000d`),
			Gx:      HI(`240026400f3d82b2e42de125b00158405b710818ac00000840046200950400000000001380052e000000000000000012`),
			Gy:      HI(`1`),
		}),
	)
})

// BnBn382 returns the predefined bn/bn382 curve.
func BnBn382() elliptic.Curve { return bnBn382() }

var bnBn414 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `bn414`,
			BitSize: 414,
			P:       NewGFpModulusFromHex(`240024000d7ee23f2823ca035d31b144364c75e59aefff60544845142000765efff7c0000021138004dfffffd900000000000013`),
			A:       ParseGFpHex(``),
			B:       ParseGFpHex(`2`),
			N:       HI(`240024000d7ee23f2823ca035d31b144364c75e59aefff605447e513f00070607ff82000001f9080041fffffdf0000000000000d`),
			Gx:      HI(`240024000d7ee23f2823ca035d31b144364c75e59aefff60544845142000765efff7c0000021138004dfffffd900000000000012`),
			Gy:      HI(`1`),
		}),
	)
})

// BnBn414 returns the predefined bn/bn414 curve.
func BnBn414() elliptic.Curve { return bnBn414() }

var bnBn446 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `bn446`,
			BitSize: 446,
			P:       NewGFpModulusFromHex(`2400000000000000002400000002d00000000d800000021c0000001800000000870000000b0400000057c00000015c000000132000000067`),
			A:       ParseGFpHex(``),
			B:       ParseGFpHex(`101`),
			N:       HI(`2400000000000000002400000002d00000000d800000021c00000017a0000000870000000ad400000054c000000156000000126000000061`),
			Gx:      HI(`2400000000000000002400000002d00000000d800000021c0000001800000000870000000b0400000057c00000015c000000132000000066`),
			Gy:      HI(`10`),
		}),
	)
})

// BnBn446 returns the predefined bn/bn446 curve.
func BnBn446() elliptic.Curve { return bnBn446() }

var bnBn478 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `bn478`,
			BitSize: 478,
			P:       NewGFpModulusFromHex(`23fffffffffffffedfffffffee0001b3600000006bfff5db835fff5d28085442328002888f96f2944d7ded781430ffd780065fff010020fffd900013`),
			A:       ParseGFpHex(``),
			B:       ParseGFpHex(`2`),
			N:       HI(`23fffffffffffffedfffffffee0001b3600000006bfff5db835fff5d2807f442328002888f9872944d7e0578112f7fd780062fff07001f7ffdf0000d`),
			Gx:      HI(`23fffffffffffffedfffffffee0001b3600000006bfff5db835fff5d28085442328002888f96f2944d7ded781430ffd780065fff010020fffd900012`),
			Gy:      HI(`1`),
		}),
	)
})

// BnBn478 returns the predefined bn/bn478 curve.
func BnBn478() elliptic.Curve { return bnBn478() }

var bnBn510 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `bn510`,
			BitSize: 510,
			P:       NewGFpModulusFromHex(`2400000000000000003f000000000001b0002958000000000237000c0f0000084000f8100151a400073800242d00001380019440000000000888000000000013`),
			A:       ParseGFpHex(``),
			B:       ParseGFpHex(`101`),
			N:       HI(`2400000000000000003f000000000001b0002958000000000237000c0f000007e000f8100151a40006e400242d000010800181e000000000073800000000000d`),
			Gx:      HI(`2400000000000000003f000000000001b0002958000000000237000c0f0000084000f8100151a400073800242d00001380019440000000000888000000000012`),
			Gy:      HI(`10`),
		}),
	)
})

// BnBn510 returns the predefined bn/bn510 curve.
func BnBn510() elliptic.Curve { return bnBn510() }

var bnBn542 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `bn542`,
			BitSize: 542,
			P:       NewGFpModulusFromHex(`2400090000d80009000024000090001b01b1b051090510001b00d8001b0510d8a2084511080008d000090510005110800108138025380001b00000084000001380000013`),
			A:       ParseGFpHex(``),
			B:       ParseGFpHex(`2`),
			N:       HI(`2400090000d80009000024000090001b01b1b051090510001b00d8001b0510d8a207e510fc0008700009051000510fc000fc108025080001b0000007e00000108000000d`),
			Gx:      HI(`2400090000d80009000024000090001b01b1b051090510001b00d8001b0510d8a2084511080008d000090510005110800108138025380001b00000084000001380000012`),
			Gy:      HI(`1`),
		}),
	)
})

// BnBn542 returns the predefined bn/bn542 curve.
func BnBn542() elliptic.Curve { return bnBn542() }

var bnBn574 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `bn574`,
			BitSize: 574,
			P:       NewGFpModulusFromHex(`2400023ffffb7fff4c00002400167fffee01aee014423faefffb5c000a200050ffff2808400041fffe73fff7c000210000000000001380004dfffd90000000000000000000000013`),
			A:       ParseGFpHex(``),
			B:       ParseGFpHex(`2`),
			N:       HI(`2400023ffffb7fff4c00002400167fffee01aee014423faefffb5c000a200050ffff2807e0003efffe85fff820001f80000000000010800041fffdf000000000000000000000000d`),
			Gx:      HI(`2400023ffffb7fff4c00002400167fffee01aee014423faefffb5c000a200050ffff2808400041fffe73fff7c000210000000000001380004dfffd90000000000000000000000012`),
			Gy:      HI(`1`),
		}),
	)
})

// BnBn574 returns the predefined bn/bn574 curve.
func BnBn574() elliptic.Curve { return bnBn574() }

var bnBn606 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `bn606`,
			BitSize: 606,
			P:       NewGFpModulusFromHex(`23fffffffffffee00000000000036000000241affb7ffffff275e0024000001b1440000d94482df27fffc9aedf0000000036512100245142137fffffb75d7bd900000000000000246c844e13`),
			A:       ParseGFpHex(``),
			B:       ParseGFpHex(`2`),
			N:       HI(`23fffffffffffee00000000000036000000241affb7ffffff275e0024000001b1440000d9447cdf27fffc9aee08000000036511f8024513f107fffffb75d81df00000000000000246c7e420d`),
			Gx:      HI(`23fffffffffffee00000000000036000000241affb7ffffff275e0024000001b1440000d94482df27fffc9aedf0000000036512100245142137fffffb75d7bd900000000000000246c844e12`),
			Gy:      HI(`1`),
		}),
	)
})

// BnBn606 returns the predefined bn/bn606 curve.
func BnBn606() elliptic.Curve { return bnBn606() }

var bnBn638 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `bn638`,
			BitSize: 638,
			P:       NewGFpModulusFromHex(`23fffffdc000000d7fffffb8000001d3fffff942d000165e3fff94870000d52ffffdd0e00008de55c00086520021e55bfffff51ffff4eb800000004c80015acdffffffffffffece00000000000000067`),
			A:       ParseGFpHex(``),
			B:       ParseGFpHex(`101`),
			N:       HI(`23fffffdc000000d7fffffb8000001d3fffff942d000165e3fff94870000d52ffffdd0e00008de55600086550021e555fffff54ffff4eac000000049800154d9ffffffffffffeda00000000000000061`),
			Gx:      HI(`23fffffdc000000d7fffffb8000001d3fffff942d000165e3fff94870000d52ffffdd0e00008de55c00086520021e55bfffff51ffff4eb800000004c80015acdffffffffffffece00000000000000066`),
			Gy:      HI(`10`),
		}),
	)
})

// BnBn638 returns the predefined bn/bn638 curve.
func BnBn638() elliptic.Curve { return bnBn638() }
