// Code generated by curve_generator. DO NOT EDIT.

package curves

import (
	"crypto/elliptic"
	"sync"

	. "github.com/RyuaNerin/elliptic2/internal"
	. "github.com/RyuaNerin/elliptic2/internal/curve"
	wp "github.com/RyuaNerin/elliptic2/internal/curve/weierstrassprime"
	. "github.com/RyuaNerin/elliptic2/internal/field"
)

var mntMnt1 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `mnt1`,
			BitSize: 170,
			P:       NewGFpModulusFromHex(`26dccacc5041939206cf2b7dec50950e3c9fa4827af`),
			A:       ParseGFpHex(`22ffbb20cc052993fa27dc507800b624c650e4ff3d2`),
			B:       ParseGFpHex(`1c7be6fa8da953b5624efc72406af7fa77499803d08`),
			N:       HI(`a60fd646ad409b3312c3b23ba64e082ad7b354d`),
			Gx:      HI(`25a3ae778f7ef6586abae5acde21e54b6c64edf33d0`),
			Gy:      HI(`5b4ace33aa53c670ce35535d6c273698a182da557d`),
		}),
	)
})

// MntMnt1 returns the predefined mnt/mnt1 curve.
func MntMnt1() elliptic.Curve { return mntMnt1() }

var mntMnt2_1 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `mnt2/1`,
			BitSize: 159,
			P:       NewGFpModulusFromHex(`5affffffffffff4b46081000000059bb1bf600b7`),
			A:       ParseGFpHex(`3dd24a7e5c0bdfaccc215e22760469c73ee9d879`),
			B:       ParseGFpHex(`478c31a992b294e19f6e4416f958646dddede5e3`),
			N:       HI(`5affffffffffff4b46081000000059bb1bf600b5`),
			Gx:      HI(`2725af3d7dea98cb9242ac6ddb9bd89bdcf38898`),
			Gy:      HI(`480b4184ed2c50c0230b4c73ca939c1b6b7f1103`),
		}),
	)
})

// MntMnt2_1 returns the predefined mnt/mnt2/1 curve.
func MntMnt2_1() elliptic.Curve { return mntMnt2_1() }

var mntMnt2_2 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `mnt2/2`,
			BitSize: 159,
			P:       NewGFpModulusFromHex(`5affffffffffff4b46081000000059bb1bf600b7`),
			A:       ParseGFpHex(`7b29491c1a02cd87844f5098d0381f6c45d6523`),
			B:       ParseGFpHex(`41cc630bd66ac817d43358b108ad3d214037993c`),
			N:       HI(`5affffffffffff4b46081000000059bb1bf600b5`),
			Gx:      HI(`d76b3e1f1ed76a282fa99575d29ff2e587049e9`),
			Gy:      HI(`36e1557ed145ad409f924420e12f74a900fab054`),
		}),
	)
})

// MntMnt2_2 returns the predefined mnt/mnt2/2 curve.
func MntMnt2_2() elliptic.Curve { return mntMnt2_2() }

var mntMnt3_1 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `mnt3/1`,
			BitSize: 160,
			P:       NewGFpModulusFromHex(`8afffffffffffeeb0fa77000000089f0dd49fac7`),
			A:       ParseGFpHex(`6d01fd0a017c62075ae999977379867e07f2a6d4`),
			B:       ParseGFpHex(`7701535c00fd965341d38bba4cfbdcf9a4651825`),
			N:       HI(`8afffffffffffeeb0fa77000000089f0dd49fac5`),
			Gx:      HI(`1781998103c3ca14ea76b9d3a700a53e1c784789`),
			Gy:      HI(`53352dde04447c25c9bb332a3c7634d3b8801f34`),
		}),
	)
})

// MntMnt3_1 returns the predefined mnt/mnt3/1 curve.
func MntMnt3_1() elliptic.Curve { return mntMnt3_1() }

var mntMnt3_2 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `mnt3/2`,
			BitSize: 160,
			P:       NewGFpModulusFromHex(`8afffffffffffeeb0fa77000000089f0dd49fac7`),
			A:       ParseGFpHex(`5fbe0085bd2b23afcd5b9c7704aeed2bfdbe89e4`),
			B:       ParseGFpHex(`3fd4005928c76d1fde3d12fa031f48c7fe7f0698`),
			N:       HI(`8afffffffffffeeb0fa77000000089f0dd49fac5`),
			Gx:      HI(`494e297179d42c761701ab03b2e5bca98a24dfe7`),
			Gy:      HI(`3274201d6596252a780390a222e3763bbecfe5f1`),
		}),
	)
})

// MntMnt3_2 returns the predefined mnt/mnt3/2 curve.
func MntMnt3_2() elliptic.Curve { return mntMnt3_2() }

var mntMnt3_3 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `mnt3/3`,
			BitSize: 160,
			P:       NewGFpModulusFromHex(`8afffffffffffeeb0fa77000000089f0dd49fac7`),
			A:       ParseGFpHex(`2ddf23acb05a91bda6ba9c20d7a584aa25075ce0`),
			B:       ParseGFpHex(`1f8125c46a31e79fd6cc25298b23ab130cd22b5a`),
			N:       HI(`8afffffffffffeeb0fa77000000089f0dd49fac5`),
			Gx:      HI(`3f710d05b65b5e16ae1b946d3fc582b16a927432`),
			Gy:      HI(`4a30945c64fd7f85e148ba816005468447616b1f`),
		}),
	)
})

// MntMnt3_3 returns the predefined mnt/mnt3/3 curve.
func MntMnt3_3() elliptic.Curve { return mntMnt3_3() }

var mntMnt4 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `mnt4`,
			BitSize: 240,
			P:       NewGFpModulusFromHex(`a2ffffffffffffffffffffffffc298b00000000000000000000005c866cf`),
			A:       ParseGFpHex(`4be28760aa064734852cb4ff51ef2928a7a3cd75087c35cb1433714f7407`),
			B:       ParseGFpHex(`329704eb1c042f7858c878aa369f70c5c517de4e05a823dcb8224b8a4d5a`),
			N:       HI(`a2ffffffffffffffffffffffffc298b00000000000000000000005c866cd`),
			Gx:      HI(`82556d57811807a0d7675674b3d57222cfbf9a2a2a2cd146572d7b67627e`),
			Gy:      HI(`73afacea28dc870baa1d5b0bd4300ddd975e2eefc7c2db508fc2e92a8345`),
		}),
	)
})

// MntMnt4 returns the predefined mnt/mnt4 curve.
func MntMnt4() elliptic.Curve { return mntMnt4() }

var mntMnt5_1 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `mnt5/1`,
			BitSize: 240,
			P:       NewGFpModulusFromHex(`d2fffffffffffffffffffffffe9058d000000000000000000000a0271007`),
			A:       ParseGFpHex(`d149265d4687dcab1f2046e0947e51ac5e8e7f25916d35539d4df2e9017a`),
			B:       ParseGFpHex(`489e7783a1f584712bd4f6d48cf2d1ca2c975678936e639083991c5fc369`),
			N:       HI(`d2fffffffffffffffffffffffe9058d000000000000000000000a0271005`),
			Gx:      HI(`1d871a744f1e02ed15d7d84abd95e80476e6307085f12dba27092ff06d60`),
			Gy:      HI(`5c0c8bae9661303107b0077949dee16a7f6dde4982657b9196de23d9f9d0`),
		}),
	)
})

// MntMnt5_1 returns the predefined mnt/mnt5/1 curve.
func MntMnt5_1() elliptic.Curve { return mntMnt5_1() }

var mntMnt5_2 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `mnt5/2`,
			BitSize: 240,
			P:       NewGFpModulusFromHex(`d2fffffffffffffffffffffffe9058d000000000000000000000a0271007`),
			A:       ParseGFpHex(`26caaced434c5a4c2c9c1b09e0ddc167548a95516e7c81b20702485c9809`),
			B:       ParseGFpHex(`6031c89e2cdd91881dbd675beac3f3df8db1b8e0f45301215a01baf56ab3`),
			N:       HI(`d2fffffffffffffffffffffffe9058d000000000000000000000a0271005`),
			Gx:      HI(`16e55a2ef696238a7aaf19e51b6a81e1582f28b4bcb6575ab4e0331e569b`),
			Gy:      HI(`38de9844643fc9db3c568ec528983da16a177d56145a1d4bf88a2340d839`),
		}),
	)
})

// MntMnt5_2 returns the predefined mnt/mnt5/2 curve.
func MntMnt5_2() elliptic.Curve { return mntMnt5_2() }

var mntMnt5_3 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `mnt5/3`,
			BitSize: 240,
			P:       NewGFpModulusFromHex(`d2fffffffffffffffffffffffe9058d000000000000000000000a0271007`),
			A:       ParseGFpHex(`44cfc0f3bc92ec82f818b443b564cf25dee3ebae7902e370f9e80283d3bd`),
			B:       ParseGFpHex(`2ddfd5f7d30c9daca565cd8278eddf6e9497f27450ac97a0a69aac57e27e`),
			N:       HI(`d2fffffffffffffffffffffffe9058d000000000000000000000a0271005`),
			Gx:      HI(`b071579c8cc322dc7fdce378e5b539b4b7580823aba3cfdd6637cbfa0bbb`),
			Gy:      HI(`15d1b75795732b1e2db1efa55cdbb19357e0aa0422cc03b442809339cf02`),
		}),
	)
})

// MntMnt5_3 returns the predefined mnt/mnt5/3 curve.
func MntMnt5_3() elliptic.Curve { return mntMnt5_3() }
