// Code generated by curve_generator. DO NOT EDIT.

package curves

import (
	"crypto/elliptic"
	"sync"

	. "github.com/RyuaNerin/elliptic2/internal"
	. "github.com/RyuaNerin/elliptic2/internal/curve"
	t "github.com/RyuaNerin/elliptic2/internal/curve/twistededwards"
	wp "github.com/RyuaNerin/elliptic2/internal/curve/weierstrassprime"
	. "github.com/RyuaNerin/elliptic2/internal/field"
)

var numsEd254Mont = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		t.Build(&t.CurveParams{
			Name:    `ed-254-mont`,
			BitSize: 254,
			P:       NewGFpModulusFromHex(`3f80ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff`),
			A:       ParseGFpHex(`3f80fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe`),
			D:       ParseGFpHex(`367b`),
			N:       HI(`fe03fffffffffffffffffffffffffffeb95306c8bd62fb0eaf3d3fec46e98c7`),
		}),
	)
})

// NumsEd254Mont returns the predefined nums/ed-254-mont curve.
func NumsEd254Mont() elliptic.Curve { return numsEd254Mont() }

var numsEd255Mers = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		t.Build(&t.CurveParams{
			Name:    `ed-255-mers`,
			BitSize: 255,
			P:       NewGFpModulusFromHex(`7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffd03`),
			A:       ParseGFpHex(`7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffd02`),
			D:       ParseGFpHex(`ea97`),
			N:       HI(`1fffffffffffffffffffffffffffffffdcf1a785eda6832eac49d1ed0436eb75`),
		}),
	)
})

// NumsEd255Mers returns the predefined nums/ed-255-mers curve.
func NumsEd255Mers() elliptic.Curve { return numsEd255Mers() }

var numsEd256Mont = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		t.Build(&t.CurveParams{
			Name:    `ed-256-mont`,
			BitSize: 256,
			P:       NewGFpModulusFromHex(`ffa7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff`),
			A:       ParseGFpHex(`ffa7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe`),
			D:       ParseGFpHex(`350a`),
			N:       HI(`3fe9ffffffffffffffffffffffffffffb154bbafb86733c966d92eded8ec7bab`),
		}),
	)
})

// NumsEd256Mont returns the predefined nums/ed-256-mont curve.
func NumsEd256Mont() elliptic.Curve { return numsEd256Mont() }

var numsEd382Mont = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		t.Build(&t.CurveParams{
			Name:    `ed-382-mont`,
			BitSize: 382,
			P:       NewGFpModulusFromHex(`3ffaffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff`),
			A:       ParseGFpHex(`3ffafffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe`),
			D:       ParseGFpHex(`af381`),
			N:       HI(`ffebfffffffffffffffffffffffffffffffffffffffffffd31afaa1520dc177d8c1605c481e068269880369e5f3fa61`),
		}),
	)
})

// NumsEd382Mont returns the predefined nums/ed-382-mont curve.
func NumsEd382Mont() elliptic.Curve { return numsEd382Mont() }

var numsEd383Mers = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		t.Build(&t.CurveParams{
			Name:    `ed-383-mers`,
			BitSize: 383,
			P:       NewGFpModulusFromHex(`7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe5b`),
			A:       ParseGFpHex(`7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe5a`),
			D:       ParseGFpHex(`7fed6`),
			N:       HI(`1ffffffffffffffffffffffffffffffffffffffffffffffff1109704e73d9fbbbcd5687c9eaca2206ffebcec1ba7c81d`),
		}),
	)
})

// NumsEd383Mers returns the predefined nums/ed-383-mers curve.
func NumsEd383Mers() elliptic.Curve { return numsEd383Mers() }

var numsEd384Mont = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		t.Build(&t.CurveParams{
			Name:    `ed-384-mont`,
			BitSize: 384,
			P:       NewGFpModulusFromHex(`b0ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff`),
			A:       ParseGFpHex(`b0fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe`),
			D:       ParseGFpHex(`6f17`),
			N:       HI(`2c3ffffffffffffffffffffffffffffffffffffffffffffff56d07e24e2749cd9f6b769aec80f6fe06fe4e3a6332489b`),
		}),
	)
})

// NumsEd384Mont returns the predefined nums/ed-384-mont curve.
func NumsEd384Mont() elliptic.Curve { return numsEd384Mont() }

var numsEd510Mont = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		t.Build(&t.CurveParams{
			Name:    `ed-510-mont`,
			BitSize: 510,
			P:       NewGFpModulusFromHex(`3eddffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff`),
			A:       ParseGFpHex(`3eddfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe`),
			D:       ParseGFpHex(`8da1e`),
			N:       HI(`fb77fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffd7ced11e7c2f1abf716df42a6c246080b5fcc20917e59a42c85821cdf36d51b1`),
		}),
	)
})

// NumsEd510Mont returns the predefined nums/ed-510-mont curve.
func NumsEd510Mont() elliptic.Curve { return numsEd510Mont() }

var numsEd511Mers = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		t.Build(&t.CurveParams{
			Name:    `ed-511-mers`,
			BitSize: 511,
			P:       NewGFpModulusFromHex(`7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe1f`),
			A:       ParseGFpHex(`7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe1e`),
			D:       ParseGFpHex(`10bf7d`),
			N:       HI(`1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffea7c34182e41e2e9baa930e478c489b72542706bec5f32194f7c2e8f8d142f11`),
		}),
	)
})

// NumsEd511Mers returns the predefined nums/ed-511-mers curve.
func NumsEd511Mers() elliptic.Curve { return numsEd511Mers() }

var numsEd512Mont = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		t.Build(&t.CurveParams{
			Name:    `ed-512-mont`,
			BitSize: 512,
			P:       NewGFpModulusFromHex(`fe14ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff`),
			A:       ParseGFpHex(`fe14fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe`),
			D:       ParseGFpHex(`12a9c`),
			N:       HI(`3f853fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfd59cdc33470d103060513f6def4d37d9af21b2b2701fa331487ecb8db605`),
		}),
	)
})

// NumsEd512Mont returns the predefined nums/ed-512-mont curve.
func NumsEd512Mont() elliptic.Curve { return numsEd512Mont() }

var numsNumsp256d1 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `numsp256d1`,
			BitSize: 256,
			P:       NewGFpModulusFromHex(`ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff43`),
			A:       ParseGFpHex(`ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff40`),
			B:       ParseGFpHex(`25581`),
			N:       HI(`ffffffffffffffffffffffffffffffffe43c8275ea265c6020ab20294751a825`),
			Gx:      HI(`1`),
			Gy:      HI(`696f1853c1e466d7fc82c96cceeedd6bd02c2f9375894ec10bf46306c2b56c77`),
		}),
	)
})

// NumsNumsp256d1 returns the predefined nums/numsp256d1 curve.
func NumsNumsp256d1() elliptic.Curve { return numsNumsp256d1() }

var numsNumsp256t1 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		t.Build(&t.CurveParams{
			Name:    `numsp256t1`,
			BitSize: 256,
			P:       NewGFpModulusFromHex(`ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff43`),
			A:       ParseGFpHex(`ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff42`),
			D:       ParseGFpHex(`3bee`),
			N:       HI(`3fffffffffffffffffffffffffffffffbe6aa55ad0a6bc64e5b84e6f1122b4ad`),
			Gx:      HI(`d`),
			Gy:      HI(`7d0ab41e2a1276dba3d330b39fa046bfbe2a6d63824d303f707f6fb5331cadba`),
		}),
	)
})

// NumsNumsp256t1 returns the predefined nums/numsp256t1 curve.
func NumsNumsp256t1() elliptic.Curve { return numsNumsp256t1() }

var numsNumsp384d1 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `numsp384d1`,
			BitSize: 384,
			P:       NewGFpModulusFromHex(`fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffec3`),
			A:       ParseGFpHex(`fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffec0`),
			B:       ParseGFpHex(`ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff77bb`),
			N:       HI(`ffffffffffffffffffffffffffffffffffffffffffffffffd61eaf1eeb5d6881beda9d3d4c37e27a604d81f67b0e61b9`),
			Gx:      HI(`2`),
			Gy:      HI(`3c9f82cb4b87b4dc71e763e0663e5dbd8034ed422f04f82673330dc58d15ffa2b4a3d0bad5d30f865bcbbf503ea66f43`),
		}),
	)
})

// NumsNumsp384d1 returns the predefined nums/numsp384d1 curve.
func NumsNumsp384d1() elliptic.Curve { return numsNumsp384d1() }

var numsNumsp384t1 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		t.Build(&t.CurveParams{
			Name:    `numsp384t1`,
			BitSize: 384,
			P:       NewGFpModulusFromHex(`fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffec3`),
			A:       ParseGFpHex(`fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffec2`),
			D:       ParseGFpHex(`5158a`),
			N:       HI(`3fffffffffffffffffffffffffffffffffffffffffffffffecd7d11ed5a259a25a13a0458e39f4e451d6d71f70426e25`),
			Gx:      HI(`8`),
			Gy:      HI(`749cdaba136ce9b65bd4471794aa619daa5c7b4c930bff8ebd798a8ae753c6d72f003860febabad534a4acf5fa7f5bee`),
		}),
	)
})

// NumsNumsp384t1 returns the predefined nums/numsp384t1 curve.
func NumsNumsp384t1() elliptic.Curve { return numsNumsp384t1() }

var numsNumsp512d1 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `numsp512d1`,
			BitSize: 512,
			P:       NewGFpModulusFromHex(`fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdc7`),
			A:       ParseGFpHex(`fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdc4`),
			B:       ParseGFpHex(`1d99b`),
			N:       HI(`ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5b3ca4fb94e7831b4fc258ed97d0bdc63b568b36607cd243ce153f390433555d`),
			Gx:      HI(`2`),
			Gy:      HI(`1c282eb23327f9711952c250ea61ad53fcc13031cf6dd336e0b9328433afbdd8cc5a1c1f0c716fdc724dde537c2b0adb00bb3d08dc83755b205cc30d7f83cf28`),
		}),
	)
})

// NumsNumsp512d1 returns the predefined nums/numsp512d1 curve.
func NumsNumsp512d1() elliptic.Curve { return numsNumsp512d1() }

var numsNumsp512t1 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		t.Build(&t.CurveParams{
			Name:    `numsp512t1`,
			BitSize: 512,
			P:       NewGFpModulusFromHex(`fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdc7`),
			A:       ParseGFpHex(`fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdc6`),
			D:       ParseGFpHex(`9baa8`),
			N:       HI(`3fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffa7e50809efdabbb9a624784f449545f0dcea5ff0cb800f894e78d1cb0b5f0189`),
			Gx:      HI(`20`),
			Gy:      HI(`7d67e841dc4c467b605091d80869212f9ceb124bf726973f9ff048779e1d614e62ae2ece5057b5dad96b7a897c1d72799261134638750f4f0cb91027543b1c5e`),
		}),
	)
})

// NumsNumsp512t1 returns the predefined nums/numsp512t1 curve.
func NumsNumsp512t1() elliptic.Curve { return numsNumsp512t1() }

var numsW254Mont = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `w-254-mont`,
			BitSize: 254,
			P:       NewGFpModulusFromHex(`3f80ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff`),
			A:       ParseGFpHex(`3f80fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc`),
			B:       ParseGFpHex(`-2f72`),
			N:       HI(`3f80ffffffffffffffffffffffffffffeb818bea0da375c06fa419c4af8df83f`),
		}),
	)
})

// NumsW254Mont returns the predefined nums/w-254-mont curve.
func NumsW254Mont() elliptic.Curve { return numsW254Mont() }

var numsW255Mers = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `w-255-mers`,
			BitSize: 255,
			P:       NewGFpModulusFromHex(`7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffd03`),
			A:       ParseGFpHex(`7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffd00`),
			B:       ParseGFpHex(`-51bd`),
			N:       HI(`7fffffffffffffffffffffffffffffff864a38283ad2b3dfab8fac983c594aeb`),
		}),
	)
})

// NumsW255Mers returns the predefined nums/w-255-mers curve.
func NumsW255Mers() elliptic.Curve { return numsW255Mers() }

var numsW256Mont = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `w-256-mont`,
			BitSize: 256,
			P:       NewGFpModulusFromHex(`ffa7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff`),
			A:       ParseGFpHex(`ffa7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc`),
			B:       ParseGFpHex(`14e6a`),
			N:       HI(`ffa7fffffffffffffffffffffffffffffc517513e6e5074b9d10c5e1a79857eb`),
		}),
	)
})

// NumsW256Mont returns the predefined nums/w-256-mont curve.
func NumsW256Mont() elliptic.Curve { return numsW256Mont() }

var numsW382Mont = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `w-382-mont`,
			BitSize: 382,
			P:       NewGFpModulusFromHex(`3ffaffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff`),
			A:       ParseGFpHex(`3ffafffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc`),
			B:       ParseGFpHex(`-20a72`),
			N:       HI(`3ffaffffffffffffffffffffffffffffffffffffffffffffa6eb1cff4bde214d73b321ffd8e82cd160ab86803ebb301d`),
		}),
	)
})

// NumsW382Mont returns the predefined nums/w-382-mont curve.
func NumsW382Mont() elliptic.Curve { return numsW382Mont() }

var numsW383Mers = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `w-383-mers`,
			BitSize: 383,
			P:       NewGFpModulusFromHex(`7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe5b`),
			A:       ParseGFpHex(`7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe58`),
			B:       ParseGFpHex(`17dbc`),
			N:       HI(`7fffffffffffffffffffffffffffffffffffffffffffffffa9caf814a8a116ad9fb0b4035417aaf319297fc0bb7a439f`),
		}),
	)
})

// NumsW383Mers returns the predefined nums/w-383-mers curve.
func NumsW383Mers() elliptic.Curve { return numsW383Mers() }

var numsW384Mont = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `w-384-mont`,
			BitSize: 384,
			P:       NewGFpModulusFromHex(`b0ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff`),
			A:       ParseGFpHex(`b0fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc`),
			B:       ParseGFpHex(`6c96`),
			N:       HI(`b0ffffffffffffffffffffffffffffffffffffffffffffffba9b7f14ca7512537a4edcd38a7c41da29be4894b298eebb`),
		}),
	)
})

// NumsW384Mont returns the predefined nums/w-384-mont curve.
func NumsW384Mont() elliptic.Curve { return numsW384Mont() }

var numsW510Mont = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `w-510-mont`,
			BitSize: 510,
			P:       NewGFpModulusFromHex(`3eddffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff`),
			A:       ParseGFpHex(`3eddfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc`),
			B:       ParseGFpHex(`988d`),
			N:       HI(`3eddffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb9146ccde150ef33747ab29d1e6573d8d22de95e322303f3a00b200986fa9a2d`),
		}),
	)
})

// NumsW510Mont returns the predefined nums/w-510-mont curve.
func NumsW510Mont() elliptic.Curve { return numsW510Mont() }

var numsW511Mers = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `w-511-mers`,
			BitSize: 511,
			P:       NewGFpModulusFromHex(`7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe1f`),
			A:       ParseGFpHex(`7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe1c`),
			B:       ParseGFpHex(`879da`),
			N:       HI(`7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff8dbefa3f5ed9d839a2d4fe6ff516e87fa8d3e656a0f99fa1f0105f73b3b9d19f`),
		}),
	)
})

// NumsW511Mers returns the predefined nums/w-511-mers curve.
func NumsW511Mers() elliptic.Curve { return numsW511Mers() }

var numsW512Mont = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `w-512-mont`,
			BitSize: 512,
			P:       NewGFpModulusFromHex(`fe14ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff`),
			A:       ParseGFpHex(`fe14fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc`),
			B:       ParseGFpHex(`185ed`),
			N:       HI(`fe14ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff638a8d792ee750298064aaf0b8498e61df3d3995064ed73b939628f17e98fdc9`),
		}),
	)
})

// NumsW512Mont returns the predefined nums/w-512-mont curve.
func NumsW512Mont() elliptic.Curve { return numsW512Mont() }
