// Code generated by curve_generator. DO NOT EDIT.

package curves

import (
	"crypto/elliptic"
	"sync"

	. "github.com/RyuaNerin/elliptic2/internal"
	. "github.com/RyuaNerin/elliptic2/internal/curve"
	e "github.com/RyuaNerin/elliptic2/internal/curve/edwards"
	m "github.com/RyuaNerin/elliptic2/internal/curve/montgomery"
	t "github.com/RyuaNerin/elliptic2/internal/curve/twistededwards"
	wp "github.com/RyuaNerin/elliptic2/internal/curve/weierstrassprime"
	. "github.com/RyuaNerin/elliptic2/internal/field"
)

var otherBADA55R256 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `BADA55-R-256`,
			BitSize: 256,
			P:       NewGFpModulusFromHex(`f1fd178c0b3ad58f10126de8ce42435b3961adbcabc8ca6de8fcf353d86e9c03`),
			A:       ParseGFpHex(`f1fd178c0b3ad58f10126de8ce42435b3961adbcabc8ca6de8fcf353d86e9c00`),
			B:       ParseGFpHex(`bada55bada55bada55bada55bada55bada55bada55bada55bada55bada55bd48`),
			N:       HI(`f1fd178c0b3ad58f10126de8ce42435a1a8e3837861aa0efa0e52aec7379c967`),
		}),
	)
})

// OtherBADA55R256 returns the predefined other/BADA55-R-256 curve.
func OtherBADA55R256() elliptic.Curve { return otherBADA55R256() }

var otherBADA55VPR224 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `BADA55-VPR-224`,
			BitSize: 224,
			P:       NewGFpModulusFromHex(`ffffffffffffffffffffffffffffffff000000000000000000000001`),
			A:       ParseGFpHex(`7144ba12ce8a0c3befa053edbada555a42391fc64f052376e041c7d4af23195ebd8d83625321d452e8a0c3bb0a048a26115704e45dceb346a9f4bd9741d14d49`),
			B:       ParseGFpHex(`5c32ec7fc48ce1802d9b70dbc3fa574eaf015fce4e99b43ebe3468d6efb2276ba3669aff6ffc0f4c6ae4ae2e5d74c3c0af97dce17147688dda89e734b56944a2`),
			N:       HI(`ffffffffffffffffffffffffffff473fa5d3e9bf40a95a8d3f014add`),
		}),
	)
})

// OtherBADA55VPR224 returns the predefined other/BADA55-VPR-224 curve.
func OtherBADA55VPR224() elliptic.Curve { return otherBADA55VPR224() }

var otherBADA55VPR2_224 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `BADA55-VPR2-224`,
			BitSize: 224,
			P:       NewGFpModulusFromHex(`ffffffffffffffffffffffffffffffff000000000000000000000001`),
			A:       ParseGFpHex(`8f0ff20e1e3cf4905d492e04110683948bfc236790bbb59e6e6b33f24f348ed2e16c64ee79f9fd27e9a367ff6415b41189e4fb6bada555455dc44c4f87011eef`),
			B:       ParseGFpHex(`e85067a95547e30661c854a43ed80f36289043ffc73da78a97e37fb96a2717009088656b948865a660ff3959330d8a1ca1e4de31b7b7d496a4cde555e57d05c`),
			N:       HI(`ffffffffffffffffffffffffffffdf5c0319f61dc6ccebe902bc220f`),
		}),
	)
})

// OtherBADA55VPR2_224 returns the predefined other/BADA55-VPR2-224 curve.
func OtherBADA55VPR2_224() elliptic.Curve { return otherBADA55VPR2_224() }

var otherBADA55VR224 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `BADA55-VR-224`,
			BitSize: 224,
			P:       NewGFpModulusFromHex(`ffffffffffffffffffffffffffffffff000000000000000000000001`),
			A:       ParseGFpHex(`fffffffffffffffffffffffffffffffefffffffffffffffffffffffe`),
			B:       ParseGFpHex(`bada55ecfd9ca54c0738b8a6fb8cf4ccf84e916d83d6da1b78b622351e11ab4e`),
			N:       HI(`ffffffffffffffffffffffffffff0d44ef1096b2b67b7a3dcee7b079`),
		}),
	)
})

// OtherBADA55VR224 returns the predefined other/BADA55-VR-224 curve.
func OtherBADA55VR224() elliptic.Curve { return otherBADA55VR224() }

var otherBADA55VR256 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `BADA55-VR-256`,
			BitSize: 256,
			P:       NewGFpModulusFromHex(`ffffffff00000001000000000000000000000000ffffffffffffffffffffffff`),
			A:       ParseGFpHex(`ffffffff00000001000000000000000000000000fffffffffffffffffffffffc`),
			B:       ParseGFpHex(`bada55ecd8bbead3add6c534f92197deb47fceb9be7e0e702a8d1dd56b5d0b0c`),
			N:       HI(`ffffffff00000000fffffffffffffffebedc2797003336661a49d76a903bdb91`),
		}),
	)
})

// OtherBADA55VR256 returns the predefined other/BADA55-VR-256 curve.
func OtherBADA55VR256() elliptic.Curve { return otherBADA55VR256() }

var otherBADA55VR384 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `BADA55-VR-384`,
			BitSize: 384,
			P:       NewGFpModulusFromHex(`fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeffffffff0000000000000000ffffffff`),
			A:       ParseGFpHex(`fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeffffffff0000000000000000fffffffc`),
			B:       ParseGFpHex(`bada55ec3be2ad1f9eeea5881ecf95bbf3ac392526f01d4cd13e684c63a17cc4d5f271642ad83899113817a61006413d`),
			N:       HI(`fffffffffffffffffffffffffffffffffffffffffffffffeefe1169b82ff7e5032c683f766fae57359cfc5fc25ffce37`),
		}),
	)
})

// OtherBADA55VR384 returns the predefined other/BADA55-VR-384 curve.
func OtherBADA55VR384() elliptic.Curve { return otherBADA55VR384() }

var otherCurve1174 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `Curve1174`,
			BitSize: 251,
			P:       NewGFpModulusFromHex(`7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7`),
			A:       ParseGFpHex(`486be25b34c8080922b969257eeb54c404f914a29067a5560bb9aee0bc67a6d`),
			B:       ParseGFpHex(`e347a25bf875dd2f1f12d8a10334d417cc15e77893a99f4bf278ca563072e6`),
			N:       HI(`1fffffffffffffffffffffffffffffff77965c4dfd307348944d45fd166c971`),
			Gx:      HI(`3be821d63d2cd5afe0504f452e5cf47a60a10446928ceaecfd5294f89b45051`),
			Gy:      HI(`66fe4e7b8b6fe152f743393029a61bfb839747c8fb00f7b27a6841c07532a0`),
		}),
	)
})

// OtherCurve1174 returns the predefined other/Curve1174 curve.
func OtherCurve1174() elliptic.Curve { return otherCurve1174() }

var otherCurve22103 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `Curve22103`,
			BitSize: 221,
			P:       NewGFpModulusFromHex(`1ffffffffffffffffffffffffffffffffffffffffffffffffffffffd`),
			A:       ParseGFpHex(`155555555555555555555555555555555555555555555552174084ff`),
			B:       ParseGFpHex(`1425ed097b425ed097b425ed097b425ed097b425ed0bba9428427967`),
			N:       HI(`3fffffffffffffffffffffffffff5cd04695a145c3067cf4aae2025`),
			Gx:      HI(`cb476fe081b61f56a60b1d1b34fb7207d072ef25dadf377731049b0`),
			Gy:      HI(`36429404d97e1e217bad2e5601f6551f95d8fe9481bd454d1f3e7b6`),
		}),
	)
})

// OtherCurve22103 returns the predefined other/Curve22103 curve.
func OtherCurve22103() elliptic.Curve { return otherCurve22103() }

var otherCurve25519 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		m.Build(&m.CurveParams{
			Name:    `Curve25519`,
			BitSize: 255,
			P:       NewGFpModulusFromHex(`7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffed`),
			A:       ParseGFpHex(`76d06`),
			B:       ParseGFpHex(`1`),
			N:       HI(`1000000000000000000000000000000014def9dea2f79cd65812631a5cf5d3ed`),
			Gx:      HI(`9`),
			Gy:      HI(`20ae19a1b8a086b4e01edd2c7748d14c923d4d7e6d7c61b229e9c5a27eced3d9`),
		}),
	)
})

// OtherCurve25519 returns the predefined other/Curve25519 curve.
func OtherCurve25519() elliptic.Curve { return otherCurve25519() }

var otherCurve383187 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		m.Build(&m.CurveParams{
			Name:    `Curve383187`,
			BitSize: 283,
			P:       NewGFpModulusFromHex(`7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff45`),
			A:       ParseGFpHex(`38251`),
			B:       ParseGFpHex(`1`),
			N:       HI(`1000000000000000000000000000000000000000000000000e85a85287a1488acd41ae84b2b7030446f72088b00a0e21`),
			Gx:      HI(`5`),
			Gy:      HI(`1eebe07dc1871896732b12d5504a32370471965c7a11f2c89865f855ab3cbd7c224e3620c31af3370788457dd5ce46df`),
		}),
	)
})

// OtherCurve383187 returns the predefined other/Curve383187 curve.
func OtherCurve383187() elliptic.Curve { return otherCurve383187() }

var otherCurve41417 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		t.Build(&t.CurveParams{
			Name:    `Curve41417`,
			BitSize: 414,
			P:       NewGFpModulusFromHex(`3fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffef`),
			A:       ParseGFpHex(`1`),
			D:       ParseGFpHex(`e21`),
			N:       HI(`7ffffffffffffffffffffffffffffffffffffffffffffffffffeb3cc92414cf706022b36f1c0338ad63cf181b0e71a5e106af79`),
			Gx:      HI(`1a334905141443300218c0631c326e5fcd46369f44c03ec7f57ff35498a4ab4d6d6ba111301a73faa8537c64c4fd3812f3cbc595`),
			Gy:      HI(`22`),
		}),
	)
})

// OtherCurve41417 returns the predefined other/Curve41417 curve.
func OtherCurve41417() elliptic.Curve { return otherCurve41417() }

var otherCurve4417 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `Curve4417`,
			BitSize: 226,
			P:       NewGFpModulusFromHex(`3fffffffffffffffffffffffffffffffffffffffffffffffffffffffb`),
			A:       ParseGFpHex(`4648d10b419379d50f4ba01869d9ae363285e01fe66920878ee075b0`),
			B:       ParseGFpHex(`4c4dcedfac09383a0311b98ee9637415b9134b4115fdb760c1a3d419`),
			N:       HI(`fffffffffffffffffffffffffffffc4a75594d4923fc93d42713cdaf`),
			Gx:      HI(`ff9d7edd97d523012ffaaca32b7c90f1a8e026f21972c789a8484a2b`),
			Gy:      HI(`3e9036adc1a41fce2f2ca08e2d1be4f6d97e30ca7761db1f3e2f2ce96`),
		}),
	)
})

// OtherCurve4417 returns the predefined other/Curve4417 curve.
func OtherCurve4417() elliptic.Curve { return otherCurve4417() }

var otherCurve448 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		m.Build(&m.CurveParams{
			Name:    `Curve448`,
			BitSize: 448,
			P:       NewGFpModulusFromHex(`fffffffffffffffffffffffffffffffffffffffffffffffffffffffeffffffffffffffffffffffffffffffffffffffffffffffffffffffff`),
			A:       ParseGFpHex(`262a6`),
			B:       ParseGFpHex(`1`),
			N:       HI(`3fffffffffffffffffffffffffffffffffffffffffffffffffffffff7cca23e9c44edb49aed63690216cc2728dc58f552378c292ab5844f3`),
			Gx:      HI(`5`),
			Gy:      HI(`7d235d1295f5b1f66c98ab6e58326fcecbae5d34f55545d060f75dc28df3f6edb8027e2346430d211312c4b150677af76fd7223d457b5b1a`),
		}),
	)
})

// OtherCurve448 returns the predefined other/Curve448 curve.
func OtherCurve448() elliptic.Curve { return otherCurve448() }

var otherCurve67254 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `Curve67254`,
			BitSize: 382,
			P:       NewGFpModulusFromHex(`3fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff97`),
			A:       ParseGFpHex(`2e32419a32377af8e7f03148a106d112c8c2e26d31a89f46b743deed322c7adc3024afe4b5afd8db7180281586549f4a`),
			B:       ParseGFpHex(`22f6ef3be72a67fdc236d7173727cd2af6d02a195753c44bdf451369b02ea0f963d9a775cae6dc3ae9ccabb7f183c1ad`),
			N:       HI(`fffffffffffffffffffffffffffffffffffffffffffffffd5fb21f21e95eee17c5e69281b102d2773e27e13fd3c9719`),
			Gx:      HI(`141946416199fdda96ec1f1ac80058aa3f0ce96b1bcd023e97bae542fe3404b4738db9b81a13698339387672eca360c0`),
			Gy:      HI(`d51bf79d968f4a076022e750f821058e2b5073697b639edd355ebf8ad32352b1efa9478de7eb5662ef0d26ef6eea795`),
		}),
	)
})

// OtherCurve67254 returns the predefined other/Curve67254 curve.
func OtherCurve67254() elliptic.Curve { return otherCurve67254() }

var otherE222 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		e.Build(&e.CurveParams{
			Name:    `E-222`,
			BitSize: 222,
			P:       NewGFpModulusFromHex(`3fffffffffffffffffffffffffffffffffffffffffffffffffffff8b`),
			C:       ParseGFpHex(`1`),
			D:       ParseGFpHex(`27166`),
			N:       HI(`ffffffffffffffffffffffffffff70cbc95e932f802f31423598cbf`),
			Gx:      HI(`19b12bb156a389e55c9768c303316d07c23adab3736eb2bc3eb54e51`),
			Gy:      HI(`1c`),
		}),
	)
})

// OtherE222 returns the predefined other/E-222 curve.
func OtherE222() elliptic.Curve { return otherE222() }

var otherE382 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		e.Build(&e.CurveParams{
			Name:    `E-382`,
			BitSize: 382,
			P:       NewGFpModulusFromHex(`3fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff97`),
			C:       ParseGFpHex(`1`),
			D:       ParseGFpHex(`3ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffef8e1`),
			N:       HI(`fffffffffffffffffffffffffffffffffffffffffffffffd5fb21f21e95eee17c5e69281b102d2773e27e13fd3c9719`),
			Gx:      HI(`196f8dd0eab20391e5f05be96e8d20ae68f840032b0b64352923bab85364841193517dbce8105398ebc0cc9470f79603`),
			Gy:      HI(`11`),
		}),
	)
})

// OtherE382 returns the predefined other/E-382 curve.
func OtherE382() elliptic.Curve { return otherE382() }

var otherE521 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		e.Build(&e.CurveParams{
			Name:    `E-521`,
			BitSize: 521,
			P:       NewGFpModulusFromHex(`1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff`),
			C:       ParseGFpHex(`1`),
			D:       ParseGFpHex(`1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffa4331`),
			N:       HI(`7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffd15b6c64746fc85f736b8af5e7ec53f04fbd8c4569a8f1f4540ea2435f5180d6b`),
			Gx:      HI(`752cb45c48648b189df90cb2296b2878a3bfd9f42fc6c818ec8bf3c9c0c6203913f6ecc5ccc72434b1ae949d568fc99c6059d0fb13364838aa302a940a2f19ba6c`),
			Gy:      HI(`c`),
		}),
	)
})

// OtherE521 returns the predefined other/E-521 curve.
func OtherE521() elliptic.Curve { return otherE521() }

var otherEd25519 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		t.Build(&t.CurveParams{
			Name:    `Ed25519`,
			BitSize: 255,
			P:       NewGFpModulusFromHex(`7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffed`),
			A:       ParseGFpHex(`7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffec`),
			D:       ParseGFpHex(`52036cee2b6ffe738cc740797779e89800700a4d4141d8ab75eb4dca135978a3`),
			N:       HI(`1000000000000000000000000000000014def9dea2f79cd65812631a5cf5d3ed`),
			Gx:      HI(`216936d3cd6e53fec0a4e231fdd6dc5c692cc7609525a7b2c9562d608f25d51a`),
			Gy:      HI(`6666666666666666666666666666666666666666666666666666666666666658`),
		}),
	)
})

// OtherEd25519 returns the predefined other/Ed25519 curve.
func OtherEd25519() elliptic.Curve { return otherEd25519() }

var otherEd448 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		t.Build(&t.CurveParams{
			Name:    `Ed448`,
			BitSize: 448,
			P:       NewGFpModulusFromHex(`fffffffffffffffffffffffffffffffffffffffffffffffffffffffeffffffffffffffffffffffffffffffffffffffffffffffffffffffff`),
			A:       ParseGFpHex(`1`),
			D:       ParseGFpHex(`d78b4bdc7f0daf19f24f38c29373a2ccad46157242a50f37809b1da3412a12e79ccc9c81264cfe9ad080997058fb61c4243cc32dbaa156b9`),
			N:       HI(`3fffffffffffffffffffffffffffffffffffffffffffffffffffffff7cca23e9c44edb49aed63690216cc2728dc58f552378c292ab5844f3`),
			Gx:      HI(`79a70b2b70400553ae7c9df416c792c61128751ac92969240c25a07d728bdc93e21f7787ed6972249de732f38496cd11698713093e9c04fc`),
			Gy:      HI(`7fffffffffffffffffffffffffffffffffffffffffffffffffffffff80000000000000000000000000000000000000000000000000000001`),
		}),
	)
})

// OtherEd448 returns the predefined other/Ed448 curve.
func OtherEd448() elliptic.Curve { return otherEd448() }

var otherEd448Goldilocks = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		t.Build(&t.CurveParams{
			Name:    `Ed448-Goldilocks`,
			BitSize: 448,
			P:       NewGFpModulusFromHex(`fffffffffffffffffffffffffffffffffffffffffffffffffffffffeffffffffffffffffffffffffffffffffffffffffffffffffffffffff`),
			A:       ParseGFpHex(`1`),
			D:       ParseGFpHex(`fffffffffffffffffffffffffffffffffffffffffffffffffffffffeffffffffffffffffffffffffffffffffffffffffffffffffffff6756`),
			N:       HI(`3fffffffffffffffffffffffffffffffffffffffffffffffffffffff7cca23e9c44edb49aed63690216cc2728dc58f552378c292ab5844f3`),
			Gx:      HI(`aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa955555555555555555555555555555555555555555555555555555555`),
			Gy:      HI(`ae05e9634ad7048db359d6205086c2b0036ed7a035884dd7b7e36d728ad8c4b80d6565833a2a3098bbbcb2bed1cda06bdaeafbcdea9386ed`),
		}),
	)
})

// OtherEd448Goldilocks returns the predefined other/Ed448-Goldilocks curve.
func OtherEd448Goldilocks() elliptic.Curve { return otherEd448Goldilocks() }

var otherFp224BN = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `Fp224BN`,
			BitSize: 224,
			P:       NewGFpModulusFromHex(`fffffffffff107288ec29e602c4520db42180823bb907d1287127833`),
			A:       ParseGFpHex(``),
			B:       ParseGFpHex(`3`),
			N:       HI(`fffffffffff107288ec29e602c4420db4218082b36c2accff76c58ed`),
			Gx:      HI(`1`),
			Gy:      HI(`2`),
		}),
	)
})

// OtherFp224BN returns the predefined other/Fp224BN curve.
func OtherFp224BN() elliptic.Curve { return otherFp224BN() }

var otherFp254BNa = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `Fp254BNa`,
			BitSize: 254,
			P:       NewGFpModulusFromHex(`2370fb049d410fbe4e761a9886e502417d023f40180000017e80600000000001`),
			A:       ParseGFpHex(``),
			B:       ParseGFpHex(`5`),
			N:       HI(`2370fb049d410fbe4e761a9886e502411dc1af70120000017e80600000000001`),
			Gx:      HI(`1`),
			Gy:      HI(`d45589b158faaf6ab0e4ad38d998e9982e7ff63964ee1460342a592677cccb0`),
		}),
	)
})

// OtherFp254BNa returns the predefined other/Fp254BNa curve.
func OtherFp254BNa() elliptic.Curve { return otherFp254BNa() }

var otherFp256BN = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `Fp256BN`,
			BitSize: 256,
			P:       NewGFpModulusFromHex(`fffffffffffcf0cd46e5f25eee71a49f0cdc65fb12980a82d3292ddbaed33013`),
			A:       ParseGFpHex(``),
			B:       ParseGFpHex(`3`),
			N:       HI(`fffffffffffcf0cd46e5f25eee71a49e0cdc65fb1299921af62d536cd10b500d`),
			Gx:      HI(`1`),
			Gy:      HI(`2`),
		}),
	)
})

// OtherFp256BN returns the predefined other/Fp256BN curve.
func OtherFp256BN() elliptic.Curve { return otherFp256BN() }

var otherFp384BN = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `Fp384BN`,
			BitSize: 384,
			P:       NewGFpModulusFromHex(`fffffffffffffffffff2a96823d5920d2a127e3f6fbca024c8fbe29531892c79534f9d306328261550a7cabd7cccd10b`),
			A:       ParseGFpHex(``),
			B:       ParseGFpHex(`3`),
			N:       HI(`fffffffffffffffffff2a96823d5920d2a127e3f6fbca023c8fbe29531892c795356487d8ac63e4f4db17384341a5775`),
			Gx:      HI(`1`),
			Gy:      HI(`2`),
		}),
	)
})

// OtherFp384BN returns the predefined other/Fp384BN curve.
func OtherFp384BN() elliptic.Curve { return otherFp384BN() }

var otherFp512BN = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `Fp512BN`,
			BitSize: 512,
			P:       NewGFpModulusFromHex(`fffffffffffffffffffffffffff9ec7f01c60ba1d8cb5307c0bbe3c111b0ef455146cf1eacbe98b8e48c65deab236fe1916a55ce5f4c6467b4eb280922adef33`),
			A:       ParseGFpHex(``),
			B:       ParseGFpHex(`3`),
			N:       HI(`fffffffffffffffffffffffffff9ec7f01c60ba1d8cb5307c0bbe3c111b0ef445146cf1eacbe98b8e48c65deab2679a34a10313e04f9a2b406a64a5f519a09ed`),
			Gx:      HI(`1`),
			Gy:      HI(`2`),
		}),
	)
})

// OtherFp512BN returns the predefined other/Fp512BN curve.
func OtherFp512BN() elliptic.Curve { return otherFp512BN() }

var otherJubJub = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		t.Build(&t.CurveParams{
			Name:    `JubJub`,
			BitSize: 255,
			P:       NewGFpModulusFromHex(`73eda753299d7d483339d80809a1d80553bda402fffe5bfeffffffff00000001`),
			A:       ParseGFpHex(`73eda753299d7d483339d80809a1d80553bda402fffe5bfeffffffff00000000`),
			D:       ParseGFpHex(`2a9318e74bfa2b48f5fd9207e6bd7fd4292d7f6d37579d2601065fd6d6343eb1`),
			N:       HI(`e7db4ea6533afa906673b0101343b00a6682093ccc81082d0970e5ed6f72cb7`),
			Gx:      HI(`11dafe5d23e1218086a365b99fbf3d3be72f6afd7d1f72623e6b071492d1122b`),
			Gy:      HI(`1d523cf1ddab1a1793132e78c866c0c33e26ba5cc220fed7cc3f870e59d292aa`),
		}),
	)
})

// OtherJubJub returns the predefined other/JubJub curve.
func OtherJubJub() elliptic.Curve { return otherJubJub() }

var otherM221 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		m.Build(&m.CurveParams{
			Name:    `M-221`,
			BitSize: 221,
			P:       NewGFpModulusFromHex(`1ffffffffffffffffffffffffffffffffffffffffffffffffffffffd`),
			A:       ParseGFpHex(`1c93a`),
			B:       ParseGFpHex(`1`),
			N:       HI(`40000000000000000000000000015a08ed730e8a2f77f005042605b`),
			Gx:      HI(`4`),
			Gy:      HI(`f7acdd2a4939571d1cef14eca37c228e61dbff10707dc6c08c5056d`),
		}),
	)
})

// OtherM221 returns the predefined other/M-221 curve.
func OtherM221() elliptic.Curve { return otherM221() }

var otherM383 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		m.Build(&m.CurveParams{
			Name:    `M-383`,
			BitSize: 383,
			P:       NewGFpModulusFromHex(`7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff45`),
			A:       ParseGFpHex(`1f82fe`),
			B:       ParseGFpHex(`1`),
			N:       HI(`10000000000000000000000000000000000000000000000006c79673ac36ba6e7a32576f7b1b249e46bbc225be9071d7`),
			Gx:      HI(`c`),
			Gy:      HI(`1ec7ed04aaf834af310e304b2da0f328e7c165f0e8988abd3992861290f617aa1f1b2e7d0b6e332e969991b62555e77e`),
		}),
	)
})

// OtherM383 returns the predefined other/M-383 curve.
func OtherM383() elliptic.Curve { return otherM383() }

var otherM511 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		m.Build(&m.CurveParams{
			Name:    `M-511`,
			BitSize: 511,
			P:       NewGFpModulusFromHex(`7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff45`),
			A:       ParseGFpHex(`81806`),
			B:       ParseGFpHex(`1`),
			N:       HI(`100000000000000000000000000000000000000000000000000000000000000017b5feff30c7f5677ab2aeebd13779a2ac125042a6aa10bfa54c15bab76baf1b`),
			Gx:      HI(`5`),
			Gy:      HI(`2fbdc0ad8530803d28fdbad354bb488d32399ac1cf8f6e01ee3f96389b90c809422b9429e8a43dbf49308ac4455940abe9f1dbca542093a895e30a64af056fa5`),
		}),
	)
})

// OtherM511 returns the predefined other/M-511 curve.
func OtherM511() elliptic.Curve { return otherM511() }

var otherMDC201601 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		e.Build(&e.CurveParams{
			Name:    `MDC201601`,
			BitSize: 256,
			P:       NewGFpModulusFromHex(`f13b68b9d456afb4532f92fdd7a5fd4f086a9037ef07af9ec13710405779ec13`),
			C:       ParseGFpHex(`1`),
			D:       ParseGFpHex(`571304521965b68a7cdfbfccfb0cb9625f1270f63f21f041ee9309250300cf89`),
			N:       HI(`3c4eda2e7515abed14cbe4bf75e97f534fb38975faf974bb588552f421b0f7fb`),
			Gx:      HI(`b681886a7f903b83d85b421e03cbcf6350d72abb8d2713e2232c25bfee68363b`),
			Gy:      HI(`ca6734e1b59c0b0359814dcf6563da421da8bc3d81a93a3a7e73c355bd2864b5`),
		}),
	)
})

// OtherMDC201601 returns the predefined other/MDC201601 curve.
func OtherMDC201601() elliptic.Curve { return otherMDC201601() }

var otherPallas = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `Pallas`,
			BitSize: 255,
			P:       NewGFpModulusFromHex(`40000000000000000000000000000000224698fc094cf91b992d30ed00000001`),
			A:       ParseGFpHex(``),
			B:       ParseGFpHex(`5`),
			N:       HI(`40000000000000000000000000000000224698fc0994a8dd8c46eb2100000001`),
			Gx:      HI(`40000000000000000000000000000000224698fc094cf91b992d30ed00000000`),
			Gy:      HI(`2`),
		}),
	)
})

// OtherPallas returns the predefined other/Pallas curve.
func OtherPallas() elliptic.Curve { return otherPallas() }

var otherSsc160 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `ssc-160`,
			BitSize: 160,
			P:       NewGFpModulusFromHex(`c90fdaa22168c234c4c6628b80dc1cd129024e1f`),
			A:       ParseGFpHex(`c90fdaa22168c234c4c6628b80dc1cd129024e1c`),
			B:       ParseGFpHex(`adf85458a2bb4a9aafdc5620273d3cf1d8b9c841`),
			N:       HI(`c90fdaa22168c234c4c5d89f4f2dd72349ee61f7`),
		}),
	)
})

// OtherSsc160 returns the predefined other/ssc-160 curve.
func OtherSsc160() elliptic.Curve { return otherSsc160() }

var otherSsc192 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `ssc-192`,
			BitSize: 192,
			P:       NewGFpModulusFromHex(`c90fdaa22168c234c4c6628b80dc1cd129024e088a67cd13`),
			A:       ParseGFpHex(`c90fdaa22168c234c4c6628b80dc1cd129024e088a67cd10`),
			B:       ParseGFpHex(`adf85458a2bb4a9aafdc5620273d3cf1d8b9c583ce2d36a6`),
			N:       HI(`c90fdaa22168c234c4c6628c5dca19490dd3e6fd7979a7a3`),
		}),
	)
})

// OtherSsc192 returns the predefined other/ssc-192 curve.
func OtherSsc192() elliptic.Curve { return otherSsc192() }

var otherSsc224 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `ssc-224`,
			BitSize: 224,
			P:       NewGFpModulusFromHex(`c90fdaa22168c234c4c6628b80dc1cd129024e088a67cc74020bbedf`),
			A:       ParseGFpHex(`c90fdaa22168c234c4c6628b80dc1cd129024e088a67cc74020bbedc`),
			B:       ParseGFpHex(`adf85458a2bb4a9aafdc5620273d3cf1d8b9c583ce2d3695a9e13a03`),
			N:       HI(`c90fdaa22168c234c4c6628b80dd2439be5b2b827a9ffbea7240e5cd`),
		}),
	)
})

// OtherSsc224 returns the predefined other/ssc-224 curve.
func OtherSsc224() elliptic.Curve { return otherSsc224() }

var otherSsc256 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `ssc-256`,
			BitSize: 256,
			P:       NewGFpModulusFromHex(`c90fdaa22168c234c4c6628b80dc1cd129024e088a67cc74020bbea63b139c0b`),
			A:       ParseGFpHex(`c90fdaa22168c234c4c6628b80dc1cd129024e088a67cc74020bbea63b139c08`),
			B:       ParseGFpHex(`adf85458a2bb4a9aafdc5620273d3cf1d8b9c583ce2d3695a9e13641146434e1`),
			N:       HI(`c90fdaa22168c234c4c6628b80dc1cd0fbec42e940b37a88d9caeca198a64437`),
		}),
	)
})

// OtherSsc256 returns the predefined other/ssc-256 curve.
func OtherSsc256() elliptic.Curve { return otherSsc256() }

var otherSsc288 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `ssc-288`,
			BitSize: 288,
			P:       NewGFpModulusFromHex(`c90fdaa22168c234c4c6628b80dc1cd129024e088a67cc74020bbea63b139b22514a098b`),
			A:       ParseGFpHex(`c90fdaa22168c234c4c6628b80dc1cd129024e088a67cc74020bbea63b139b22514a0988`),
			B:       ParseGFpHex(`adf85458a2bb4a9aafdc5620273d3cf1d8b9c583ce2d3695a9e13641146433fbcc939f36`),
			N:       HI(`c90fdaa22168c234c4c6628b80dc1cd12903ba214366757b7a5240b2a637e2065a850855`),
		}),
	)
})

// OtherSsc288 returns the predefined other/ssc-288 curve.
func OtherSsc288() elliptic.Curve { return otherSsc288() }

var otherSsc320 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `ssc-320`,
			BitSize: 320,
			P:       NewGFpModulusFromHex(`c90fdaa22168c234c4c6628b80dc1cd129024e088a67cc74020bbea63b139b22514a08798e3408b3`),
			A:       ParseGFpHex(`c90fdaa22168c234c4c6628b80dc1cd129024e088a67cc74020bbea63b139b22514a08798e3408b0`),
			B:       ParseGFpHex(`adf85458a2bb4a9aafdc5620273d3cf1d8b9c583ce2d3695a9e13641146433fbcc939dce249b40a4`),
			N:       HI(`c90fdaa22168c234c4c6628b80dc1cd129024e09489bd44fda941042cccc7286009777663bb29671`),
		}),
	)
})

// OtherSsc320 returns the predefined other/ssc-320 curve.
func OtherSsc320() elliptic.Curve { return otherSsc320() }

var otherSsc384 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `ssc-384`,
			BitSize: 384,
			P:       NewGFpModulusFromHex(`c90fdaa22168c234c4c6628b80dc1cd129024e088a67cc74020bbea63b139b22514a08798e3404ddef9519b3cd3a437b`),
			A:       ParseGFpHex(`c90fdaa22168c234c4c6628b80dc1cd129024e088a67cc74020bbea63b139b22514a08798e3404ddef9519b3cd3a4378`),
			B:       ParseGFpHex(`adf85458a2bb4a9aafdc5620273d3cf1d8b9c583ce2d3695a9e13641146433fbcc939dce249b3ef97d2fe363630c7791`),
			N:       HI(`c90fdaa22168c234c4c6628b80dc1cd129024e088a67cc73b7669162524b60c73ee73e6dfe7059f510370fe7870d8599`),
		}),
	)
})

// OtherSsc384 returns the predefined other/ssc-384 curve.
func OtherSsc384() elliptic.Curve { return otherSsc384() }

var otherSsc512 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `ssc-512`,
			BitSize: 512,
			P:       NewGFpModulusFromHex(`c90fdaa22168c234c4c6628b80dc1cd129024e088a67cc74020bbea63b139b22514a08798e3404ddef9519b3cd3a431b302b0a6df25f14374fe1356d6d51c5ef`),
			A:       ParseGFpHex(`c90fdaa22168c234c4c6628b80dc1cd129024e088a67cc74020bbea63b139b22514a08798e3404ddef9519b3cd3a431b302b0a6df25f14374fe1356d6d51c5ec`),
			B:       ParseGFpHex(`adf85458a2bb4a9aafdc5620273d3cf1d8b9c583ce2d3695a9e13641146433fbcc939dce249b3ef97d2fe363630c75d8f681b202aec4617ad3df1ed5d5fd6a8d`),
			N:       HI(`c90fdaa22168c234c4c6628b80dc1cd129024e088a67cc74020bbea63b139b235a2359c4afbc9eb7987f1c9ab37e42599188c4b7dc6269b830d80897f57a5f71`),
		}),
	)
})

// OtherSsc512 returns the predefined other/ssc-512 curve.
func OtherSsc512() elliptic.Curve { return otherSsc512() }

var otherTom256 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `Tom-256`,
			BitSize: 256,
			P:       NewGFpModulusFromHex(`ffffffff0000000100000000000000017e72b42b30e7317793135661b1c4b117`),
			A:       ParseGFpHex(`ffffffff0000000100000000000000017e72b42b30e7317793135661b1c4b114`),
			B:       ParseGFpHex(`b441071b12f4a0366fb552f8e21ed4ac36b06aceeb354224863e60f20219fc56`),
			N:       HI(`ffffffff00000001000000000000000000000000ffffffffffffffffffffffff`),
			Gx:      HI(`3`),
			Gy:      HI(`5a6dd32df58708e64e97345cbe66600decd9d538a351bb3c30b4954925b1f02d`),
		}),
	)
})

// OtherTom256 returns the predefined other/Tom-256 curve.
func OtherTom256() elliptic.Curve { return otherTom256() }

var otherTom384 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `Tom-384`,
			BitSize: 384,
			P:       NewGFpModulusFromHex(`fffffffffffffffffffffffffffffffffffffffffffffffeaf5f689f8669fb41b08d5f5edffd26599c434bbd978917c5`),
			A:       ParseGFpHex(`821dfdc940e7f074ac481f8b2870c48962cce56abd72dfc42813a944cea15df78dc0a2d97fbf031ed26c9076826940ba`),
			B:       ParseGFpHex(`9b5b584b655fdcb087d37f8c4fee893c0499223db5e004c674ea0dee48a4ec0c9e9f684099f2a51c62a2cce400cb1e4b`),
			N:       HI(`fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeffffffff0000000000000000ffffffff`),
		}),
	)
})

// OtherTom384 returns the predefined other/Tom-384 curve.
func OtherTom384() elliptic.Curve { return otherTom384() }

var otherTom521 = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `Tom-521`,
			BitSize: 521,
			P:       NewGFpModulusFromHex(`200000000000000000000000000000000000000000000000000000000000000002c54be78524c33584f734a266748b2063accf5028e6778dc5056476d0690853249`),
			A:       ParseGFpHex(`ef6432c21701cc48c63fb9263e14ba76d4a94ba14d173b134e3032b0e2e543180eb6725125992a7d00162a5f57d21918b0766364eeb53c53bb12f405dac1d527e2`),
			B:       ParseGFpHex(`3cbc65d1e0245d79703b18e9aaea1ac6d67f87a2cd4bd84b9e6df6a45a979c481825ca5a857270fc890352f9fac7fd6020deaabb28d099718f0f77a4eec222871d`),
			N:       HI(`1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff`),
		}),
	)
})

// OtherTom521 returns the predefined other/Tom-521 curve.
func OtherTom521() elliptic.Curve { return otherTom521() }

var otherTweedledee = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `Tweedledee`,
			BitSize: 255,
			P:       NewGFpModulusFromHex(`40000000000000000000000000000000038aa127696286c9842cafd400000001`),
			A:       ParseGFpHex(``),
			B:       ParseGFpHex(`5`),
			N:       HI(`40000000000000000000000000000000038aa1276c3f59b9a14064e200000001`),
			Gx:      HI(`40000000000000000000000000000000038aa127696286c9842cafd400000000`),
			Gy:      HI(`2`),
		}),
	)
})

// OtherTweedledee returns the predefined other/Tweedledee curve.
func OtherTweedledee() elliptic.Curve { return otherTweedledee() }

var otherTweedledum = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `Tweedledum`,
			BitSize: 255,
			P:       NewGFpModulusFromHex(`40000000000000000000000000000000038aa1276c3f59b9a14064e200000001`),
			A:       ParseGFpHex(``),
			B:       ParseGFpHex(`5`),
			N:       HI(`40000000000000000000000000000000038aa127696286c9842cafd400000001`),
			Gx:      HI(`40000000000000000000000000000000038aa1276c3f59b9a14064e200000000`),
			Gy:      HI(`2`),
		}),
	)
})

// OtherTweedledum returns the predefined other/Tweedledum curve.
func OtherTweedledum() elliptic.Curve { return otherTweedledum() }

var otherVesta = sync.OnceValue(func() elliptic.Curve {
	return NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `Vesta`,
			BitSize: 255,
			P:       NewGFpModulusFromHex(`40000000000000000000000000000000224698fc0994a8dd8c46eb2100000001`),
			A:       ParseGFpHex(``),
			B:       ParseGFpHex(`5`),
			N:       HI(`40000000000000000000000000000000224698fc094cf91b992d30ed00000001`),
			Gx:      HI(`40000000000000000000000000000000224698fc0994a8dd8c46eb2100000000`),
			Gy:      HI(`2`),
		}),
	)
})

// OtherVesta returns the predefined other/Vesta curve.
func OtherVesta() elliptic.Curve { return otherVesta() }
