from __future__ import annotations

import csv
import hashlib
import io
import json
import re
import shutil
import subprocess
from dataclasses import dataclass
from multiprocessing import cpu_count
from multiprocessing.pool import Pool
from pathlib import Path
from typing import Any, Final, TypedDict, cast

import docker
import docker.errors
import tqdm
from git import Repo
from jinja2 import Environment, FileSystemLoader
from type_sage import (
    BinaryCurveParams,
    EdwardsCurveParams,
    GeneratedTestCases,
    IgnoredCurve,
    MontgomeryCurveParams,
    TwistedEdwardsCurveParams,
    UnifiedCurve,
    UnifiedNamespace,
    WeierstrassBinaryCurveParams,
    WeierstrassPrimeCurveParams,
)
from type_std import (
    CurveTypes,
    GitCurve,
    GitDocument,
    GitFieldBinaryPoly,
    GitFieldPrime,
    GitRaw,
    UnsupportedCurveTypeError,
)

STD_CURVES_REPO: Final = "https://github.com/J08nY/std-curves.git"
STD_CURVES_DIR: Final = Path("std-curves")

TEMPLATE_DIR: Final = Path(__file__).parent / "templates"

SAGE_FILE: Final = "main_sage.py"
SAGEMATH_DOCKER_IMAGE: Final = "sagemath/sagemath:10.7"

CACHE_DIR: Final = Path(".cache")

MARKDOWN_START: Final = "<!-- curves start -->"
MARKDOWN_END: Final = "<!-- curves end -->"

# CSV 파일 경로 및 헤더 정의
CURVE_PARAMS_CSV: Final[
    dict[
        CurveTypes,
        tuple[
            str,  # CSV 파일명
            list[str],  # 전체 헤더
            list[str],  # 원본 유지할 헤더
            tuple[str, list[str]],  # (prime, 축약할 헤더)
        ],
    ]
] = {
    CurveTypes.WEIERSTRASS_BINARY_POLY: (
        "params_weierstrass_binary_poly.csv",
        ["namespace", "name", "bits", "fx", "a2", "a6", "n", "h", "gx", "gy"],
        ["namespace", "name", "bits"],
        ("", []),
    ),
    CurveTypes.WEIERSTRASS_PRIME: (
        "params_weierstrass_prime.csv",
        ["namespace", "name", "bits", "p", "a", "b", "n", "h", "gx", "gy"],
        ["namespace", "name", "bits"],
        ("p", ["a", "b"]),
    ),
    CurveTypes.MONTGOMERY_PRIME: (
        "params_montgomery.csv",
        ["namespace", "name", "bits", "p", "a", "b", "n", "h", "gx", "gy"],
        ["namespace", "name", "bits"],
        ("p", ["a", "b"]),
    ),
    CurveTypes.TWISTEDEDWARDS_PRIME: (
        "params_twistededwards.csv",
        ["namespace", "name", "bits", "p", "a", "d", "n", "h", "gx", "gy"],
        ["namespace", "name", "bits"],
        ("p", ["a", "d"]),
    ),
    CurveTypes.EDWARDS_PRIME: (
        "params_edwards.csv",
        ["namespace", "name", "bits", "p", "c", "d", "n", "h", "gx", "gy"],
        ["namespace", "name", "bits"],
        ("p", ["c", "d"]),
    ),
}

reDockerInvalidChar: Final = re.compile(r"[^a-zA-Z0-9_.-]")


class Jinja2Context(TypedDict):
    namespace: str
    name: str
    desc: str
    any_weierstrass_binary: bool
    any_weierstrass_prime: bool
    any_montgomery: bool
    any_twistededwards: bool
    any_edwards: bool
    curve_list: list[Jinja2Curve]
    ignored_curve_list: list[IgnoredCurve]


class Jinja2Curve(TypedDict):
    golang_var: str
    golang_fun: str
    unified_curve: UnifiedCurve
    f_arg: str | None
    f_str: str | None
    testcase: GeneratedTestCases
    has_generator: bool
    field_type: str


class AliasTestCurve(TypedDict):
    name: str
    curve_expr: str
    oid: str


@dataclass
class CurveEntry:
    namespace: UnifiedNamespace
    curve: Jinja2Curve
    fullname: str
    parameter_key: tuple[Any, ...]
    parameter_hash: int
    internal_name: str


@dataclass
class CurveCatalog:
    entries: dict[str, CurveEntry]
    families: list[list[CurveEntry]]
    canonical_by_key: dict[tuple[Any, ...], CurveEntry]
    target_by_fullname: dict[str, CurveEntry]
    variants: list[CurveEntry]


CANONICAL_NAMESPACE_PRIORITY: Final = {
    "nist": 0,
    "secg": 1,
    "x962": 2,
    "x963": 3,
}

# "<namespace>/<curve>": ("<Go std elliptic curve>", "<OID>")
GO_STD_CURVES: Final[dict[str, tuple[str, str]]] = {
    "nist/P-224": ("P224", "1.3.132.0.33"),
    "nist/P-256": ("P256", "1.2.840.10045.3.1.7"),
    "nist/P-384": ("P384", "1.3.132.0.34"),
    "nist/P-521": ("P521", "1.3.132.0.35"),
}

GENERATED_HEADER: Final = "// Code generated by curve_generator. DO NOT EDIT."


def load_document(fp) -> GitDocument:
    return json.loads(fp)


def capitalize(s: str) -> str:
    if len(s) == 0:
        return ""
    if len(s) == 1:
        return s.upper()
    return s[0].upper() + s[1:]


def to_golang_function_name(namespace: str, name: str) -> str:
    # 숫자로 시작하는 경우 namespace 접두사 추가
    if re.match(r"^\d", name):
        name = capitalize_part(namespace) + name

    # 슬래시 -> 언더스코어
    name = name.replace("/", "_")

    # 숫자-숫자 -> 숫자_숫자
    name = re.sub(r"(\d)-(\d)", r"\1_\2", name)

    # 하이픈, 공백 기준으로 분리 후 PascalCase 변환
    parts = re.split(r"[-\s]+", name)
    name = "".join(capitalize_part(part) for part in parts if part)

    # 영문자/숫자/언더스코어 외 문자 제거
    name = re.sub(r"[^a-zA-Z0-9_]", "", name)

    # print(oname, "->", name)
    return name


def noncapitalize_part(s: str) -> str:
    """첫 글자만 소문자 보장, 나머지 원본 유지."""
    if not s:
        return s
    return s[0].lower() + s[1:]


def capitalize_part(s: str) -> str:
    """첫 글자만 대문자 보장, 나머지 원본 유지."""
    if not s:
        return s
    return s[0].upper() + s[1:]


def to_fullname(doc: UnifiedNamespace, curve: UnifiedCurve) -> str:
    return f"{doc['name']}/{curve['name']}"


def build(
    namespace_list: list[UnifiedNamespace],
    remove_docker_container: bool = True,
) -> None:
    contexts = [
        context
        for namespace in namespace_list
        if (
            context := prepare_namespace(
                namespace,
                rm=remove_docker_container,
            )
        )
        is not None
    ]
    catalog = build_curve_catalog(contexts)
    env = create_jinja_environment()

    for curve_type, (csv_filename, headers, _, _) in CURVE_PARAMS_CSV.items():
        write_template(
            Path("..", "..") / csv_filename,
            env,
            "curve_params.csv.j2",
            {"rows": [headers, *curve_params_rows(contexts, curve_type)]},
            normalize_trailing_newline=False,
        )

    readme_content_list: list[str] = []
    for context in contexts:
        namespace = context["namespace"]
        output_dir = Path("..", "..", namespace)
        output_dir.mkdir(parents=True, exist_ok=True)

        write_template(
            output_dir / f"{namespace}.go",
            env,
            "_/namespace.go.j2",
            {
                **context,
                "target_by_fullname": catalog.target_by_fullname,
            },
        )
        remove_generated(output_dir / f"{namespace}_curve.go")
        remove_generated(output_dir / f"{namespace}_test.go")

        readme_content_list.append(env.get_template("README.md.j2").render(context))

    generate_curves(catalog, env)
    write_template(
        Path("..", "..", "alias_test.go"),
        env,
        "alias_test.go.j2",
        alias_test_context(catalog),
    )
    generated_go = [
        Path("..", "..", "alias.go"),
        Path("..", "..", "alias_test.go"),
    ]
    generated_go.extend(
        Path("..", "..", context["namespace"], f"{context['namespace']}.go")
        for context in contexts
    )
    generated_go.extend(Path("..", "..", "internal", "curves").glob("*.go"))
    generated_go.append(Path("..", "..", "internal", "curves", "oids", "oids.go"))
    format_generated_go(generated_go)

    readme_path = Path("..", "..", "README.md")
    readme = readme_path.read_text(encoding="utf-8")
    prefix = readme.split(MARKDOWN_START)[0]
    suffix = readme.split(MARKDOWN_END)[1]
    write_template(
        readme_path,
        env,
        "README.generated.md.j2",
        {
            "prefix": prefix,
            "suffix": suffix,
            "markdown_start": MARKDOWN_START,
            "markdown_end": MARKDOWN_END,
            "sections": readme_content_list,
        },
        normalize_trailing_newline=False,
    )


def format_str(input: str | int | None) -> str | None:
    return (
        (
            input[2:]
            if isinstance(input, str) and input.startswith("0x")
            else (hex(input)[2:] if isinstance(input, int) else input)
        )
        if input is not None
        else None
    )


def trim0x(input: str | None) -> str | None:
    if input is None:
        return None
    if input.startswith("-0x"):
        return "-" + (input[3:].lstrip("0") or "")
    if input.startswith("0x"):
        return input[2:].lstrip("0") or ""
    return input.lstrip("0") or ""


def to_hex(input: str | int | None) -> str | None:
    if input is None:
        return None
    if isinstance(input, int):
        return trim0x(hex(input))
    return trim0x(input)


def create_jinja_environment() -> Environment:
    env = Environment(loader=FileSystemLoader(TEMPLATE_DIR), keep_trailing_newline=True)
    env.filters["surround"] = lambda input, c: (
        [f"{c}{i}{c}" for i in input] if isinstance(input, list) else f"{c}{input}{c}"
    )
    env.filters["join"] = lambda input, sep: sep.join(
        [input] if not isinstance(input, list) else input
    )
    env.filters["to_hex"] = to_hex
    env.filters["trim0x"] = trim0x
    env.filters["noncapitalize"] = noncapitalize_part
    env.filters["go_string"] = lambda value: json.dumps(value, ensure_ascii=False)
    env.filters["csv_row"] = render_csv_row
    return env


def render_csv_row(values: list[Any]) -> str:
    output = io.StringIO(newline="")
    csv.writer(output, lineterminator="\r\n").writerow(values)
    return output.getvalue()


def write_template(
    path: Path,
    env: Environment,
    template_name: str,
    context: dict[str, Any],
    *,
    normalize_trailing_newline: bool = True,
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    content = env.get_template(template_name).render(context)
    if normalize_trailing_newline:
        content = content.rstrip() + "\n"
    path.write_text(content, encoding="utf-8", newline="")


def remove_generated(path: Path) -> None:
    if not path.exists():
        return
    with path.open("r", encoding="utf-8") as fs:
        if fs.readline().strip() != GENERATED_HEADER:
            raise RuntimeError(f"Refusing to remove non-generated file: {path}")
    path.unlink()


def format_generated_go(paths: list[Path]) -> None:
    gofmt = shutil.which("gofmt")
    if gofmt is None:
        raise RuntimeError("gofmt is required to format generated Go code")
    subprocess.run([gofmt, "-w", *(str(path) for path in paths)], check=True)

    goimports = shutil.which("goimports")
    if goimports is None:
        raise RuntimeError("goimports is required to format generated Go code")
    subprocess.run([goimports, "-w", *(str(path) for path in paths)], check=True)


def pull_image_with_progress(image: str) -> None:
    docker_client = docker.DockerClient()

    try:
        docker_client.images.get(image)  # Check if the image is already present
        return
    except docker.errors.ImageNotFound:
        pass  # Image not found, proceed to pull

    bars: dict[str, tqdm.tqdm] = {}

    for line in docker_client.api.pull(image, stream=True, decode=True):
        layer_id: str | None = line.get("id")
        status: str = line.get("status", "")
        detail: dict[str, Any] = line.get("progressDetail", {})
        current: int | None = detail.get("current")
        total: int | None = detail.get("total")

        if layer_id is None:
            continue

        if layer_id not in bars:
            bars[layer_id] = tqdm.tqdm(
                total=total, desc=f"{layer_id} {status}", unit="B", unit_scale=True
            )

        bar = bars[layer_id]

        if total and bar.total != total:
            bar.total = total

        if current is not None:
            bar.n = current
            bar.set_description(f"{layer_id} {status}")
            bar.refresh()

        if status in ("Pull complete", "Already exists"):
            bar.n = bar.total or bar.n
            bar.refresh()
            bar.close()

    for bar in bars.values():
        if not bar.disable:
            bar.close()


def prepare_namespace(ns: UnifiedNamespace, rm: bool) -> Jinja2Context | None:
    namespace: str = ns["namespace"]
    testcases: dict[str, GeneratedTestCases] = {}
    non_cached: list[UnifiedCurve] = []

    for curve in ns["curve_list"]:
        tmpdir = CACHE_DIR / namespace / curve["name"].replace("/", "_")
        result_file = Path(tmpdir) / "output" / "result.json"

        if not result_file.exists():
            non_cached.append(curve)
            continue

        with result_file.open("r", encoding="utf-8") as fs:
            testcases[curve["name"]] = json.load(fs)

    if len(non_cached) > 0:
        print(
            f"Pulling Docker image {SAGEMATH_DOCKER_IMAGE} for SageMath test case generation..."
        )
        pull_image_with_progress(SAGEMATH_DOCKER_IMAGE)

        print(
            f"Generating test cases for {len(non_cached)} curves: {', '.join(f'{namespace}/{c["name"]}' for c in non_cached)}"
        )
        with Pool(max(1, cpu_count() - 2)) as pool:
            results = list(
                pool.starmap(
                    generate_testcase,
                    tqdm.tqdm(
                        [(namespace, curve, rm) for curve in non_cached],
                        total=len(non_cached),
                        desc=f"{namespace}",
                    ),
                )
            )

        testcases.update(
            {
                curve_name: testcase
                for curve_name, testcase in results
                if testcase is not None
            }
        )

    curve_list: list[Jinja2Curve] = []
    for curve in ns["curve_list"]:
        if curve["name"] not in testcases:
            print(
                f"Skipping curve {namespace}/{curve['name']} due to missing test case"
            )
            continue

        f_arg, f_str = None, None

        field_type = "prime field"
        bfp = cast(BinaryCurveParams, curve["params"])
        if bfp.get("fx") is not None:
            f_powers = bfp["fx"]

            f_arg = ", ".join(f"{poly}" for poly in f_powers)
            f_str = "f(x) = " + " + ".join(
                f"2^{poly}" if poly > 1 else "1" for poly in f_powers
            )

            field_type = "binary field"

        gx = (curve.get("params") or {}).get("gx")
        gy = (curve.get("params") or {}).get("gy")

        curve_info: Jinja2Curve = {
            "golang_var": noncapitalize_part(
                to_golang_function_name(namespace, curve["name"])
            ),
            "golang_fun": to_golang_function_name(namespace, curve["name"]),
            "unified_curve": curve,
            "testcase": testcases[curve["name"]],
            "has_generator": gx is not None and gy is not None,
            "f_arg": f_arg,
            "f_str": f_str,
            "field_type": field_type,
        }
        curve_list.append(curve_info)

    if len(curve_list) == 0:
        return None

    context: Jinja2Context = {
        "namespace": namespace,
        "name": ns["name"],
        "desc": ns["desc"],
        "any_weierstrass_binary": any(
            curve["unified_curve"]["type"] == CurveTypes.WEIERSTRASS_BINARY_POLY.value
            for curve in curve_list
        ),
        "any_weierstrass_prime": any(
            curve["unified_curve"]["type"] == CurveTypes.WEIERSTRASS_PRIME.value
            for curve in curve_list
        ),
        "any_montgomery": any(
            curve["unified_curve"]["type"] == CurveTypes.MONTGOMERY_PRIME.value
            for curve in curve_list
        ),
        "any_twistededwards": any(
            curve["unified_curve"]["type"] == CurveTypes.TWISTEDEDWARDS_PRIME.value
            for curve in curve_list
        ),
        "any_edwards": any(
            curve["unified_curve"]["type"] == CurveTypes.EDWARDS_PRIME.value
            for curve in curve_list
        ),
        "curve_list": sorted(curve_list, key=lambda x: x["unified_curve"]["name"]),
        "ignored_curve_list": ns["ignored_curve_list"],
    }

    return context


def curve_params_rows(
    contexts: list[Jinja2Context],
    curve_type: CurveTypes,
) -> list[list[Any]]:
    _, csv_header, keep_plains, (p_name, minify) = CURVE_PARAMS_CSV[curve_type]
    rows: list[list[Any]] = []

    for context in contexts:
        for curve in context["curve_list"]:
            if curve["unified_curve"]["type"] != curve_type.value:
                continue

            params = cast(dict[str, Any], curve["unified_curve"]["params"].copy())
            params["namespace"] = context["namespace"]
            params["name"] = curve["unified_curve"]["name"]

            p = cast(int, params.get(p_name) if p_name else None)
            for key, value in params.items():
                if isinstance(value, int) and key not in keep_plains:
                    if key in minify and len(hex(value - p)) < len(hex(value)):
                        value -= p
                    params[key] = hex(value)

            rows.append([params[column] for column in csv_header])

    return rows


def curve_parameter_key(curve: UnifiedCurve) -> tuple[Any, ...]:
    curve_type = curve["type"]
    params = cast(dict[str, Any], curve["params"])

    def coefficient(name: str) -> int | None:
        value = cast(int | None, params.get(name))
        p = cast(int | None, params.get("p"))
        if value is not None and p is not None:
            return value % p
        return value

    common = (
        curve_type,
        params.get("bits"),
        params.get("n"),
        params.get("gx"),
        params.get("gy"),
    )
    if curve_type == CurveTypes.WEIERSTRASS_BINARY_POLY.value:
        return common + (
            tuple(sorted(cast(list[int], params["fx"]), reverse=True)),
            params.get("a2"),
            params.get("a6"),
        )
    if curve_type in (
        CurveTypes.WEIERSTRASS_PRIME.value,
        CurveTypes.MONTGOMERY_PRIME.value,
    ):
        return common + (params.get("p"), coefficient("a"), coefficient("b"))
    if curve_type == CurveTypes.TWISTEDEDWARDS_PRIME.value:
        return common + (params.get("p"), coefficient("a"), coefficient("d"))
    if curve_type == CurveTypes.EDWARDS_PRIME.value:
        return common + (params.get("p"), coefficient("c"), coefficient("d"))
    raise ValueError(f"Unsupported curve type: {curve_type}")


def curve_parameter_hash(parameter_key: tuple[Any, ...]) -> int:
    payload = json.dumps(parameter_key, separators=(",", ":"), ensure_ascii=True)
    return int.from_bytes(hashlib.sha256(payload.encode("ascii")).digest()[:8], "big")


def canonical_sort_key(entry: CurveEntry) -> tuple[int, str, str]:
    namespace = entry.namespace["namespace"]
    return (
        CANONICAL_NAMESPACE_PRIORITY.get(namespace, 100),
        namespace,
        entry.curve["unified_curve"]["name"].lower(),
    )


def build_curve_catalog(contexts: list[Jinja2Context]) -> CurveCatalog:
    entries: dict[str, CurveEntry] = {}
    names: set[str] = set()

    for context in contexts:
        namespace = context["namespace"]
        ns: UnifiedNamespace = {
            "namespace": namespace,
            "name": context["name"],
            "desc": context["desc"],
            "curve_list": [c["unified_curve"] for c in context["curve_list"]],
            "ignored_curve_list": context["ignored_curve_list"],
        }
        for curve in context["curve_list"]:
            fullname = f"{namespace}/{curve['unified_curve']['name']}"
            parameter_key = curve_parameter_key(curve["unified_curve"])
            internal_name = capitalize_part(namespace) + curve["golang_fun"]
            if internal_name in names:
                raise ValueError(
                    f"Duplicate internal Go function name: {internal_name}"
                )
            names.add(internal_name)
            entries[fullname] = CurveEntry(
                namespace=ns,
                curve=curve,
                fullname=fullname,
                parameter_key=parameter_key,
                parameter_hash=curve_parameter_hash(parameter_key),
                internal_name=internal_name,
            )

    for entry in entries.values():
        for alias in entry.curve["unified_curve"]["aliases"]:
            target = entries.get(alias)
            if target is not None and target.parameter_key != entry.parameter_key:
                raise ValueError(
                    f"Alias parameters differ: {entry.fullname} and {target.fullname}"
                )

    family_map: dict[tuple[Any, ...], list[CurveEntry]] = {}
    for entry in entries.values():
        family_map.setdefault(entry.parameter_key, []).append(entry)

    families = [
        sorted(family, key=canonical_sort_key) for family in family_map.values()
    ]
    families.sort(key=lambda family: canonical_sort_key(family[0]))
    canonical_by_key = {family[0].parameter_key: family[0] for family in families}

    target_by_fullname: dict[str, CurveEntry] = {}
    variants: list[CurveEntry] = []
    for family in families:
        canonical = family[0]
        oid_groups: dict[str | None, list[CurveEntry]] = {}
        for entry in family:
            oid = cast(str | None, entry.curve["unified_curve"]["params"].get("oid"))
            oid_groups.setdefault(oid, []).append(entry)

        for oid_group in oid_groups.values():
            representative = (
                canonical
                if canonical in oid_group
                else min(oid_group, key=canonical_sort_key)
            )
            variants.append(representative)
            for entry in oid_group:
                target_by_fullname[entry.fullname] = representative

    return CurveCatalog(
        entries=entries,
        families=families,
        canonical_by_key=canonical_by_key,
        target_by_fullname=target_by_fullname,
        variants=sorted(variants, key=canonical_sort_key),
    )


def internal_namespace_context(
    namespace: str,
    definitions: list[CurveEntry],
    aliases: list[CurveEntry],
    catalog: CurveCatalog,
) -> dict[str, Any]:
    curve_types = {entry.curve["unified_curve"]["type"] for entry in definitions}
    accessors = [
        {"entry": entry, "base": entry, "is_definition": True}
        for entry in sorted(definitions, key=lambda item: item.internal_name)
    ]
    accessors.extend(
        {
            "entry": entry,
            "base": catalog.canonical_by_key[entry.parameter_key],
            "is_definition": False,
        }
        for entry in sorted(aliases, key=lambda item: item.internal_name)
    )
    return {
        "namespace": namespace,
        "has_definitions": bool(definitions),
        "any_weierstrass_binary": (
            CurveTypes.WEIERSTRASS_BINARY_POLY.value in curve_types
        ),
        "any_weierstrass_prime": CurveTypes.WEIERSTRASS_PRIME.value in curve_types,
        "any_montgomery": CurveTypes.MONTGOMERY_PRIME.value in curve_types,
        "any_twistededwards": CurveTypes.TWISTEDEDWARDS_PRIME.value in curve_types,
        "any_edwards": CurveTypes.EDWARDS_PRIME.value in curve_types,
        "accessors": accessors,
    }


def internal_test_context(
    namespace: str,
    definitions: list[CurveEntry],
) -> dict[str, Any]:
    curves: list[Jinja2Curve] = []
    for entry in sorted(definitions, key=lambda item: item.internal_name):
        curve = cast(Jinja2Curve, dict(entry.curve))
        curve["golang_fun"] = entry.internal_name
        curves.append(curve)
    return {
        "test_name_prefix": capitalize_part(namespace),
        "variable_prefix": namespace,
        "curve_list": curves,
    }


def generate_curves(
    catalog: CurveCatalog,
    env: Environment,
) -> None:
    workspace_dir: Final = Path("..", "..")

    internal_dir: Final = workspace_dir / "internal" / "curves"
    internal_dir.mkdir(parents=True, exist_ok=True)

    definitions_by_namespace: dict[str, list[CurveEntry]] = {}
    for definition in catalog.canonical_by_key.values():
        definitions_by_namespace.setdefault(
            definition.namespace["namespace"], []
        ).append(definition)

    aliases_by_namespace: dict[str, list[CurveEntry]] = {}
    for variant in catalog.variants:
        if variant is catalog.canonical_by_key[variant.parameter_key]:
            continue
        aliases_by_namespace.setdefault(variant.namespace["namespace"], []).append(
            variant
        )

    namespaces = sorted(set(definitions_by_namespace) | set(aliases_by_namespace))
    expected = {"alias.go", "oid.go", "oid_test.go"}
    expected.update(f"{namespace}.go" for namespace in namespaces)
    expected.update(
        f"{namespace}_test.go"
        for namespace, entries in definitions_by_namespace.items()
        if entries
    )
    for path in internal_dir.glob("*.go"):
        if path.name not in expected:
            remove_generated(path)

    oid_context = internal_oid_context(catalog)
    write_template(
        internal_dir / "oids" / "oids.go",
        env,
        "internal/curves/oids/oids.go.j2",
        oid_context,
    )
    write_template(
        workspace_dir / "oids" / "oid.go",
        env,
        "oids/oid.go.j2",
        oid_context,
    )
    write_template(
        workspace_dir / "oids" / "oid_test.go",
        env,
        "oids/oid_test.go.j2",
        oid_context,
    )

    for namespace in namespaces:
        definitions = definitions_by_namespace.get(namespace, [])
        aliases = aliases_by_namespace.get(namespace, [])
        write_template(
            internal_dir / f"{namespace}.go",
            env,
            "internal/curves/namespace.go.j2",
            internal_namespace_context(namespace, definitions, aliases, catalog),
        )
        if definitions:
            write_template(
                internal_dir / f"{namespace}_test.go",
                env,
                "internal/curves/namespace_test.go.j2",
                internal_test_context(namespace, definitions),
            )


def internal_oid_context(catalog: CurveCatalog) -> dict[str, Any]:
    oid_entries: list[dict[str, Any]] = []
    entries_by_oid: dict[str, CurveEntry] = {}

    for entry in catalog.variants:
        oid = cast(str | None, entry.curve["unified_curve"]["params"].get("oid"))
        if oid is None:
            continue

        previous = entries_by_oid.get(oid)
        if previous is not None:
            raise ValueError(
                f"Duplicate OID {oid}: {previous.fullname} and {entry.fullname}"
            )
        entries_by_oid[oid] = entry

        try:
            oid_arcs = [str(int(arc)) for arc in oid.split(".")]
        except ValueError as ex:
            raise ValueError(f"Invalid OID {oid}: {entry.fullname}") from ex

        oid_entries.append(
            {
                "golang_var": f"OID{entry.internal_name}",
                "golang_fun": entry.internal_name,
                "oid": oid,
                "oid_arcs": oid_arcs,
            }
        )

    return {
        "oid_entries": sorted(oid_entries, key=lambda item: item["golang_var"]),
    }


def alias_test_context(catalog: CurveCatalog) -> dict[str, Any]:
    families: list[list[AliasTestCurve]] = []
    namespaces: set[str] = set()

    for family in catalog.families:
        test_curves: list[AliasTestCurve] = []
        for entry in family:
            oid = cast(
                str | None,
                entry.curve["unified_curve"]["params"].get("oid"),
            )
            test_curves.append(
                {
                    "name": entry.fullname,
                    "curve_expr": (
                        f"{entry.namespace['namespace']}.{entry.curve['golang_fun']}()"
                    ),
                    "oid": oid or "",
                }
            )

            if std_curve := GO_STD_CURVES.get(entry.fullname):
                test_curves.append(
                    {
                        "name": f"crypto/elliptic.{std_curve[0]}",
                        "curve_expr": f"elliptic.{std_curve[0]}()",
                        "oid": std_curve[1],
                    }
                )

        if len(test_curves) > 1:
            families.append(test_curves)
            namespaces.update(entry.namespace["namespace"] for entry in family)

    return {
        "families": families,
        "namespaces": sorted(namespaces),
    }


def generate_testcase(
    namespace: str,
    curve: UnifiedCurve,
    rm: bool,
) -> tuple[str, GeneratedTestCases | None]:

    tmpdir = CACHE_DIR / namespace / curve["name"].replace("/", "_")
    input_json = Path(tmpdir) / "curve.json"
    output_dir = Path(tmpdir) / "output"

    error_file = output_dir / "error.txt"
    result_file = output_dir / "result.json"

    output_dir.mkdir(parents=True, exist_ok=True)

    if error_file.exists():
        error_file.unlink()

    with input_json.open("w", encoding="utf-8") as fs:
        json.dump(curve, fs, indent=2)

    local_dir = Path(".")
    volumes: dict[str, dict[str, str]] = {
        str((local_dir / file.name).absolute()): {
            "bind": f"/input/{file.name}",
            "mode": "ro",
        }
        for file in local_dir.iterdir()
        if file.is_file() and file.suffix == ".py"
    }
    volumes[str(input_json.absolute())] = {"bind": "/input/curve.json", "mode": "ro"}
    volumes[str(output_dir.absolute())] = {"bind": "/output", "mode": "rw"}

    # Docker 컨테이너 실행
    docker_cli: Any = None
    docker_container: Any = None
    try:
        docker_cli = docker.client.DockerClient()

        docker_name = f"ryuanerin-elliptic2-sagegen-{curve['type'].lower()}-{namespace}-{curve['name'].replace('/', '_')}"
        docker_name = reDockerInvalidChar.sub("_", docker_name)

        try:
            docker_cli.containers.get(docker_name).remove(force=True)
        except docker.errors.NotFound:
            pass  # 컨테이너가 존재하지 않으면 무시

        docker_container = docker_cli.containers.run(
            name=docker_name,
            image=SAGEMATH_DOCKER_IMAGE,
            command=["sage", f"/input/{SAGE_FILE}"],
            volumes=volumes,
            cpu_count=1,
            remove=rm,
            detach=True,
        )
        docker_container.wait(timeout=300)

        # 결과 파일 읽기
        if error_file.exists():
            with error_file.open("r", encoding="utf-8") as fs:
                error_msg = fs.read()
            raise RuntimeError(f"SageMath error for {curve['name']}: {error_msg}")

        if not result_file.exists():
            raise RuntimeError(f"Output file not generated for {curve['name']}")

        with result_file.open("r", encoding="utf-8") as fs:
            return curve["name"], json.load(fs)

        # docker_container.stop()
        # docker_container.remove()

    except Exception as ex:  # noqa: BLE001
        print(f"Error generating test case for {namespace} - {curve['name']}: {ex}")
        return curve["name"], None

    finally:
        if docker_cli is not None:
            docker_cli.close()


def unify_document(std: dict[str, GitDocument]) -> list[UnifiedNamespace]:
    ret: list[UnifiedNamespace] = []

    def to_int(x: int | str | GitRaw | None) -> int:
        if x is None:
            raise ValueError("Input cannot be None")
        if isinstance(x, int):
            return x
        if isinstance(x, str):
            if x.startswith("0x"):
                return int(x, 16)
            if x.startswith("-0x"):
                return -int(x[3:], 16)
            return int(x)
        return to_int(x.get("raw", None))

    def to_nullable(x: int | str | GitRaw | None) -> int | None:
        if x is None:
            return None
        if isinstance(x, int):
            return x
        if isinstance(x, str):
            if x.startswith("0x"):
                return int(x, 16)
            if x.startswith("-0x"):
                return -int(x[3:], 16)
            return int(x)
        return to_nullable(x.get("raw", None))

    for namespace, doc in std.items():
        curve_list: list[UnifiedCurve] = []
        ignored_curve_list: list[IgnoredCurve] = []

        def append_ignored_curve(
            curve: GitCurve,
            curve_type: CurveTypes | None,
            reason: str,
            *,
            _target: list[IgnoredCurve] = ignored_curve_list,
        ):
            _target.append(
                {
                    "name": curve["name"],
                    "desc": curve["desc"],
                    "type": curve_type.value if curve_type else "unknown",
                    "aliases": curve.get("aliases") or [],
                    "raw": curve,
                    "reason": reason,
                }
            )

        for std_curve in doc["curves"]:
            try:
                curve_type = CurveTypes.get(std_curve)
            except UnsupportedCurveTypeError as e:
                print(
                    f"Skipping curve {std_curve['name']} in {namespace} due to unsupported type: {e.message}"
                )
                append_ignored_curve(std_curve, None, e.message)
                continue

            a = to_nullable(std_curve.get("params", {}).get("a", None))
            b = to_nullable(std_curve.get("params", {}).get("b", None))
            c = to_nullable(std_curve.get("params", {}).get("c", None))
            d = to_nullable(std_curve.get("params", {}).get("d", None))
            gx = to_nullable((std_curve.get("generator", None) or {}).get("x", None))
            gy = to_nullable((std_curve.get("generator", None) or {}).get("y", None))
            h = to_int(std_curve["cofactor"])
            n = to_int(std_curve["order"])

            """
            if gx is None or gy is None:
                print(
                    f"Skipping curve {std_curve['name']} in {namespace} due to missing generator point"
                )
                append_ignored_curve(std_curve, "has no generator point")
                continue
            """
            if gx is not None and gy is None:
                print(
                    f"Skipping curve {std_curve['name']} in {namespace} due to missing Gy coordinate"
                )
                append_ignored_curve(
                    std_curve, curve_type, "has no generator y coordinate"
                )
                continue
            if gy is not None and gx is None:
                print(
                    f"Skipping curve {std_curve['name']} in {namespace} due to missing Gx coordinate"
                )
                append_ignored_curve(
                    std_curve, curve_type, "has no generator x coordinate"
                )
                continue

            aliases = std_curve.get("aliases") or []

            uc: UnifiedCurve = {
                "type": curve_type.value,
                "name": std_curve["name"],
                "desc": std_curve["desc"],
                "aliases": aliases,
                "raw": std_curve,
                "params": {
                    "n": n,
                },
            }
            oid = std_curve.get("oid", None)
            match curve_type:
                case CurveTypes.WEIERSTRASS_BINARY_POLY:
                    field = cast(GitFieldBinaryPoly, std_curve["field"])
                    cwb: WeierstrassBinaryCurveParams = {
                        "bits": to_int(field["bits"]),
                        "fx": [to_int(poly["power"]) for poly in field["poly"]],
                        "a2": a or 0,
                        "a6": b or 0,
                        "gx": gx,
                        "gy": gy,
                        "h": h,
                        "n": n,
                        "oid": oid,
                    }
                    uc["params"] = cwb

                case CurveTypes.WEIERSTRASS_PRIME:
                    field = cast(GitFieldPrime, std_curve["field"])
                    cwp: WeierstrassPrimeCurveParams = {
                        "bits": to_int(field["bits"]),
                        "p": to_int(field["p"]),
                        "a": a or 0,
                        "b": b or 0,
                        "gx": gx,
                        "gy": gy,
                        "h": h,
                        "n": n,
                        "oid": oid,
                    }
                    uc["params"] = cwp

                case CurveTypes.MONTGOMERY_PRIME:
                    field = cast(GitFieldPrime, std_curve["field"])
                    cm: MontgomeryCurveParams = {
                        "bits": to_int(field["bits"]),
                        "p": to_int(field["p"]),
                        "a": a or 0,
                        "b": b or 0,
                        "gx": gx,
                        "gy": gy,
                        "h": h,
                        "n": n,
                        "oid": oid,
                    }
                    uc["params"] = cm

                case CurveTypes.TWISTEDEDWARDS_PRIME:
                    field = cast(GitFieldPrime, std_curve["field"])
                    cte: TwistedEdwardsCurveParams = {
                        "bits": to_int(field["bits"]),
                        "p": to_int(field["p"]),
                        "a": a or 0,
                        "d": d or 0,
                        "gx": gx,
                        "gy": gy,
                        "h": h,
                        "n": n,
                        "oid": oid,
                    }
                    uc["params"] = cte

                case CurveTypes.EDWARDS_PRIME:
                    field = cast(GitFieldPrime, std_curve["field"])
                    ce: EdwardsCurveParams = {
                        "bits": to_int(field["bits"]),
                        "p": to_int(field["p"]),
                        "c": c or 0,
                        "d": d or 0,
                        "gx": gx,
                        "gy": gy,
                        "h": h,
                        "n": n,
                        "oid": oid,
                    }
                    uc["params"] = ce

            curve_list.append(uc)

        curve_list.sort(key=lambda x: x["name"].lower())
        ignored_curve_list.sort(key=lambda x: x["name"].lower())

        ns: UnifiedNamespace = {
            "name": doc["name"],
            "namespace": namespace,
            "desc": doc["desc"],
            "curve_list": curve_list,
            "ignored_curve_list": ignored_curve_list,
        }
        ret.append(ns)

    ret.sort(key=lambda x: (x["name"] == "other", x["name"]))

    return ret


def read_std_curves(
    git_dir: Path,
    repo_url: str,
    *,
    update: bool = True,
) -> dict[str, GitDocument]:
    std: dict[str, GitDocument] = {}

    if not (git_dir / ".git").exists():
        repo = Repo.clone_from(
            url=repo_url,
            to_path=git_dir,
        )
        repo.git.checkout("data")
    elif update:
        repo = Repo(git_dir)
        repo.git.checkout("data")
        repo.remotes.origin.pull()

    for dir in git_dir.iterdir():
        if not dir.is_dir():
            continue

        curves_json = dir / "curves.json"

        if curves_json.exists():
            print(f"Processing {curves_json}")

            with curves_json.open("r", encoding="utf-8") as fs:
                std[dir.name] = json.load(fs)

    return std


def main():
    import argparse

    parser = argparse.ArgumentParser(description="Generate Go code for elliptic curves")
    parser.add_argument(
        "--std-curves-dir",
        type=str,
        default=str(STD_CURVES_DIR),
        help="Path to the std-curves directory",
    )
    parser.add_argument(
        "--repo-url",
        type=str,
        default=STD_CURVES_REPO,
        help="URL of the std-curves repository",
    )
    parser.add_argument(
        "--clean-cache",
        action="store_true",
        help="Clean the cache directory before generating test cases",
    )
    parser.add_argument(
        "--no-remove-docker-container",
        action="store_true",
        help="Remove the Docker container after generating test cases",
    )
    parser.add_argument(
        "--no-pull",
        action="store_true",
        help="Use the existing std-curves checkout without fetching updates",
    )
    args = parser.parse_args()

    if args.clean_cache and CACHE_DIR.exists():
        print(f"Cleaning cache directory {CACHE_DIR}...")
        shutil.rmtree(CACHE_DIR)
        print(f"Cache directory {CACHE_DIR} has been cleaned.")

    std = read_std_curves(
        git_dir=Path(args.std_curves_dir),
        repo_url=args.repo_url,
        update=not args.no_pull,
    )
    unified_list = unify_document(std)
    build(
        unified_list,
        remove_docker_container=not args.no_remove_docker_container,
    )


# Process all JSON files in the current directory
if __name__ == "__main__":
    main()
