// Code generated by curve_generator. DO NOT EDIT.

/*
package wtls is a collection of named elliptic curves.

Wireless Application Protocol - Wireless Transport Layer Security (WAP-WTLS) curves: <https://www.wapforum.org/tech/documents/WAP-199-WTLS-20000218-a.pdf>

https://neuromancer.sk/std/wtls/
*/
package wtls

import (
	"crypto/elliptic"

	"github.com/RyuaNerin/elliptic2/internal/curves"
)

// WapWsgIdmEcidWtls1 returns a Curve which implements wtls/wap-wsg-idm-ecid-wtls1
// https://neuromancer.sk/std/wtls/wap-wsg-idm-ecid-wtls1
//
// OID: 2.23.43.1.4.1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func WapWsgIdmEcidWtls1() elliptic.Curve {
	return curves.WtlsWapWsgIdmEcidWtls1()
}

// WapWsgIdmEcidWtls10 returns a Curve which implements wtls/wap-wsg-idm-ecid-wtls10
// https://neuromancer.sk/std/wtls/wap-wsg-idm-ecid-wtls10
//
// OID: 2.23.43.1.4.10
// Aliases:
//   - secg/sect233k1
//   - nist/K-233
//   - x963/ansit233k1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func WapWsgIdmEcidWtls10() elliptic.Curve {
	return curves.WtlsWapWsgIdmEcidWtls10()
}

// WapWsgIdmEcidWtls11 returns a Curve which implements wtls/wap-wsg-idm-ecid-wtls11
// https://neuromancer.sk/std/wtls/wap-wsg-idm-ecid-wtls11
//
// OID: 2.23.43.1.4.11
// Aliases:
//   - secg/sect233r1
//   - nist/B-233
//   - x963/ansit233r1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func WapWsgIdmEcidWtls11() elliptic.Curve {
	return curves.WtlsWapWsgIdmEcidWtls11()
}

// WapWsgIdmEcidWtls12 returns a Curve which implements wtls/wap-wsg-idm-ecid-wtls12
// https://neuromancer.sk/std/wtls/wap-wsg-idm-ecid-wtls12
//
// OID: 2.23.43.1.4.12
// Aliases:
//   - secg/secp224r1
//   - nist/P-224
//   - x963/ansip224r1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func WapWsgIdmEcidWtls12() elliptic.Curve {
	return curves.WtlsWapWsgIdmEcidWtls12()
}

// WapWsgIdmEcidWtls3 returns a Curve which implements wtls/wap-wsg-idm-ecid-wtls3
// https://neuromancer.sk/std/wtls/wap-wsg-idm-ecid-wtls3
//
// OID: 2.23.43.1.4.3
// Aliases:
//   - nist/K-163
//   - secg/sect163k1
//   - x963/ansit163k1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func WapWsgIdmEcidWtls3() elliptic.Curve {
	return curves.WtlsWapWsgIdmEcidWtls3()
}

// WapWsgIdmEcidWtls4 returns a Curve which implements wtls/wap-wsg-idm-ecid-wtls4
// https://neuromancer.sk/std/wtls/wap-wsg-idm-ecid-wtls4
//
// OID: 2.23.43.1.4.4
// Aliases:
//   - secg/sect113r1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func WapWsgIdmEcidWtls4() elliptic.Curve {
	return curves.WtlsWapWsgIdmEcidWtls4()
}

// WapWsgIdmEcidWtls5 returns a Curve which implements wtls/wap-wsg-idm-ecid-wtls5
// https://neuromancer.sk/std/wtls/wap-wsg-idm-ecid-wtls5
//
// OID: 2.23.43.1.4.5
// Aliases:
//   - x962/c2pnb163v1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func WapWsgIdmEcidWtls5() elliptic.Curve {
	return curves.WtlsWapWsgIdmEcidWtls5()
}

// WapWsgIdmEcidWtls6 returns a Curve which implements wtls/wap-wsg-idm-ecid-wtls6
// https://neuromancer.sk/std/wtls/wap-wsg-idm-ecid-wtls6
//
// OID: 2.23.43.1.4.6
// Aliases:
//   - secg/secp112r1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func WapWsgIdmEcidWtls6() elliptic.Curve {
	return curves.WtlsWapWsgIdmEcidWtls6()
}

// WapWsgIdmEcidWtls7 returns a Curve which implements wtls/wap-wsg-idm-ecid-wtls7
// https://neuromancer.sk/std/wtls/wap-wsg-idm-ecid-wtls7
//
// OID: 2.23.43.1.4.7
// Aliases:
//   - secg/secp160r1
//   - x963/ansip160r1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func WapWsgIdmEcidWtls7() elliptic.Curve {
	return curves.WtlsWapWsgIdmEcidWtls7()
}

// WapWsgIdmEcidWtls8 returns a Curve which implements wtls/wap-wsg-idm-ecid-wtls8
// https://neuromancer.sk/std/wtls/wap-wsg-idm-ecid-wtls8
//
// OID: 2.23.43.1.4.8
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func WapWsgIdmEcidWtls8() elliptic.Curve {
	return curves.WtlsWapWsgIdmEcidWtls8()
}

// WapWsgIdmEcidWtls9 returns a Curve which implements wtls/wap-wsg-idm-ecid-wtls9
// https://neuromancer.sk/std/wtls/wap-wsg-idm-ecid-wtls9
//
// OID: 2.23.43.1.4.9
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func WapWsgIdmEcidWtls9() elliptic.Curve {
	return curves.WtlsWapWsgIdmEcidWtls9()
}
