// Code generated by curve_generator. DO NOT EDIT.

/*
package wtls is a collection of named elliptic curves.

Wireless Application Protocol - Wireless Transport Layer Security (WAP-WTLS) curves: <https://www.wapforum.org/tech/documents/WAP-199-WTLS-20000218-a.pdf>

https://neuromancer.sk/std/wtls/
*/
package wtls

import (
	"crypto/elliptic"
)

// WapWsgIdmEcidWtls1 returns a Curve which implements wtls/wap-wsg-idm-ecid-wtls1
// https://neuromancer.sk/std/wtls/
//
// OID: 2.23.43.1.4.1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func WapWsgIdmEcidWtls1() elliptic.Curve {
	wapWsgIdmEcidWtls1Once.Do(initWapWsgIdmEcidWtls1)
	return wapWsgIdmEcidWtls1Curve
}

// WapWsgIdmEcidWtls10 returns a Curve which implements wtls/wap-wsg-idm-ecid-wtls10
// https://neuromancer.sk/std/wtls/
//
// OID: 2.23.43.1.4.10
// Aliases:
//   - secg/sect233k1
//   - nist/K-233
//   - x963/ansit233k1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func WapWsgIdmEcidWtls10() elliptic.Curve {
	wapWsgIdmEcidWtls10Once.Do(initWapWsgIdmEcidWtls10)
	return wapWsgIdmEcidWtls10Curve
}

// WapWsgIdmEcidWtls11 returns a Curve which implements wtls/wap-wsg-idm-ecid-wtls11
// https://neuromancer.sk/std/wtls/
//
// OID: 2.23.43.1.4.11
// Aliases:
//   - secg/sect233r1
//   - nist/B-233
//   - x963/ansit233r1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func WapWsgIdmEcidWtls11() elliptic.Curve {
	wapWsgIdmEcidWtls11Once.Do(initWapWsgIdmEcidWtls11)
	return wapWsgIdmEcidWtls11Curve
}

// WapWsgIdmEcidWtls12 returns a Curve which implements wtls/wap-wsg-idm-ecid-wtls12
// https://neuromancer.sk/std/wtls/
//
// OID: 2.23.43.1.4.12
// Aliases:
//   - secg/secp224r1
//   - nist/P-224
//   - x963/ansip224r1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func WapWsgIdmEcidWtls12() elliptic.Curve {
	wapWsgIdmEcidWtls12Once.Do(initWapWsgIdmEcidWtls12)
	return wapWsgIdmEcidWtls12Curve
}

// WapWsgIdmEcidWtls3 returns a Curve which implements wtls/wap-wsg-idm-ecid-wtls3
// https://neuromancer.sk/std/wtls/
//
// OID: 2.23.43.1.4.3
// Aliases:
//   - nist/K-163
//   - secg/sect163k1
//   - x963/ansit163k1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func WapWsgIdmEcidWtls3() elliptic.Curve {
	wapWsgIdmEcidWtls3Once.Do(initWapWsgIdmEcidWtls3)
	return wapWsgIdmEcidWtls3Curve
}

// WapWsgIdmEcidWtls4 returns a Curve which implements wtls/wap-wsg-idm-ecid-wtls4
// https://neuromancer.sk/std/wtls/
//
// OID: 2.23.43.1.4.4
// Aliases:
//   - secg/sect113r1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func WapWsgIdmEcidWtls4() elliptic.Curve {
	wapWsgIdmEcidWtls4Once.Do(initWapWsgIdmEcidWtls4)
	return wapWsgIdmEcidWtls4Curve
}

// WapWsgIdmEcidWtls5 returns a Curve which implements wtls/wap-wsg-idm-ecid-wtls5
// https://neuromancer.sk/std/wtls/
//
// OID: 2.23.43.1.4.5
// Aliases:
//   - x962/c2pnb163v1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func WapWsgIdmEcidWtls5() elliptic.Curve {
	wapWsgIdmEcidWtls5Once.Do(initWapWsgIdmEcidWtls5)
	return wapWsgIdmEcidWtls5Curve
}

// WapWsgIdmEcidWtls6 returns a Curve which implements wtls/wap-wsg-idm-ecid-wtls6
// https://neuromancer.sk/std/wtls/
//
// OID: 2.23.43.1.4.6
// Aliases:
//   - secg/secp112r1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func WapWsgIdmEcidWtls6() elliptic.Curve {
	wapWsgIdmEcidWtls6Once.Do(initWapWsgIdmEcidWtls6)
	return wapWsgIdmEcidWtls6Curve
}

// WapWsgIdmEcidWtls7 returns a Curve which implements wtls/wap-wsg-idm-ecid-wtls7
// https://neuromancer.sk/std/wtls/
//
// OID: 2.23.43.1.4.7
// Aliases:
//   - secg/secp160r1
//   - x963/ansip160r1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func WapWsgIdmEcidWtls7() elliptic.Curve {
	wapWsgIdmEcidWtls7Once.Do(initWapWsgIdmEcidWtls7)
	return wapWsgIdmEcidWtls7Curve
}

// WapWsgIdmEcidWtls8 returns a Curve which implements wtls/wap-wsg-idm-ecid-wtls8
// https://neuromancer.sk/std/wtls/
//
// OID: 2.23.43.1.4.8
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func WapWsgIdmEcidWtls8() elliptic.Curve {
	wapWsgIdmEcidWtls8Once.Do(initWapWsgIdmEcidWtls8)
	return wapWsgIdmEcidWtls8Curve
}

// WapWsgIdmEcidWtls9 returns a Curve which implements wtls/wap-wsg-idm-ecid-wtls9
// https://neuromancer.sk/std/wtls/
//
// OID: 2.23.43.1.4.9
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func WapWsgIdmEcidWtls9() elliptic.Curve {
	wapWsgIdmEcidWtls9Once.Do(initWapWsgIdmEcidWtls9)
	return wapWsgIdmEcidWtls9Curve
}
