// Code generated by curve_generator. DO NOT EDIT.

package wtls

import (
	"crypto/elliptic"
	"sync"

	. "github.com/RyuaNerin/elliptic2/internal"
	. "github.com/RyuaNerin/elliptic2/internal/curve"
	wb "github.com/RyuaNerin/elliptic2/internal/curve/weierstrassbinary"
	wp "github.com/RyuaNerin/elliptic2/internal/curve/weierstrassprime"
	. "github.com/RyuaNerin/elliptic2/internal/field"
)

var (
	wapWsgIdmEcidWtls1Once  sync.Once
	wapWsgIdmEcidWtls10Once sync.Once
	wapWsgIdmEcidWtls11Once sync.Once
	wapWsgIdmEcidWtls12Once sync.Once
	wapWsgIdmEcidWtls3Once  sync.Once
	wapWsgIdmEcidWtls4Once  sync.Once
	wapWsgIdmEcidWtls5Once  sync.Once
	wapWsgIdmEcidWtls6Once  sync.Once
	wapWsgIdmEcidWtls7Once  sync.Once
	wapWsgIdmEcidWtls8Once  sync.Once
	wapWsgIdmEcidWtls9Once  sync.Once

	wapWsgIdmEcidWtls1Curve  elliptic.Curve
	wapWsgIdmEcidWtls10Curve elliptic.Curve
	wapWsgIdmEcidWtls11Curve elliptic.Curve
	wapWsgIdmEcidWtls12Curve elliptic.Curve
	wapWsgIdmEcidWtls3Curve  elliptic.Curve
	wapWsgIdmEcidWtls4Curve  elliptic.Curve
	wapWsgIdmEcidWtls5Curve  elliptic.Curve
	wapWsgIdmEcidWtls6Curve  elliptic.Curve
	wapWsgIdmEcidWtls7Curve  elliptic.Curve
	wapWsgIdmEcidWtls8Curve  elliptic.Curve
	wapWsgIdmEcidWtls9Curve  elliptic.Curve
)

// https://neuromancer.sk/std/wtls/wap-wsg-idm-ecid-wtls1
func initWapWsgIdmEcidWtls1() {
	wapWsgIdmEcidWtls1Curve = NewCurve(
		wb.Build(&wb.CurveParams{
			Name:    `wap-wsg-idm-ecid-wtls1`,
			BitSize: 113,
			Poly:    NewGF2mModulusFromPolynomials(113, 9, 0),
			A2:      ParseGF2mHex(`1`),
			A6:      ParseGF2mHex(`1`),
			N:       HI(`fffffffffffffffdbf91af6dea73`),
			Gx:      HI(`1667979a40ba497e5d5c270780617`),
			Gy:      HI(`f44b4af1ecc2630e08785cebcc15`),
		}),
		WithOID(`2.23.43.1.4.1`),
	)
}

// https://neuromancer.sk/std/wtls/wap-wsg-idm-ecid-wtls10
func initWapWsgIdmEcidWtls10() {
	wapWsgIdmEcidWtls10Curve = NewCurve(
		wb.Build(&wb.CurveParams{
			Name:    `wap-wsg-idm-ecid-wtls10`,
			BitSize: 233,
			Poly:    NewGF2mModulusFromPolynomials(233, 74, 0),
			A2:      ParseGF2mHex(``),
			A6:      ParseGF2mHex(`1`),
			N:       HI(`8000000000000000000000000000069d5bb915bcd46efb1ad5f173abdf`),
			Gx:      HI(`17232ba853a7e731af129f22ff4149563a419c26bf50a4c9d6eefad6126`),
			Gy:      HI(`1db537dece819b7f70f555a67c427a8cd9bf18aeb9b56e0c11056fae6a3`),
		}),
		WithOID(`2.23.43.1.4.10`),
	)
}

// https://neuromancer.sk/std/wtls/wap-wsg-idm-ecid-wtls11
func initWapWsgIdmEcidWtls11() {
	wapWsgIdmEcidWtls11Curve = NewCurve(
		wb.Build(&wb.CurveParams{
			Name:    `wap-wsg-idm-ecid-wtls11`,
			BitSize: 233,
			Poly:    NewGF2mModulusFromPolynomials(233, 74, 0),
			A2:      ParseGF2mHex(`1`),
			A6:      ParseGF2mHex(`66647ede6c332c7f8c0923bb58213b333b20e9ce4281fe115f7d8f90ad`),
			N:       HI(`1000000000000000000000000000013e974e72f8a6922031d2603cfe0d7`),
			Gx:      HI(`fac9dfcbac8313bb2139f1bb755fef65bc391f8b36f8f8eb7371fd558b`),
			Gy:      HI(`1006a08a41903350678e58528bebf8a0beff867a7ca36716f7e01f81052`),
		}),
		WithOID(`2.23.43.1.4.11`),
	)
}

// https://neuromancer.sk/std/wtls/wap-wsg-idm-ecid-wtls12
func initWapWsgIdmEcidWtls12() {
	wapWsgIdmEcidWtls12Curve = NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `wap-wsg-idm-ecid-wtls12`,
			BitSize: 224,
			P:       NewGFpModulusFromHex(`ffffffffffffffffffffffffffffffff000000000000000000000001`),
			A:       ParseGFpHex(`fffffffffffffffffffffffffffffffefffffffffffffffffffffffe`),
			B:       ParseGFpHex(`b4050a850c04b3abf54132565044b0b7d7bfd8ba270b39432355ffb4`),
			N:       HI(`ffffffffffffffffffffffffffff16a2e0b8f03e13dd29455c5c2a3d`),
			Gx:      HI(`b70e0cbd6bb4bf7f321390b94a03c1d356c21122343280d6115c1d21`),
			Gy:      HI(`bd376388b5f723fb4c22dfe6cd4375a05a07476444d5819985007e34`),
		}),
		WithOID(`2.23.43.1.4.12`),
	)
}

// https://neuromancer.sk/std/wtls/wap-wsg-idm-ecid-wtls3
func initWapWsgIdmEcidWtls3() {
	wapWsgIdmEcidWtls3Curve = NewCurve(
		wb.Build(&wb.CurveParams{
			Name:    `wap-wsg-idm-ecid-wtls3`,
			BitSize: 163,
			Poly:    NewGF2mModulusFromPolynomials(163, 7, 6, 3, 0),
			A2:      ParseGF2mHex(`1`),
			A6:      ParseGF2mHex(`1`),
			N:       HI(`4000000000000000000020108a2e0cc0d99f8a5ef`),
			Gx:      HI(`2fe13c0537bbc11acaa07d793de4e6d5e5c94eee8`),
			Gy:      HI(`289070fb05d38ff58321f2e800536d538ccdaa3d9`),
		}),
		WithOID(`2.23.43.1.4.3`),
	)
}

// https://neuromancer.sk/std/wtls/wap-wsg-idm-ecid-wtls4
func initWapWsgIdmEcidWtls4() {
	wapWsgIdmEcidWtls4Curve = NewCurve(
		wb.Build(&wb.CurveParams{
			Name:    `wap-wsg-idm-ecid-wtls4`,
			BitSize: 113,
			Poly:    NewGF2mModulusFromPolynomials(113, 9, 0),
			A2:      ParseGF2mHex(`3088250ca6e7c7fe649ce85820f7`),
			A6:      ParseGF2mHex(`e8bee4d3e2260744188be0e9c723`),
			N:       HI(`100000000000000d9ccec8a39e56f`),
			Gx:      HI(`9d73616f35f4ab1407d73562c10f`),
			Gy:      HI(`a52830277958ee84d1315ed31886`),
		}),
		WithOID(`2.23.43.1.4.4`),
	)
}

// https://neuromancer.sk/std/wtls/wap-wsg-idm-ecid-wtls5
func initWapWsgIdmEcidWtls5() {
	wapWsgIdmEcidWtls5Curve = NewCurve(
		wb.Build(&wb.CurveParams{
			Name:    `wap-wsg-idm-ecid-wtls5`,
			BitSize: 163,
			Poly:    NewGF2mModulusFromPolynomials(163, 8, 2, 1, 0),
			A2:      ParseGF2mHex(`72546b5435234a422e0789675f432c89435de5242`),
			A6:      ParseGF2mHex(`c9517d06d5240d3cff38c74b20b6cd4d6f9dd4d9`),
			N:       HI(`400000000000000000001e60fc8821cc74daeafc1`),
			Gx:      HI(`7af69989546103d79329fcc3d74880f33bbe803cb`),
			Gy:      HI(`1ec23211b5966adea1d3f87f7ea5848aef0b7ca9f`),
		}),
		WithOID(`2.23.43.1.4.5`),
	)
}

// https://neuromancer.sk/std/wtls/wap-wsg-idm-ecid-wtls6
func initWapWsgIdmEcidWtls6() {
	wapWsgIdmEcidWtls6Curve = NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `wap-wsg-idm-ecid-wtls6`,
			BitSize: 112,
			P:       NewGFpModulusFromHex(`db7c2abf62e35e668076bead208b`),
			A:       ParseGFpHex(`db7c2abf62e35e668076bead2088`),
			B:       ParseGFpHex(`659ef8ba043916eede8911702b22`),
			N:       HI(`db7c2abf62e35e7628dfac6561c5`),
			Gx:      HI(`9487239995a5ee76b55f9c2f098`),
			Gy:      HI(`a89ce5af8724c0a23e0e0ff77500`),
		}),
		WithOID(`2.23.43.1.4.6`),
	)
}

// https://neuromancer.sk/std/wtls/wap-wsg-idm-ecid-wtls7
func initWapWsgIdmEcidWtls7() {
	wapWsgIdmEcidWtls7Curve = NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `wap-wsg-idm-ecid-wtls7`,
			BitSize: 160,
			P:       NewGFpModulusFromHex(`ffffffffffffffffffffffffffffffff7fffffff`),
			A:       ParseGFpHex(`ffffffffffffffffffffffffffffffff7ffffffc`),
			B:       ParseGFpHex(`1c97befc54bd7a8b65acf89f81d4d4adc565fa45`),
			N:       HI(`100000000000000000001f4c8f927aed3ca752257`),
			Gx:      HI(`4a96b5688ef573284664698968c38bb913cbfc82`),
			Gy:      HI(`23a628553168947d59dcc912042351377ac5fb32`),
		}),
		WithOID(`2.23.43.1.4.7`),
	)
}

// https://neuromancer.sk/std/wtls/wap-wsg-idm-ecid-wtls8
func initWapWsgIdmEcidWtls8() {
	wapWsgIdmEcidWtls8Curve = NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `wap-wsg-idm-ecid-wtls8`,
			BitSize: 112,
			P:       NewGFpModulusFromHex(`fffffffffffffffffffffffffde7`),
			A:       ParseGFpHex(``),
			B:       ParseGFpHex(`3`),
			N:       HI(`100000000000001ecea551ad837e9`),
			Gx:      HI(`1`),
			Gy:      HI(`2`),
		}),
		WithOID(`2.23.43.1.4.8`),
	)
}

// https://neuromancer.sk/std/wtls/wap-wsg-idm-ecid-wtls9
func initWapWsgIdmEcidWtls9() {
	wapWsgIdmEcidWtls9Curve = NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `wap-wsg-idm-ecid-wtls9`,
			BitSize: 160,
			P:       NewGFpModulusFromHex(`fffffffffffffffffffffffffffffffffffc808f`),
			A:       ParseGFpHex(``),
			B:       ParseGFpHex(`3`),
			N:       HI(`100000000000000000001cdc98ae0e2de574abf33`),
			Gx:      HI(`1`),
			Gy:      HI(`2`),
		}),
		WithOID(`2.23.43.1.4.9`),
	)
}
