// Code generated by curve_generator. DO NOT EDIT.
package montgomery

import (
	"github.com/RyuaNerin/elliptic2/internal/curve"
)

func (op *affineOp) add(dst, p1, p2 *curve.GFpCoordinate) {
	/**
	https://hyperelliptic.org/EFD/g1p/auto-montgom.html

	x3 = b*(y2-y1)**2/(x2-x1)**2-a-x1-x2
	y3 = (2*x1+x2+a)*(y2-y1)/(x2-x1)-b*(y2-y1)**3/(x2-x1)**3-y1

	| Operation                 | Expression
	|  1: _0 = x2 - x1          |
	|  2: _0 = _0**-1           |
	|  3: dxy = y2 - y1         |
	|  4: dxy = dxy * _0        | 1: dxy = (y2 - y1) * (x2 - x1)**-1
	|  5: _1 = dxy**2           |
	|  6: bdxy2 = b * _1        | 2: bdxy2 = b * dxy**2
	|  7: x3 = bdxy2 - a        |
	|  8: x3 = x3 - x1          |
	|  9: x3 = x3 - x2          | 3: x3 = bdxy2 - a - x1 - x2
	| 10: y3 = 2 * x1           |
	| 11: y3 = y3 + x2          |
	| 12: y3 = y3 + a           |
	| 13: y3 = y3 - bdxy2       |
	| 14: y3 = y3 * dxy         |
	| 15: y3 = y3 - y1          | 4: y3 = (2 * x1 + x2 + a - bdxy2) * dxy - y1
	*/

	a, b := op.A, op.B

	x1, y1 := &p1[0], &p1[1]
	x2, y2 := &p2[0], &p2[1]
	x3, y3 := &dst[0], &dst[1]

	_0 := &op.t[0]

	x3.Sub(x2, x1)  // 1: _0 = x2 - x1
	y3.Sub(y2, y1)  // 3: dxy = y2 - y1
	_0.Inv(x3)      // 2: _0 = _0**-1
	x3.Mul(y3, _0)  // 4: dxy = dxy * _0
	x3.ReduceSoft() //
	y3.Sqr(x3)      // 5: _1 = dxy**2
	y3.ReduceSoft() //
	_0.Mul(b, y3)   // 6: bdxy2 = b * _1
	_0.ReduceSoft() //
	y3.Lsh(x1, 1)   // 10: y3 = 2 * x1
	y3.Add(y3, x2)  // 11: y3 = y3 + x2
	y3.Add(y3, a)   // 12: y3 = y3 + a
	y3.Sub(y3, _0)  // 13: y3 = y3 - bdxy2
	y3.Mul(y3, x3)  // 14: y3 = y3 * dxy
	y3.ReduceSoft() //
	x3.Sub(_0, a)   // 7: x3 = bdxy2 - a
	x3.Sub(x3, x1)  // 8: x3 = x3 - x1
	x3.Sub(x3, x2)  // 9: x3 = x3 - x2
	x3.Reduce()     //
	y3.Sub(y3, y1)  // 15: y3 = y3 - y1
	y3.Reduce()     //
}
