// Code generated by curve_generator. DO NOT EDIT.

/*
package nist is a collection of named elliptic curves.

RECOMMENDED ELLIPTIC CURVES FOR FEDERAL GOVERNMENT USE  July 1999

https://neuromancer.sk/std/nist/
*/
package nist

import (
	"crypto/elliptic"
)

// B163 returns a Curve which implements nist/B-163
// https://neuromancer.sk/std/nist/
//
// OID: 1.3.132.0.15
// Aliases:
//   - secg/sect163r2
//   - x963/ansit163r2
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func B163() elliptic.Curve {
	b163Once.Do(initB163)
	return b163Curve
}

// B233 returns a Curve which implements nist/B-233
// https://neuromancer.sk/std/nist/
//
// OID: 1.3.132.0.27
// Aliases:
//   - secg/sect233r1
//   - wtls/wap-wsg-idm-ecid-wtls11
//   - x963/ansit233r1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func B233() elliptic.Curve {
	b233Once.Do(initB233)
	return b233Curve
}

// B283 returns a Curve which implements nist/B-283
// https://neuromancer.sk/std/nist/
//
// OID: 1.3.132.0.17
// Aliases:
//   - secg/sect283r1
//   - x963/ansit283r1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func B283() elliptic.Curve {
	b283Once.Do(initB283)
	return b283Curve
}

// B409 returns a Curve which implements nist/B-409
// https://neuromancer.sk/std/nist/
//
// OID: 1.3.132.0.37
// Aliases:
//   - secg/sect409r1
//   - x963/ansit409r1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func B409() elliptic.Curve {
	b409Once.Do(initB409)
	return b409Curve
}

// B571 returns a Curve which implements nist/B-571
// https://neuromancer.sk/std/nist/
//
// OID: 1.3.132.0.39
// Aliases:
//   - secg/sect571r1
//   - x963/ansit571r1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func B571() elliptic.Curve {
	b571Once.Do(initB571)
	return b571Curve
}

// K163 returns a Curve which implements nist/K-163
// https://neuromancer.sk/std/nist/
//
// OID: 1.3.132.0.1
// Aliases:
//   - secg/sect163k1
//   - x963/ansit163k1
//   - wtls/wap-wsg-idm-ecid-wtls3
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func K163() elliptic.Curve {
	k163Once.Do(initK163)
	return k163Curve
}

// K233 returns a Curve which implements nist/K-233
// https://neuromancer.sk/std/nist/
//
// OID: 1.3.132.0.26
// Aliases:
//   - secg/sect233k1
//   - wtls/wap-wsg-idm-ecid-wtls10
//   - x963/ansit233k1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func K233() elliptic.Curve {
	k233Once.Do(initK233)
	return k233Curve
}

// K283 returns a Curve which implements nist/K-283
// https://neuromancer.sk/std/nist/
//
// OID: 1.3.132.0.16
// Aliases:
//   - secg/sect283k1
//   - x963/ansit283k1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func K283() elliptic.Curve {
	k283Once.Do(initK283)
	return k283Curve
}

// K409 returns a Curve which implements nist/K-409
// https://neuromancer.sk/std/nist/
//
// OID: 1.3.132.0.36
// Aliases:
//   - secg/sect409k1
//   - x963/ansit409k1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func K409() elliptic.Curve {
	k409Once.Do(initK409)
	return k409Curve
}

// K571 returns a Curve which implements nist/K-571
// https://neuromancer.sk/std/nist/
//
// OID: 1.3.132.0.38
// Aliases:
//   - secg/sect571k1
//   - x963/ansit571k1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func K571() elliptic.Curve {
	k571Once.Do(initK571)
	return k571Curve
}

// P192 returns a Curve which implements nist/P-192
// https://neuromancer.sk/std/nist/
//
// OID: 1.2.840.10045.3.1.1
// Aliases:
//   - secg/secp192r1
//   - x962/prime192v1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func P192() elliptic.Curve {
	p192Once.Do(initP192)
	return p192Curve
}

// P224 returns a Curve which implements nist/P-224
// https://neuromancer.sk/std/nist/
//
// OID: 1.3.132.0.33
// Aliases:
//   - secg/secp224r1
//   - wtls/wap-wsg-idm-ecid-wtls12
//   - x963/ansip224r1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func P224() elliptic.Curve {
	p224Once.Do(initP224)
	return p224Curve
}

// P256 returns a Curve which implements nist/P-256
// https://neuromancer.sk/std/nist/
//
// OID: 1.2.840.10045.3.1.7
// Aliases:
//   - secg/secp256r1
//   - x962/prime256v1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func P256() elliptic.Curve {
	p256Once.Do(initP256)
	return p256Curve
}

// P384 returns a Curve which implements nist/P-384
// https://neuromancer.sk/std/nist/
//
// OID: 1.3.132.0.34
// Aliases:
//   - secg/secp384r1
//   - x963/ansip384r1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func P384() elliptic.Curve {
	p384Once.Do(initP384)
	return p384Curve
}

// P521 returns a Curve which implements nist/P-521
// https://neuromancer.sk/std/nist/
//
// OID: 1.3.132.0.35
// Aliases:
//   - secg/secp521r1
//   - x963/ansip521r1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func P521() elliptic.Curve {
	p521Once.Do(initP521)
	return p521Curve
}
