// Code generated by curve_generator. DO NOT EDIT.

package nist

import (
	"crypto/elliptic"
	"sync"

	. "github.com/RyuaNerin/elliptic2/internal"
	. "github.com/RyuaNerin/elliptic2/internal/curve"
	wb "github.com/RyuaNerin/elliptic2/internal/curve/weierstrassbinary"
	wp "github.com/RyuaNerin/elliptic2/internal/curve/weierstrassprime"
	. "github.com/RyuaNerin/elliptic2/internal/field"
)

var (
	b163Once sync.Once
	b233Once sync.Once
	b283Once sync.Once
	b409Once sync.Once
	b571Once sync.Once
	k163Once sync.Once
	k233Once sync.Once
	k283Once sync.Once
	k409Once sync.Once
	k571Once sync.Once
	p192Once sync.Once
	p224Once sync.Once
	p256Once sync.Once
	p384Once sync.Once
	p521Once sync.Once

	b163Curve elliptic.Curve
	b233Curve elliptic.Curve
	b283Curve elliptic.Curve
	b409Curve elliptic.Curve
	b571Curve elliptic.Curve
	k163Curve elliptic.Curve
	k233Curve elliptic.Curve
	k283Curve elliptic.Curve
	k409Curve elliptic.Curve
	k571Curve elliptic.Curve
	p192Curve elliptic.Curve
	p224Curve elliptic.Curve
	p256Curve elliptic.Curve
	p384Curve elliptic.Curve
	p521Curve elliptic.Curve
)

// https://neuromancer.sk/std/nist/B-163
func initB163() {
	b163Curve = NewCurve(
		wb.Build(&wb.CurveParams{
			Name:    `B-163`,
			BitSize: 163,
			Poly:    NewGF2mModulusFromPolynomials(163, 7, 6, 3, 0),
			A2:      ParseGF2mHex(`1`),
			A6:      ParseGF2mHex(`20a601907b8c953ca1481eb10512f78744a3205fd`),
			N:       ParseGF2mHex(`40000000000000000000292fe77e70c12a4234c33`),
			Gx:      HI(`3f0eba16286a2d57ea0991168d4994637e8343e36`),
			Gy:      HI(`d51fbc6c71a0094fa2cdd545b11c5c0c797324f1`),
		}),
		WithOID(`1.3.132.0.15`),
	)
}

// https://neuromancer.sk/std/nist/B-233
func initB233() {
	b233Curve = NewCurve(
		wb.Build(&wb.CurveParams{
			Name:    `B-233`,
			BitSize: 233,
			Poly:    NewGF2mModulusFromPolynomials(233, 74, 0),
			A2:      ParseGF2mHex(`1`),
			A6:      ParseGF2mHex(`66647ede6c332c7f8c0923bb58213b333b20e9ce4281fe115f7d8f90ad`),
			N:       ParseGF2mHex(`1000000000000000000000000000013e974e72f8a6922031d2603cfe0d7`),
			Gx:      HI(`fac9dfcbac8313bb2139f1bb755fef65bc391f8b36f8f8eb7371fd558b`),
			Gy:      HI(`1006a08a41903350678e58528bebf8a0beff867a7ca36716f7e01f81052`),
		}),
		WithOID(`1.3.132.0.27`),
	)
}

// https://neuromancer.sk/std/nist/B-283
func initB283() {
	b283Curve = NewCurve(
		wb.Build(&wb.CurveParams{
			Name:    `B-283`,
			BitSize: 283,
			Poly:    NewGF2mModulusFromPolynomials(283, 12, 7, 5, 0),
			A2:      ParseGF2mHex(`1`),
			A6:      ParseGF2mHex(`27b680ac8b8596da5a4af8a19a0303fca97fd7645309fa2a581485af6263e313b79a2f5`),
			N:       ParseGF2mHex(`3ffffffffffffffffffffffffffffffffffef90399660fc938a90165b042a7cefadb307`),
			Gx:      HI(`5f939258db7dd90e1934f8c70b0dfec2eed25b8557eac9c80e2e198f8cdbecd86b12053`),
			Gy:      HI(`3676854fe24141cb98fe6d4b20d02b4516ff702350eddb0826779c813f0df45be8112f4`),
		}),
		WithOID(`1.3.132.0.17`),
	)
}

// https://neuromancer.sk/std/nist/B-409
func initB409() {
	b409Curve = NewCurve(
		wb.Build(&wb.CurveParams{
			Name:    `B-409`,
			BitSize: 409,
			Poly:    NewGF2mModulusFromPolynomials(409, 87, 0),
			A2:      ParseGF2mHex(`1`),
			A6:      ParseGF2mHex(`21a5c2c8ee9feb5c4b9a753b7b476b7fd6422ef1f3dd674761fa99d6ac27c8a9a197b272822f6cd57a55aa4f50ae317b13545f`),
			N:       ParseGF2mHex(`10000000000000000000000000000000000000000000000000001e2aad6a612f33307be5fa47c3c9e052f838164cd37d9a21173`),
			Gx:      HI(`15d4860d088ddb3496b0c6064756260441cde4af1771d4db01ffe5b34e59703dc255a868a1180515603aeab60794e54bb7996a7`),
			Gy:      HI(`61b1cfab6be5f32bbfa78324ed106a7636b9c5a7bd198d0158aa4f5488d08f38514f1fdf4b4f40d2181b3681c364ba0273c706`),
		}),
		WithOID(`1.3.132.0.37`),
	)
}

// https://neuromancer.sk/std/nist/B-571
func initB571() {
	b571Curve = NewCurve(
		wb.Build(&wb.CurveParams{
			Name:    `B-571`,
			BitSize: 571,
			Poly:    NewGF2mModulusFromPolynomials(571, 10, 5, 2, 0),
			A2:      ParseGF2mHex(`1`),
			A6:      ParseGF2mHex(`2f40e7e2221f295de297117b7f3d62f5c6a97ffcb8ceff1cd6ba8ce4a9a18ad84ffabbd8efa59332be7ad6756a66e294afd185a78ff12aa520e4de739baca0c7ffeff7f2955727a`),
			N:       ParseGF2mHex(`3ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe661ce18ff55987308059b186823851ec7dd9ca1161de93d5174d66e8382e9bb2fe84e47`),
			Gx:      HI(`303001d34b856296c16c0d40d3cd7750a93d1d2955fa80aa5f40fc8db7b2abdbde53950f4c0d293cdd711a35b67fb1499ae60038614f1394abfa3b4c850d927e1e7769c8eec2d19`),
			Gy:      HI(`37bf27342da639b6dccfffeb73d69d78c6c27a6009cbbca1980f8533921e8a684423e43bab08a576291af8f461bb2a8b3531d2f0485c19b16e2f1516e23dd3c1a4827af1b8ac15b`),
		}),
		WithOID(`1.3.132.0.39`),
	)
}

// https://neuromancer.sk/std/nist/K-163
func initK163() {
	k163Curve = NewCurve(
		wb.Build(&wb.CurveParams{
			Name:    `K-163`,
			BitSize: 163,
			Poly:    NewGF2mModulusFromPolynomials(163, 7, 6, 3, 0),
			A2:      ParseGF2mHex(`1`),
			A6:      ParseGF2mHex(`1`),
			N:       ParseGF2mHex(`4000000000000000000020108a2e0cc0d99f8a5ef`),
			Gx:      HI(`2fe13c0537bbc11acaa07d793de4e6d5e5c94eee8`),
			Gy:      HI(`289070fb05d38ff58321f2e800536d538ccdaa3d9`),
		}),
		WithOID(`1.3.132.0.1`),
	)
}

// https://neuromancer.sk/std/nist/K-233
func initK233() {
	k233Curve = NewCurve(
		wb.Build(&wb.CurveParams{
			Name:    `K-233`,
			BitSize: 233,
			Poly:    NewGF2mModulusFromPolynomials(233, 74, 0),
			A2:      ParseGF2mHex(``),
			A6:      ParseGF2mHex(`1`),
			N:       ParseGF2mHex(`8000000000000000000000000000069d5bb915bcd46efb1ad5f173abdf`),
			Gx:      HI(`17232ba853a7e731af129f22ff4149563a419c26bf50a4c9d6eefad6126`),
			Gy:      HI(`1db537dece819b7f70f555a67c427a8cd9bf18aeb9b56e0c11056fae6a3`),
		}),
		WithOID(`1.3.132.0.26`),
	)
}

// https://neuromancer.sk/std/nist/K-283
func initK283() {
	k283Curve = NewCurve(
		wb.Build(&wb.CurveParams{
			Name:    `K-283`,
			BitSize: 283,
			Poly:    NewGF2mModulusFromPolynomials(283, 12, 7, 5, 0),
			A2:      ParseGF2mHex(``),
			A6:      ParseGF2mHex(`1`),
			N:       ParseGF2mHex(`1ffffffffffffffffffffffffffffffffffe9ae2ed07577265dff7f94451e061e163c61`),
			Gx:      HI(`503213f78ca44883f1a3b8162f188e553cd265f23c1567a16876913b0c2ac2458492836`),
			Gy:      HI(`1ccda380f1c9e318d90f95d07e5426fe87e45c0e8184698e45962364e34116177dd2259`),
		}),
		WithOID(`1.3.132.0.16`),
	)
}

// https://neuromancer.sk/std/nist/K-409
func initK409() {
	k409Curve = NewCurve(
		wb.Build(&wb.CurveParams{
			Name:    `K-409`,
			BitSize: 409,
			Poly:    NewGF2mModulusFromPolynomials(409, 87, 0),
			A2:      ParseGF2mHex(``),
			A6:      ParseGF2mHex(`1`),
			N:       ParseGF2mHex(`7ffffffffffffffffffffffffffffffffffffffffffffffffffe5f83b2d4ea20400ec4557d5ed3e3e7ca5b4b5c83b8e01e5fcf`),
			Gx:      HI(`60f05f658f49c1ad3ab1890f7184210efd0987e307c84c27accfb8f9f67cc2c460189eb5aaaa62ee222eb1b35540cfe9023746`),
			Gy:      HI(`1e369050b7c4e42acba1dacbf04299c3460782f918ea427e6325165e9ea10e3da5f6c42e9c55215aa9ca27a5863ec48d8e0286b`),
		}),
		WithOID(`1.3.132.0.36`),
	)
}

// https://neuromancer.sk/std/nist/K-571
func initK571() {
	k571Curve = NewCurve(
		wb.Build(&wb.CurveParams{
			Name:    `K-571`,
			BitSize: 571,
			Poly:    NewGF2mModulusFromPolynomials(571, 10, 5, 2, 0),
			A2:      ParseGF2mHex(``),
			A6:      ParseGF2mHex(`1`),
			N:       ParseGF2mHex(`20000000000000000000000000000000000000000000000000000000000000000000000131850e1f19a63e4b391a8db917f4138b630d84be5d639381e91deb45cfe778f637c1001`),
			Gx:      HI(`26eb7a859923fbc82189631f8103fe4ac9ca2970012d5d46024804801841ca44370958493b205e647da304db4ceb08cbbd1ba39494776fb988b47174dca88c7e2945283a01c8972`),
			Gy:      HI(`349dc807f4fbf374f4aeade3bca95314dd58cec9f307a54ffc61efc006d8a2c9d4979c0ac44aea74fbebbb9f772aedcb620b01a7ba7af1b320430c8591984f601cd4c143ef1c7a3`),
		}),
		WithOID(`1.3.132.0.38`),
	)
}

// https://neuromancer.sk/std/nist/P-192
func initP192() {
	p192Curve = NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `P-192`,
			BitSize: 192,
			P:       NewGFpModulusFromHex(`fffffffffffffffffffffffffffffffeffffffffffffffff`),
			A:       ParseGFpHex(`fffffffffffffffffffffffffffffffefffffffffffffffc`),
			B:       ParseGFpHex(`64210519e59c80e70fa7e9ab72243049feb8deecc146b9b1`),
			N:       ParseGFpHex(`ffffffffffffffffffffffff99def836146bc9b1b4d22831`),
			Gx:      HI(`188da80eb03090f67cbf20eb43a18800f4ff0afd82ff1012`),
			Gy:      HI(`7192b95ffc8da78631011ed6b24cdd573f977a11e794811`),
		}),
		WithOID(`1.2.840.10045.3.1.1`),
	)
}

// https://neuromancer.sk/std/nist/P-224
func initP224() {
	p224Curve = NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `P-224`,
			BitSize: 224,
			P:       NewGFpModulusFromHex(`ffffffffffffffffffffffffffffffff000000000000000000000001`),
			A:       ParseGFpHex(`fffffffffffffffffffffffffffffffefffffffffffffffffffffffe`),
			B:       ParseGFpHex(`b4050a850c04b3abf54132565044b0b7d7bfd8ba270b39432355ffb4`),
			N:       ParseGFpHex(`ffffffffffffffffffffffffffff16a2e0b8f03e13dd29455c5c2a3d`),
			Gx:      HI(`b70e0cbd6bb4bf7f321390b94a03c1d356c21122343280d6115c1d21`),
			Gy:      HI(`bd376388b5f723fb4c22dfe6cd4375a05a07476444d5819985007e34`),
		}),
		WithOID(`1.3.132.0.33`),
	)
}

// https://neuromancer.sk/std/nist/P-256
func initP256() {
	p256Curve = NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `P-256`,
			BitSize: 256,
			P:       NewGFpModulusFromHex(`ffffffff00000001000000000000000000000000ffffffffffffffffffffffff`),
			A:       ParseGFpHex(`ffffffff00000001000000000000000000000000fffffffffffffffffffffffc`),
			B:       ParseGFpHex(`5ac635d8aa3a93e7b3ebbd55769886bc651d06b0cc53b0f63bce3c3e27d2604b`),
			N:       ParseGFpHex(`ffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551`),
			Gx:      HI(`6b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c296`),
			Gy:      HI(`4fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5`),
		}),
		WithOID(`1.2.840.10045.3.1.7`),
	)
}

// https://neuromancer.sk/std/nist/P-384
func initP384() {
	p384Curve = NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `P-384`,
			BitSize: 384,
			P:       NewGFpModulusFromHex(`fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeffffffff0000000000000000ffffffff`),
			A:       ParseGFpHex(`fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffeffffffff0000000000000000fffffffc`),
			B:       ParseGFpHex(`b3312fa7e23ee7e4988e056be3f82d19181d9c6efe8141120314088f5013875ac656398d8a2ed19d2a85c8edd3ec2aef`),
			N:       ParseGFpHex(`ffffffffffffffffffffffffffffffffffffffffffffffffc7634d81f4372ddf581a0db248b0a77aecec196accc52973`),
			Gx:      HI(`aa87ca22be8b05378eb1c71ef320ad746e1d3b628ba79b9859f741e082542a385502f25dbf55296c3a545e3872760ab7`),
			Gy:      HI(`3617de4a96262c6f5d9e98bf9292dc29f8f41dbd289a147ce9da3113b5f0b8c00a60b1ce1d7e819d7a431d7c90ea0e5f`),
		}),
		WithOID(`1.3.132.0.34`),
	)
}

// https://neuromancer.sk/std/nist/P-521
func initP521() {
	p521Curve = NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `P-521`,
			BitSize: 521,
			P:       NewGFpModulusFromHex(`1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff`),
			A:       ParseGFpHex(`1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc`),
			B:       ParseGFpHex(`51953eb9618e1c9a1f929a21a0b68540eea2da725b99b315f3b8b489918ef109e156193951ec7e937b1652c0bd3bb1bf073573df883d2c34f1ef451fd46b503f00`),
			N:       ParseGFpHex(`1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffa51868783bf2f966b7fcc0148f709a5d03bb5c9b8899c47aebb6fb71e91386409`),
			Gx:      HI(`c6858e06b70404e9cd9e3ecb662395b4429c648139053fb521f828af606b4d3dbaa14b5e77efe75928fe1dc127a2ffa8de3348b3c1856a429bf97e7e31c2e5bd66`),
			Gy:      HI(`11839296a789a3bc0045c8a5fb42c7d1bd998f54449579b446817afbd17273e662c97ee72995ef42640c550b9013fad0761353c7086a272c24088be94769fd16650`),
		}),
		WithOID(`1.3.132.0.35`),
	)
}
