// Code generated by curve_generator. DO NOT EDIT.

/*
package nist is a collection of named elliptic curves.

# RECOMMENDED ELLIPTIC CURVES FOR FEDERAL GOVERNMENT USE  July 1999

https://neuromancer.sk/std/nist/
*/
package nist

import (
	"crypto/elliptic"

	"github.com/RyuaNerin/elliptic2/internal/curves"
)

// B163 returns a Curve which implements nist/B-163
// https://neuromancer.sk/std/nist/B-163
//
// OID: 1.3.132.0.15
// Aliases:
//   - secg/sect163r2
//   - x963/ansit163r2
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func B163() elliptic.Curve {
	return curves.NistB163()
}

// B233 returns a Curve which implements nist/B-233
// https://neuromancer.sk/std/nist/B-233
//
// OID: 1.3.132.0.27
// Aliases:
//   - secg/sect233r1
//   - wtls/wap-wsg-idm-ecid-wtls11
//   - x963/ansit233r1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func B233() elliptic.Curve {
	return curves.NistB233()
}

// B283 returns a Curve which implements nist/B-283
// https://neuromancer.sk/std/nist/B-283
//
// OID: 1.3.132.0.17
// Aliases:
//   - secg/sect283r1
//   - x963/ansit283r1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func B283() elliptic.Curve {
	return curves.NistB283()
}

// B409 returns a Curve which implements nist/B-409
// https://neuromancer.sk/std/nist/B-409
//
// OID: 1.3.132.0.37
// Aliases:
//   - secg/sect409r1
//   - x963/ansit409r1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func B409() elliptic.Curve {
	return curves.NistB409()
}

// B571 returns a Curve which implements nist/B-571
// https://neuromancer.sk/std/nist/B-571
//
// OID: 1.3.132.0.39
// Aliases:
//   - secg/sect571r1
//   - x963/ansit571r1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func B571() elliptic.Curve {
	return curves.NistB571()
}

// K163 returns a Curve which implements nist/K-163
// https://neuromancer.sk/std/nist/K-163
//
// OID: 1.3.132.0.1
// Aliases:
//   - secg/sect163k1
//   - x963/ansit163k1
//   - wtls/wap-wsg-idm-ecid-wtls3
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func K163() elliptic.Curve {
	return curves.NistK163()
}

// K233 returns a Curve which implements nist/K-233
// https://neuromancer.sk/std/nist/K-233
//
// OID: 1.3.132.0.26
// Aliases:
//   - secg/sect233k1
//   - wtls/wap-wsg-idm-ecid-wtls10
//   - x963/ansit233k1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func K233() elliptic.Curve {
	return curves.NistK233()
}

// K283 returns a Curve which implements nist/K-283
// https://neuromancer.sk/std/nist/K-283
//
// OID: 1.3.132.0.16
// Aliases:
//   - secg/sect283k1
//   - x963/ansit283k1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func K283() elliptic.Curve {
	return curves.NistK283()
}

// K409 returns a Curve which implements nist/K-409
// https://neuromancer.sk/std/nist/K-409
//
// OID: 1.3.132.0.36
// Aliases:
//   - secg/sect409k1
//   - x963/ansit409k1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func K409() elliptic.Curve {
	return curves.NistK409()
}

// K571 returns a Curve which implements nist/K-571
// https://neuromancer.sk/std/nist/K-571
//
// OID: 1.3.132.0.38
// Aliases:
//   - secg/sect571k1
//   - x963/ansit571k1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func K571() elliptic.Curve {
	return curves.NistK571()
}

// P192 returns a Curve which implements nist/P-192
// https://neuromancer.sk/std/nist/P-192
//
// OID: 1.2.840.10045.3.1.1
// Aliases:
//   - secg/secp192r1
//   - x962/prime192v1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func P192() elliptic.Curve {
	return curves.NistP192()
}

// P224 returns a Curve which implements nist/P-224
// https://neuromancer.sk/std/nist/P-224
//
// OID: 1.3.132.0.33
// Aliases:
//   - secg/secp224r1
//   - wtls/wap-wsg-idm-ecid-wtls12
//   - x963/ansip224r1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func P224() elliptic.Curve {
	return curves.NistP224()
}

// P256 returns a Curve which implements nist/P-256
// https://neuromancer.sk/std/nist/P-256
//
// OID: 1.2.840.10045.3.1.7
// Aliases:
//   - secg/secp256r1
//   - x962/prime256v1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func P256() elliptic.Curve {
	return curves.NistP256()
}

// P384 returns a Curve which implements nist/P-384
// https://neuromancer.sk/std/nist/P-384
//
// OID: 1.3.132.0.34
// Aliases:
//   - secg/secp384r1
//   - x963/ansip384r1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func P384() elliptic.Curve {
	return curves.NistP384()
}

// P521 returns a Curve which implements nist/P-521
// https://neuromancer.sk/std/nist/P-521
//
// OID: 1.3.132.0.35
// Aliases:
//   - secg/secp521r1
//   - x963/ansip521r1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func P521() elliptic.Curve {
	return curves.NistP521()
}
