// Code generated by curve_generator. DO NOT EDIT.

package nums

import (
	"crypto/elliptic"
	"sync"

	. "github.com/RyuaNerin/elliptic2/internal"
	. "github.com/RyuaNerin/elliptic2/internal/curve"
	t "github.com/RyuaNerin/elliptic2/internal/curve/twistededwards"
	wp "github.com/RyuaNerin/elliptic2/internal/curve/weierstrassprime"
	. "github.com/RyuaNerin/elliptic2/internal/field"
)

var (
	ed254MontOnce  sync.Once
	ed255MersOnce  sync.Once
	ed256MontOnce  sync.Once
	ed382MontOnce  sync.Once
	ed383MersOnce  sync.Once
	ed384MontOnce  sync.Once
	ed510MontOnce  sync.Once
	ed511MersOnce  sync.Once
	ed512MontOnce  sync.Once
	numsp256d1Once sync.Once
	numsp256t1Once sync.Once
	numsp384d1Once sync.Once
	numsp384t1Once sync.Once
	numsp512d1Once sync.Once
	numsp512t1Once sync.Once
	w254MontOnce   sync.Once
	w255MersOnce   sync.Once
	w256MontOnce   sync.Once
	w382MontOnce   sync.Once
	w383MersOnce   sync.Once
	w384MontOnce   sync.Once
	w510MontOnce   sync.Once
	w511MersOnce   sync.Once
	w512MontOnce   sync.Once

	ed254MontCurve  elliptic.Curve
	ed255MersCurve  elliptic.Curve
	ed256MontCurve  elliptic.Curve
	ed382MontCurve  elliptic.Curve
	ed383MersCurve  elliptic.Curve
	ed384MontCurve  elliptic.Curve
	ed510MontCurve  elliptic.Curve
	ed511MersCurve  elliptic.Curve
	ed512MontCurve  elliptic.Curve
	numsp256d1Curve elliptic.Curve
	numsp256t1Curve elliptic.Curve
	numsp384d1Curve elliptic.Curve
	numsp384t1Curve elliptic.Curve
	numsp512d1Curve elliptic.Curve
	numsp512t1Curve elliptic.Curve
	w254MontCurve   elliptic.Curve
	w255MersCurve   elliptic.Curve
	w256MontCurve   elliptic.Curve
	w382MontCurve   elliptic.Curve
	w383MersCurve   elliptic.Curve
	w384MontCurve   elliptic.Curve
	w510MontCurve   elliptic.Curve
	w511MersCurve   elliptic.Curve
	w512MontCurve   elliptic.Curve
)

// https://neuromancer.sk/std/nums/ed-254-mont
func initEd254Mont() {
	ed254MontCurve = NewCurve(
		t.Build(&t.CurveParams{
			Name:    `ed-254-mont`,
			BitSize: 254,
			P:       NewGFpModulusFromHex(`3f80ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff`),
			A:       ParseGFpHex(`3f80fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe`),
			D:       ParseGFpHex(`367b`),
			N:       HI(`fe03fffffffffffffffffffffffffffeb95306c8bd62fb0eaf3d3fec46e98c7`),
		}),
	)
}

// https://neuromancer.sk/std/nums/ed-255-mers
func initEd255Mers() {
	ed255MersCurve = NewCurve(
		t.Build(&t.CurveParams{
			Name:    `ed-255-mers`,
			BitSize: 255,
			P:       NewGFpModulusFromHex(`7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffd03`),
			A:       ParseGFpHex(`7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffd02`),
			D:       ParseGFpHex(`ea97`),
			N:       HI(`1fffffffffffffffffffffffffffffffdcf1a785eda6832eac49d1ed0436eb75`),
		}),
	)
}

// https://neuromancer.sk/std/nums/ed-256-mont
func initEd256Mont() {
	ed256MontCurve = NewCurve(
		t.Build(&t.CurveParams{
			Name:    `ed-256-mont`,
			BitSize: 256,
			P:       NewGFpModulusFromHex(`ffa7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff`),
			A:       ParseGFpHex(`ffa7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe`),
			D:       ParseGFpHex(`350a`),
			N:       HI(`3fe9ffffffffffffffffffffffffffffb154bbafb86733c966d92eded8ec7bab`),
		}),
	)
}

// https://neuromancer.sk/std/nums/ed-382-mont
func initEd382Mont() {
	ed382MontCurve = NewCurve(
		t.Build(&t.CurveParams{
			Name:    `ed-382-mont`,
			BitSize: 382,
			P:       NewGFpModulusFromHex(`3ffaffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff`),
			A:       ParseGFpHex(`3ffafffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe`),
			D:       ParseGFpHex(`af381`),
			N:       HI(`ffebfffffffffffffffffffffffffffffffffffffffffffd31afaa1520dc177d8c1605c481e068269880369e5f3fa61`),
		}),
	)
}

// https://neuromancer.sk/std/nums/ed-383-mers
func initEd383Mers() {
	ed383MersCurve = NewCurve(
		t.Build(&t.CurveParams{
			Name:    `ed-383-mers`,
			BitSize: 383,
			P:       NewGFpModulusFromHex(`7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe5b`),
			A:       ParseGFpHex(`7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe5a`),
			D:       ParseGFpHex(`7fed6`),
			N:       HI(`1ffffffffffffffffffffffffffffffffffffffffffffffff1109704e73d9fbbbcd5687c9eaca2206ffebcec1ba7c81d`),
		}),
	)
}

// https://neuromancer.sk/std/nums/ed-384-mont
func initEd384Mont() {
	ed384MontCurve = NewCurve(
		t.Build(&t.CurveParams{
			Name:    `ed-384-mont`,
			BitSize: 384,
			P:       NewGFpModulusFromHex(`b0ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff`),
			A:       ParseGFpHex(`b0fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe`),
			D:       ParseGFpHex(`6f17`),
			N:       HI(`2c3ffffffffffffffffffffffffffffffffffffffffffffff56d07e24e2749cd9f6b769aec80f6fe06fe4e3a6332489b`),
		}),
	)
}

// https://neuromancer.sk/std/nums/ed-510-mont
func initEd510Mont() {
	ed510MontCurve = NewCurve(
		t.Build(&t.CurveParams{
			Name:    `ed-510-mont`,
			BitSize: 510,
			P:       NewGFpModulusFromHex(`3eddffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff`),
			A:       ParseGFpHex(`3eddfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe`),
			D:       ParseGFpHex(`8da1e`),
			N:       HI(`fb77fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffd7ced11e7c2f1abf716df42a6c246080b5fcc20917e59a42c85821cdf36d51b1`),
		}),
	)
}

// https://neuromancer.sk/std/nums/ed-511-mers
func initEd511Mers() {
	ed511MersCurve = NewCurve(
		t.Build(&t.CurveParams{
			Name:    `ed-511-mers`,
			BitSize: 511,
			P:       NewGFpModulusFromHex(`7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe1f`),
			A:       ParseGFpHex(`7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe1e`),
			D:       ParseGFpHex(`10bf7d`),
			N:       HI(`1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffea7c34182e41e2e9baa930e478c489b72542706bec5f32194f7c2e8f8d142f11`),
		}),
	)
}

// https://neuromancer.sk/std/nums/ed-512-mont
func initEd512Mont() {
	ed512MontCurve = NewCurve(
		t.Build(&t.CurveParams{
			Name:    `ed-512-mont`,
			BitSize: 512,
			P:       NewGFpModulusFromHex(`fe14ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff`),
			A:       ParseGFpHex(`fe14fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe`),
			D:       ParseGFpHex(`12a9c`),
			N:       HI(`3f853fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccfd59cdc33470d103060513f6def4d37d9af21b2b2701fa331487ecb8db605`),
		}),
	)
}

// https://neuromancer.sk/std/nums/numsp256d1
func initNumsp256d1() {
	numsp256d1Curve = NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `numsp256d1`,
			BitSize: 256,
			P:       NewGFpModulusFromHex(`ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff43`),
			A:       ParseGFpHex(`ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff40`),
			B:       ParseGFpHex(`25581`),
			N:       HI(`ffffffffffffffffffffffffffffffffe43c8275ea265c6020ab20294751a825`),
			Gx:      HI(`1`),
			Gy:      HI(`696f1853c1e466d7fc82c96cceeedd6bd02c2f9375894ec10bf46306c2b56c77`),
		}),
	)
}

// https://neuromancer.sk/std/nums/numsp256t1
func initNumsp256t1() {
	numsp256t1Curve = NewCurve(
		t.Build(&t.CurveParams{
			Name:    `numsp256t1`,
			BitSize: 256,
			P:       NewGFpModulusFromHex(`ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff43`),
			A:       ParseGFpHex(`ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff42`),
			D:       ParseGFpHex(`3bee`),
			N:       HI(`3fffffffffffffffffffffffffffffffbe6aa55ad0a6bc64e5b84e6f1122b4ad`),
			Gx:      HI(`d`),
			Gy:      HI(`7d0ab41e2a1276dba3d330b39fa046bfbe2a6d63824d303f707f6fb5331cadba`),
		}),
	)
}

// https://neuromancer.sk/std/nums/numsp384d1
func initNumsp384d1() {
	numsp384d1Curve = NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `numsp384d1`,
			BitSize: 384,
			P:       NewGFpModulusFromHex(`fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffec3`),
			A:       ParseGFpHex(`fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffec0`),
			B:       ParseGFpHex(`ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff77bb`),
			N:       HI(`ffffffffffffffffffffffffffffffffffffffffffffffffd61eaf1eeb5d6881beda9d3d4c37e27a604d81f67b0e61b9`),
			Gx:      HI(`2`),
			Gy:      HI(`3c9f82cb4b87b4dc71e763e0663e5dbd8034ed422f04f82673330dc58d15ffa2b4a3d0bad5d30f865bcbbf503ea66f43`),
		}),
	)
}

// https://neuromancer.sk/std/nums/numsp384t1
func initNumsp384t1() {
	numsp384t1Curve = NewCurve(
		t.Build(&t.CurveParams{
			Name:    `numsp384t1`,
			BitSize: 384,
			P:       NewGFpModulusFromHex(`fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffec3`),
			A:       ParseGFpHex(`fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffec2`),
			D:       ParseGFpHex(`5158a`),
			N:       HI(`3fffffffffffffffffffffffffffffffffffffffffffffffecd7d11ed5a259a25a13a0458e39f4e451d6d71f70426e25`),
			Gx:      HI(`8`),
			Gy:      HI(`749cdaba136ce9b65bd4471794aa619daa5c7b4c930bff8ebd798a8ae753c6d72f003860febabad534a4acf5fa7f5bee`),
		}),
	)
}

// https://neuromancer.sk/std/nums/numsp512d1
func initNumsp512d1() {
	numsp512d1Curve = NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `numsp512d1`,
			BitSize: 512,
			P:       NewGFpModulusFromHex(`fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdc7`),
			A:       ParseGFpHex(`fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdc4`),
			B:       ParseGFpHex(`1d99b`),
			N:       HI(`ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5b3ca4fb94e7831b4fc258ed97d0bdc63b568b36607cd243ce153f390433555d`),
			Gx:      HI(`2`),
			Gy:      HI(`1c282eb23327f9711952c250ea61ad53fcc13031cf6dd336e0b9328433afbdd8cc5a1c1f0c716fdc724dde537c2b0adb00bb3d08dc83755b205cc30d7f83cf28`),
		}),
	)
}

// https://neuromancer.sk/std/nums/numsp512t1
func initNumsp512t1() {
	numsp512t1Curve = NewCurve(
		t.Build(&t.CurveParams{
			Name:    `numsp512t1`,
			BitSize: 512,
			P:       NewGFpModulusFromHex(`fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdc7`),
			A:       ParseGFpHex(`fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdc6`),
			D:       ParseGFpHex(`9baa8`),
			N:       HI(`3fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffa7e50809efdabbb9a624784f449545f0dcea5ff0cb800f894e78d1cb0b5f0189`),
			Gx:      HI(`20`),
			Gy:      HI(`7d67e841dc4c467b605091d80869212f9ceb124bf726973f9ff048779e1d614e62ae2ece5057b5dad96b7a897c1d72799261134638750f4f0cb91027543b1c5e`),
		}),
	)
}

// https://neuromancer.sk/std/nums/w-254-mont
func initW254Mont() {
	w254MontCurve = NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `w-254-mont`,
			BitSize: 254,
			P:       NewGFpModulusFromHex(`3f80ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff`),
			A:       ParseGFpHex(`3f80fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc`),
			B:       ParseGFpHex(`-2f72`),
			N:       HI(`3f80ffffffffffffffffffffffffffffeb818bea0da375c06fa419c4af8df83f`),
		}),
	)
}

// https://neuromancer.sk/std/nums/w-255-mers
func initW255Mers() {
	w255MersCurve = NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `w-255-mers`,
			BitSize: 255,
			P:       NewGFpModulusFromHex(`7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffd03`),
			A:       ParseGFpHex(`7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffd00`),
			B:       ParseGFpHex(`-51bd`),
			N:       HI(`7fffffffffffffffffffffffffffffff864a38283ad2b3dfab8fac983c594aeb`),
		}),
	)
}

// https://neuromancer.sk/std/nums/w-256-mont
func initW256Mont() {
	w256MontCurve = NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `w-256-mont`,
			BitSize: 256,
			P:       NewGFpModulusFromHex(`ffa7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff`),
			A:       ParseGFpHex(`ffa7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc`),
			B:       ParseGFpHex(`14e6a`),
			N:       HI(`ffa7fffffffffffffffffffffffffffffc517513e6e5074b9d10c5e1a79857eb`),
		}),
	)
}

// https://neuromancer.sk/std/nums/w-382-mont
func initW382Mont() {
	w382MontCurve = NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `w-382-mont`,
			BitSize: 382,
			P:       NewGFpModulusFromHex(`3ffaffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff`),
			A:       ParseGFpHex(`3ffafffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc`),
			B:       ParseGFpHex(`-20a72`),
			N:       HI(`3ffaffffffffffffffffffffffffffffffffffffffffffffa6eb1cff4bde214d73b321ffd8e82cd160ab86803ebb301d`),
		}),
	)
}

// https://neuromancer.sk/std/nums/w-383-mers
func initW383Mers() {
	w383MersCurve = NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `w-383-mers`,
			BitSize: 383,
			P:       NewGFpModulusFromHex(`7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe5b`),
			A:       ParseGFpHex(`7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe58`),
			B:       ParseGFpHex(`17dbc`),
			N:       HI(`7fffffffffffffffffffffffffffffffffffffffffffffffa9caf814a8a116ad9fb0b4035417aaf319297fc0bb7a439f`),
		}),
	)
}

// https://neuromancer.sk/std/nums/w-384-mont
func initW384Mont() {
	w384MontCurve = NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `w-384-mont`,
			BitSize: 384,
			P:       NewGFpModulusFromHex(`b0ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff`),
			A:       ParseGFpHex(`b0fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc`),
			B:       ParseGFpHex(`6c96`),
			N:       HI(`b0ffffffffffffffffffffffffffffffffffffffffffffffba9b7f14ca7512537a4edcd38a7c41da29be4894b298eebb`),
		}),
	)
}

// https://neuromancer.sk/std/nums/w-510-mont
func initW510Mont() {
	w510MontCurve = NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `w-510-mont`,
			BitSize: 510,
			P:       NewGFpModulusFromHex(`3eddffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff`),
			A:       ParseGFpHex(`3eddfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc`),
			B:       ParseGFpHex(`988d`),
			N:       HI(`3eddffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb9146ccde150ef33747ab29d1e6573d8d22de95e322303f3a00b200986fa9a2d`),
		}),
	)
}

// https://neuromancer.sk/std/nums/w-511-mers
func initW511Mers() {
	w511MersCurve = NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `w-511-mers`,
			BitSize: 511,
			P:       NewGFpModulusFromHex(`7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe1f`),
			A:       ParseGFpHex(`7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe1c`),
			B:       ParseGFpHex(`879da`),
			N:       HI(`7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff8dbefa3f5ed9d839a2d4fe6ff516e87fa8d3e656a0f99fa1f0105f73b3b9d19f`),
		}),
	)
}

// https://neuromancer.sk/std/nums/w-512-mont
func initW512Mont() {
	w512MontCurve = NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `w-512-mont`,
			BitSize: 512,
			P:       NewGFpModulusFromHex(`fe14ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff`),
			A:       ParseGFpHex(`fe14fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc`),
			B:       ParseGFpHex(`185ed`),
			N:       HI(`fe14ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff638a8d792ee750298064aaf0b8498e61df3d3995064ed73b939628f17e98fdc9`),
		}),
	)
}
