// Code generated by curve_generator. DO NOT EDIT.

/*
package brainpool is a collection of named elliptic curves.

ECC Brainpool Standard Curves and Curve Generation v. 1.0  19.10.2005

https://neuromancer.sk/std/brainpool/
*/
package brainpool

import (
	"crypto/elliptic"
)

// BrainpoolP160r1 returns a Curve which implements brainpool/brainpoolP160r1
// https://neuromancer.sk/std/brainpool/
//
// OID: 1.3.36.3.3.2.8.1.1.1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func BrainpoolP160r1() elliptic.Curve {
	brainpoolP160r1Once.Do(initBrainpoolP160r1)
	return brainpoolP160r1Curve
}

// BrainpoolP160t1 returns a Curve which implements brainpool/brainpoolP160t1
// https://neuromancer.sk/std/brainpool/
//
// OID: 1.3.36.3.3.2.8.1.1.2
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func BrainpoolP160t1() elliptic.Curve {
	brainpoolP160t1Once.Do(initBrainpoolP160t1)
	return brainpoolP160t1Curve
}

// BrainpoolP192r1 returns a Curve which implements brainpool/brainpoolP192r1
// https://neuromancer.sk/std/brainpool/
//
// OID: 1.3.36.3.3.2.8.1.1.3
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func BrainpoolP192r1() elliptic.Curve {
	brainpoolP192r1Once.Do(initBrainpoolP192r1)
	return brainpoolP192r1Curve
}

// BrainpoolP192t1 returns a Curve which implements brainpool/brainpoolP192t1
// https://neuromancer.sk/std/brainpool/
//
// OID: 1.3.36.3.3.2.8.1.1.4
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func BrainpoolP192t1() elliptic.Curve {
	brainpoolP192t1Once.Do(initBrainpoolP192t1)
	return brainpoolP192t1Curve
}

// BrainpoolP224r1 returns a Curve which implements brainpool/brainpoolP224r1
// https://neuromancer.sk/std/brainpool/
//
// OID: 1.3.36.3.3.2.8.1.1.5
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func BrainpoolP224r1() elliptic.Curve {
	brainpoolP224r1Once.Do(initBrainpoolP224r1)
	return brainpoolP224r1Curve
}

// BrainpoolP224t1 returns a Curve which implements brainpool/brainpoolP224t1
// https://neuromancer.sk/std/brainpool/
//
// OID: 1.3.36.3.3.2.8.1.1.6
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func BrainpoolP224t1() elliptic.Curve {
	brainpoolP224t1Once.Do(initBrainpoolP224t1)
	return brainpoolP224t1Curve
}

// BrainpoolP256r1 returns a Curve which implements brainpool/brainpoolP256r1
// https://neuromancer.sk/std/brainpool/
//
// OID: 1.3.36.3.3.2.8.1.1.7
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func BrainpoolP256r1() elliptic.Curve {
	brainpoolP256r1Once.Do(initBrainpoolP256r1)
	return brainpoolP256r1Curve
}

// BrainpoolP256t1 returns a Curve which implements brainpool/brainpoolP256t1
// https://neuromancer.sk/std/brainpool/
//
// OID: 1.3.36.3.3.2.8.1.1.8
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func BrainpoolP256t1() elliptic.Curve {
	brainpoolP256t1Once.Do(initBrainpoolP256t1)
	return brainpoolP256t1Curve
}

// BrainpoolP320r1 returns a Curve which implements brainpool/brainpoolP320r1
// https://neuromancer.sk/std/brainpool/
//
// OID: 1.3.36.3.3.2.8.1.1.9
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func BrainpoolP320r1() elliptic.Curve {
	brainpoolP320r1Once.Do(initBrainpoolP320r1)
	return brainpoolP320r1Curve
}

// BrainpoolP320t1 returns a Curve which implements brainpool/brainpoolP320t1
// https://neuromancer.sk/std/brainpool/
//
// OID: 1.3.36.3.3.2.8.1.1.10
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func BrainpoolP320t1() elliptic.Curve {
	brainpoolP320t1Once.Do(initBrainpoolP320t1)
	return brainpoolP320t1Curve
}

// BrainpoolP384r1 returns a Curve which implements brainpool/brainpoolP384r1
// https://neuromancer.sk/std/brainpool/
//
// OID: 1.3.36.3.3.2.8.1.1.11
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func BrainpoolP384r1() elliptic.Curve {
	brainpoolP384r1Once.Do(initBrainpoolP384r1)
	return brainpoolP384r1Curve
}

// BrainpoolP384t1 returns a Curve which implements brainpool/brainpoolP384t1
// https://neuromancer.sk/std/brainpool/
//
// OID: 1.3.36.3.3.2.8.1.1.12
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func BrainpoolP384t1() elliptic.Curve {
	brainpoolP384t1Once.Do(initBrainpoolP384t1)
	return brainpoolP384t1Curve
}

// BrainpoolP512r1 returns a Curve which implements brainpool/brainpoolP512r1
// https://neuromancer.sk/std/brainpool/
//
// OID: 1.3.36.3.3.2.8.1.1.13
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func BrainpoolP512r1() elliptic.Curve {
	brainpoolP512r1Once.Do(initBrainpoolP512r1)
	return brainpoolP512r1Curve
}

// BrainpoolP512t1 returns a Curve which implements brainpool/brainpoolP512t1
// https://neuromancer.sk/std/brainpool/
//
// OID: 1.3.36.3.3.2.8.1.1.14
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func BrainpoolP512t1() elliptic.Curve {
	brainpoolP512t1Once.Do(initBrainpoolP512t1)
	return brainpoolP512t1Curve
}
