// Code generated by curve_generator. DO NOT EDIT.
package twistededwards

import (
	"github.com/RyuaNerin/elliptic2/internal/curve"
	"github.com/RyuaNerin/elliptic2/internal/field"
)

func (op *affineOp) dbl(dst, p1 *curve.GFpCoordinate) {
	/**
	https://hyperelliptic.org/EFD/g1p/auto-twisted.html

	x3 = (x1*y1+y1*x1)/(1+d*x1*x1*y1*y1)
	y3 = (y1*y1-a*x1*x1)/(1-d*x1*x1*y1*y1)

	| Operation                 | Expression
	|  1: XX = x1 * x1          | 1: XX = x1 * x1
	|  2: YY = y1 * y1          | 2: YY = y1 * y1
	|  3: U = d * XX            |
	|  4: U = U * YY            | 3: U = d * XX * YY
	|  5: _0 = 1 + U            |
	|  6: _0 = _0**-1           |
	|  7: x3 = 2 * x1           |
	|  8: x3 = x3 * y1          |
	|  9: x3 = x3 * _0          | 4: x3 = 2 * x1 * y1 * (1 + U)**-1
	| 10: _1 = 1 - U            |
	| 11: _1 = _1**-1           |
	| 12: _2 = a * XX           |
	| 13: y3 = YY - _2          |
	| 14: y3 = y3 * _1          | 5: y3 = (YY - a * XX) * (1 - U)**-1
	*/

	a, d := op.A, op.D

	x1, y1 := &p1[0], &p1[1]
	x3, y3 := &dst[0], &dst[1]

	_0, _1 := &op.t[0], &op.t[1]

	one := field.GFpOne // 1

	x3.Mul(x1, x1)  // 1: XX = x1 * x1
	x3.ReduceSoft() //
	_0.Mul(a, x3)   // 12: _2 = a * XX
	_0.ReduceSoft() //
	y3.Mul(d, x3)   // 3: U = d * XX
	y3.ReduceSoft() //
	x3.Mul(y1, y1)  // 2: YY = y1 * y1
	x3.ReduceSoft() //
	_1.Mul(y3, x3)  // 4: U = U * YY
	_1.ReduceSoft() //
	y3.Sub(x3, _0)  // 13: y3 = YY - _2
	x3.Add(one, _1) // 5: _0 = 1 + U
	_0.Inv(x3)      // 6: _0 = _0**-1
	x3.Sub(one, _1) // 10: _1 = 1 - U
	_1.Inv(x3)      // 11: _1 = _1**-1
	x3.Lsh(x1, 1)   // 7: x3 = 2 * x1
	y3.Mul(y3, _1)  // 14: y3 = y3 * _1
	y3.Reduce()     //
	x3.Mul(x3, y1)  // 8: x3 = x3 * y1
	x3.ReduceSoft() //
	x3.Mul(x3, _0)  // 9: x3 = x3 * _0
	x3.Reduce()     //
}
