// Code generated by curve_generator. DO NOT EDIT.
package twistededwards

import (
	"github.com/RyuaNerin/elliptic2/internal/curve"
)

func (op *extendedOp) add2008hwcd2(dst, p1, p2 *curve.GFpCoordinate) {
	/**
	https://hyperelliptic.org/EFD/g1p/auto-twisted-extended.html#addition-add-2008-hwcd-2

	The "add-2008-hwcd-2" addition formulas [database entry; Sage verification script; Sage output; three-operand code]:

	Cost: 9M + 1*a + 7add.
	Cost: 9M + 1*a + 6add dependent upon the first point.
	Source: 2008 Hisil-Wong-Carter-Dawson, http://eprint.iacr.org/2008/522, Section 3.2.

	| Operation                 | Expression
	|  1: C = Z1 * T2           | 1: C = Z1 * T2
	|  2: D = T1 * Z2           | 2: D = T1 * Z2
	|  3: E = D + C             | 3: E = D + C
	|  4: H = D - C             | 4: H = D - C
	|  5: T3 = E * H            | 5: T3 = E * H
	|  6: A = X1 * X2           | 6: A = X1 * X2
	|  7: B = Y1 * Y2           | 7: B = Y1 * Y2
	|  8: _0 = X2 + Y2          |
	|  9: F = X1 - Y1           |
	| 10: F = F * _0            |
	| 11: F = F + B             |
	| 12: F = F - A             | 8: F = (X1 - Y1) * (X2 + Y2) + B - A
	| 13: X3 = E * F            | 9: X3 = E * F
	| 14: _1 = a * A            |
	| 15: G = B + _1            | 10: G = B + a * A
	| 16: Y3 = G * H            | 11: Y3 = G * H
	| 17: Z3 = F * G            | 12: Z3 = F * G
	*/

	a := op.A

	X1, Y1, Z1, T1 := &p1[0], &p1[1], &p1[2], &p1[3]
	X2, Y2, Z2, T2 := &p2[0], &p2[1], &p2[2], &p2[3]
	X3, Y3, Z3, T3 := &dst[0], &dst[1], &dst[2], &dst[3]

	_0, _1 := &op.t[0], &op.t[1]

	X3.Mul(Z1, T2)  // 1: C = Z1 * T2
	X3.Reduce()     //
	Y3.Mul(T1, Z2)  // 2: D = T1 * Z2
	Y3.Reduce()     //
	_0.Add(Y3, X3)  // 3: E = D + C
	Z3.Sub(Y3, X3)  // 4: H = D - C
	X3.Mul(X1, X2)  // 6: A = X1 * X2
	X3.ReduceSoft() //
	Y3.Add(X2, Y2)  // 8: _0 = X2 + Y2
	T3.Sub(X1, Y1)  // 9: F = X1 - Y1
	_1.Mul(T3, Y3)  // 10: F = F * _0
	_1.ReduceSoft() //
	Y3.Mul(Y1, Y2)  // 7: B = Y1 * Y2
	Y3.Reduce()     //
	T3.Add(_1, Y3)  // 11: F = F + B
	T3.Reduce()     //
	_1.Sub(T3, X3)  // 12: F = F - A
	T3.Mul(a, X3)   // 14: _1 = a * A
	T3.Reduce()     //
	X3.Add(Y3, T3)  // 15: G = B + _1
	T3.Mul(_0, Z3)  // 5: T3 = E * H
	T3.Reduce()     //
	Y3.Mul(X3, Z3)  // 16: Y3 = G * H
	Y3.Reduce()     //
	Z3.Mul(_1, X3)  // 17: Z3 = F * G
	Z3.Reduce()     //
	X3.Mul(_0, _1)  // 13: X3 = E * F
	X3.Reduce()     //
}
