// Code generated by curve_generator. DO NOT EDIT.
package twistededwards

import (
	"github.com/RyuaNerin/elliptic2/internal/curve"
)

func (op *extendedOp) dbl2008hwcd(dst, p1 *curve.GFpCoordinate) {
	/**
	https://hyperelliptic.org/EFD/g1p/auto-twisted-extended.html#doubling-dbl-2008-hwcd

	The "dbl-2008-hwcd" doubling formulas [database entry; Sage verification script; Sage output; three-operand code]:

	Cost: 4M + 4S + 1*a + 6add + 1*2.
	Source: 2008 Hisil-Wong-Carter-Dawson, http://eprint.iacr.org/2008/522, Section 3.3.

	| Operation                 | Expression
	|  1: A = X1**2             | 1: A = X1**2
	|  2: B = Y1**2             | 2: B = Y1**2
	|  3: D = a * A             | 3: D = a * A
	|  4: E = X1 + Y1           |
	|  5: E = E**2              |
	|  6: E = E - A             |
	|  7: E = E - B             | 4: E = (X1 + Y1)**2 - A - B
	|  8: H = D - B             | 5: H = D - B
	|  9: T3 = E * H            | 6: T3 = E * H
	| 10: _0 = Z1**2            |
	| 11: C = 2 * _0            | 7: C = 2 * Z1**2
	| 12: G = D + B             | 8: G = D + B
	| 13: F = G - C             | 9: F = G - C
	| 14: X3 = E * F            | 10: X3 = E * F
	| 15: Y3 = G * H            | 11: Y3 = G * H
	| 16: Z3 = F * G            | 12: Z3 = F * G
	*/

	a := op.A

	X1, Y1, Z1 := &p1[0], &p1[1], &p1[2]
	X3, Y3, Z3, T3 := &dst[0], &dst[1], &dst[2], &dst[3]

	_0, _1 := &op.t[0], &op.t[1]

	X3.Sqr(Y1)      // 2: B = Y1**2
	X3.Reduce()     //
	Y3.Add(X1, Y1)  // 4: E = X1 + Y1
	Z3.Sqr(Y3)      // 5: E = E**2
	Z3.Reduce()     //
	Y3.Sqr(X1)      // 1: A = X1**2
	Y3.ReduceSoft() //
	T3.Mul(a, Y3)   // 3: D = a * A
	T3.Reduce()     //
	_0.Sub(Z3, Y3)  // 6: E = E - A
	_1.Sub(T3, X3)  // 8: H = D - B
	Y3.Sqr(Z1)      // 10: _0 = Z1**2
	Y3.ReduceSoft() //
	Z3.Lsh(Y3, 1)   // 11: C = 2 * _0
	Z3.Reduce()     //
	Y3.Sub(_0, X3)  // 7: E = E - B
	_0.Add(T3, X3)  // 12: G = D + B
	T3.Sub(_0, Z3)  // 13: F = G - C
	X3.Mul(Y3, T3)  // 14: X3 = E * F
	X3.Reduce()     //
	Z3.Mul(T3, _0)  // 16: Z3 = F * G
	Z3.Reduce()     //
	T3.Mul(Y3, _1)  // 9: T3 = E * H
	T3.Reduce()     //
	Y3.Mul(_0, _1)  // 15: Y3 = G * H
	Y3.Reduce()     //
}
