// Code generated by curve_generator. DO NOT EDIT.
package twistededwards

import (
	"github.com/RyuaNerin/elliptic2/internal/curve"
)

func (op *extendedOp) madd2008hwcd2(dst, p1, p2 *curve.GFpCoordinate) {
	/**
	https://hyperelliptic.org/EFD/g1p/auto-twisted-extended.html#addition-madd-2008-hwcd-2

	The "madd-2008-hwcd-2" addition formulas [database entry; Sage verification script; Sage output; three-operand code]:

	Assumptions: Z2=1.
	Cost: 8M + 1*a + 7add.
	Cost: 8M + 1*a + 6add dependent upon the first point.
	Source: 2008 Hisil-Wong-Carter-Dawson, http://eprint.iacr.org/2008/522, Section 3.2.

	| Operation                 | Expression
	|  1: C = Z1 * T2           | 1: C = Z1 * T2
	|  2: E = T1 + C            | 2: E = T1 + C
	|  3: H = T1 - C            | 3: H = T1 - C
	|  4: T3 = E * H            | 4: T3 = E * H
	|  5: A = X1 * X2           | 5: A = X1 * X2
	|  6: B = Y1 * Y2           | 6: B = Y1 * Y2
	|  7: _0 = X2 + Y2          |
	|  8: F = X1 - Y1           |
	|  9: F = F * _0            |
	| 10: F = F + B             |
	| 11: F = F - A             | 7: F = (X1 - Y1) * (X2 + Y2) + B - A
	| 12: X3 = E * F            | 8: X3 = E * F
	| 13: _1 = a * A            |
	| 14: G = B + _1            | 9: G = B + a * A
	| 15: Y3 = G * H            | 10: Y3 = G * H
	| 16: Z3 = F * G            | 11: Z3 = F * G
	*/

	a := op.A

	X1, Y1, Z1, T1 := &p1[0], &p1[1], &p1[2], &p1[3]
	X2, Y2, T2 := &p2[0], &p2[1], &p2[3]
	X3, Y3, Z3, T3 := &dst[0], &dst[1], &dst[2], &dst[3]

	_0, _1 := &op.t[0], &op.t[1]

	X3.Mul(Z1, T2)  // 1: C = Z1 * T2
	X3.Reduce()     //
	_0.Add(T1, X3)  // 2: E = T1 + C
	Z3.Sub(T1, X3)  // 3: H = T1 - C
	X3.Mul(X1, X2)  // 5: A = X1 * X2
	X3.ReduceSoft() //
	Y3.Add(X2, Y2)  // 7: _0 = X2 + Y2
	T3.Sub(X1, Y1)  // 8: F = X1 - Y1
	_1.Mul(T3, Y3)  // 9: F = F * _0
	_1.ReduceSoft() //
	Y3.Mul(Y1, Y2)  // 6: B = Y1 * Y2
	Y3.Reduce()     //
	T3.Add(_1, Y3)  // 10: F = F + B
	T3.Reduce()     //
	_1.Sub(T3, X3)  // 11: F = F - A
	T3.Mul(a, X3)   // 13: _1 = a * A
	T3.Reduce()     //
	X3.Add(Y3, T3)  // 14: G = B + _1
	T3.Mul(_0, Z3)  // 4: T3 = E * H
	T3.Reduce()     //
	Y3.Mul(X3, Z3)  // 15: Y3 = G * H
	Y3.Reduce()     //
	Z3.Mul(_1, X3)  // 16: Z3 = F * G
	Z3.Reduce()     //
	X3.Mul(_0, _1)  // 12: X3 = E * F
	X3.Reduce()     //
}
