// Code generated by curve_generator. DO NOT EDIT.
package twistededwards

import (
	"github.com/RyuaNerin/elliptic2/internal/curve"
)

// a == -1 일 때만 사용 가능
func (op *extendedOp) madd2008hwcd4(dst, p1, p2 *curve.GFpCoordinate) {
	/**
	https://hyperelliptic.org/EFD/g1p/auto-twisted-extended-1.html#addition-madd-2008-hwcd-4

	The "madd-2008-hwcd-4" addition formulas [database entry; Sage verification script; Sage output; three-operand code]:

	Assumptions: Z2=1.
	Cost: 7M + 8add + 2*2.
	Cost: 7M + 6add + 1*2 dependent upon the first point.
	Source: 2008 Hisil-Wong-Carter-Dawson, http://eprint.iacr.org/2008/522, Section 3.2.

	| Operation                 | Expression
	|  1: C = Z1 * 2            |
	|  2: C = C * T2            | 1: C = Z1 * 2 * T2
	|  3: D = 2 * T1            | 2: D = 2 * T1
	|  4: E = D + C             | 3: E = D + C
	|  5: H = D - C             | 4: H = D - C
	|  6: T3 = E * H            | 5: T3 = E * H
	|  7: _0 = Y2 + X2          |
	|  8: A = Y1 - X1           |
	|  9: A = A * _0            | 6: A = (Y1 - X1) * (Y2 + X2)
	| 10: _1 = Y2 - X2          |
	| 11: B = Y1 + X1           |
	| 12: B = B * _1            | 7: B = (Y1 + X1) * (Y2 - X2)
	| 13: F = B - A             | 8: F = B - A
	| 14: X3 = E * F            | 9: X3 = E * F
	| 15: G = B + A             | 10: G = B + A
	| 16: Y3 = G * H            | 11: Y3 = G * H
	| 17: Z3 = F * G            | 12: Z3 = F * G
	*/

	X1, Y1, Z1, T1 := &p1[0], &p1[1], &p1[2], &p1[3]
	X2, Y2, T2 := &p2[0], &p2[1], &p2[3]
	X3, Y3, Z3, T3 := &dst[0], &dst[1], &dst[2], &dst[3]

	_0, _1 := &op.t[0], &op.t[1]

	X3.Lsh(T1, 1)  // 3: D = 2 * T1
	X3.Reduce()    //
	Y3.Lsh(Z1, 1)  // 1: C = Z1 * 2
	Z3.Mul(Y3, T2) // 2: C = C * T2
	Z3.Reduce()    //
	Y3.Add(Y1, X1) // 11: B = Y1 + X1
	T3.Add(Y2, X2) // 7: _0 = Y2 + X2
	_0.Sub(X3, Z3) // 5: H = D - C
	_1.Add(X3, Z3) // 4: E = D + C
	X3.Sub(Y2, X2) // 10: _1 = Y2 - X2
	Z3.Mul(Y3, X3) // 12: B = B * _1
	Z3.Reduce()    //
	X3.Sub(Y1, X1) // 8: A = Y1 - X1
	Y3.Mul(X3, T3) // 9: A = A * _0
	Y3.Reduce()    //
	T3.Sub(Z3, Y3) // 13: F = B - A
	X3.Add(Z3, Y3) // 15: G = B + A
	Z3.Mul(T3, X3) // 17: Z3 = F * G
	Z3.Reduce()    //
	Y3.Mul(X3, _0) // 16: Y3 = G * H
	Y3.Reduce()    //
	X3.Mul(_1, T3) // 14: X3 = E * F
	X3.Reduce()    //
	T3.Mul(_1, _0) // 6: T3 = E * H
	T3.Reduce()    //
}
