// Code generated by curve_generator. DO NOT EDIT.
package twistededwards

import (
	"github.com/RyuaNerin/elliptic2/internal/curve"
)

// a == -1 일 때만 사용 가능
func (op *extendedOp) add2008hwcd4(dst, p1, p2 *curve.GFpCoordinate) {
	/**
	https://hyperelliptic.org/EFD/g1p/auto-twisted-extended-1.html#addition-add-2008-hwcd-4

	The "add-2008-hwcd-4" addition formulas [database entry; Sage verification script; Sage output; three-operand code]:

	Cost: 8M + 8add + 2*2.
	Cost: 8M + 6add dependent upon the first point.
	Source: 2008 Hisil-Wong-Carter-Dawson, http://eprint.iacr.org/2008/522, Section 3.2.

	| Operation                 | Expression
	|  1: C = Z1 * 2            |
	|  2: C = C * T2            | 1: C = Z1 * 2 * T2
	|  3: D = T1 * 2            |
	|  4: D = D * Z2            | 2: D = T1 * 2 * Z2
	|  5: E = D + C             | 3: E = D + C
	|  6: H = D - C             | 4: H = D - C
	|  7: T3 = E * H            | 5: T3 = E * H
	|  8: _0 = Y2 + X2          |
	|  9: A = Y1 - X1           |
	| 10: A = A * _0            | 6: A = (Y1 - X1) * (Y2 + X2)
	| 11: _1 = Y2 - X2          |
	| 12: B = Y1 + X1           |
	| 13: B = B * _1            | 7: B = (Y1 + X1) * (Y2 - X2)
	| 14: F = B - A             | 8: F = B - A
	| 15: X3 = E * F            | 9: X3 = E * F
	| 16: G = B + A             | 10: G = B + A
	| 17: Y3 = G * H            | 11: Y3 = G * H
	| 18: Z3 = F * G            | 12: Z3 = F * G
	*/

	X1, Y1, Z1, T1 := &p1[0], &p1[1], &p1[2], &p1[3]
	X2, Y2, Z2, T2 := &p2[0], &p2[1], &p2[2], &p2[3]
	X3, Y3, Z3, T3 := &dst[0], &dst[1], &dst[2], &dst[3]

	_0, _1 := &op.t[0], &op.t[1]

	X3.Sub(Y2, X2) // 11: _1 = Y2 - X2
	Y3.Lsh(Z1, 1)  // 1: C = Z1 * 2
	Z3.Lsh(T1, 1)  // 3: D = T1 * 2
	T3.Mul(Y3, T2) // 2: C = C * T2
	T3.Reduce()    //
	Y3.Mul(Z3, Z2) // 4: D = D * Z2
	Y3.Reduce()    //
	Z3.Sub(Y3, T3) // 6: H = D - C
	_0.Sub(Y1, X1) // 9: A = Y1 - X1
	_1.Add(Y3, T3) // 5: E = D + C
	Y3.Add(Y1, X1) // 12: B = Y1 + X1
	T3.Mul(Y3, X3) // 13: B = B * _1
	T3.Reduce()    //
	X3.Add(Y2, X2) // 8: _0 = Y2 + X2
	Y3.Mul(_0, X3) // 10: A = A * _0
	Y3.Reduce()    //
	X3.Add(T3, Y3) // 16: G = B + A
	_0.Sub(T3, Y3) // 14: F = B - A
	T3.Mul(_1, Z3) // 7: T3 = E * H
	T3.Reduce()    //
	Y3.Mul(X3, Z3) // 17: Y3 = G * H
	Y3.Reduce()    //
	Z3.Mul(_0, X3) // 18: Z3 = F * G
	Z3.Reduce()    //
	X3.Mul(_1, _0) // 15: X3 = E * F
	X3.Reduce()    //
}
