// Code generated by curve_generator. DO NOT EDIT.
package edwards

import (
	"github.com/RyuaNerin/elliptic2/internal/curve"
)

func (op *affineOp) dbl(dst, p1 *curve.GFpCoordinate) {
	/**
	https://hyperelliptic.org/EFD/g1p/auto-edwards.html

	x3 = (x1*y1+y1*x1)/(c*(1+d*x1*x1*y1*y1))
	y3 = (y1*y1-x1*x1)/(c*(1-d*x1*x1*y1*y1))

	| Operation                 | Expression
	|  1: xx = x1 * x1          | 1: xx = x1 * x1
	|  2: yy = y1 * y1          | 2: yy = y1 * y1
	|  3: cdxxyy = c * d        |
	|  4: cdxxyy = cdxxyy * xx  |
	|  5: cdxxyy = cdxxyy * yy  | 3: cdxxyy = c * d * xx * yy
	|  6: _0 = c + cdxxyy       |
	|  7: _0 = _0**-1           |
	|  8: _1 = y1 * x1          |
	|  9: x3 = x1 * y1          |
	| 10: x3 = x3 + _1          |
	| 11: x3 = x3 * _0          | 4: x3 = (x1 * y1 + y1 * x1) * (c + cdxxyy)**-1
	| 12: _2 = c - cdxxyy       |
	| 13: _2 = _2**-1           |
	| 14: y3 = yy - xx          |
	| 15: y3 = y3 * _2          | 5: y3 = (yy - xx) * (c - cdxxyy)**-1
	*/

	c, d := op.C, op.D

	x1, y1 := &p1[0], &p1[1]
	x3, y3 := &dst[0], &dst[1]

	_0, _1 := &op.t[0], &op.t[1]

	x3.Mul(y1, y1)  // 2: yy = y1 * y1
	x3.ReduceSoft() //
	_0.Mul(x1, x1)  // 1: xx = x1 * x1
	_0.ReduceSoft() //
	y3.Mul(c, d)    // 3: cdxxyy = c * d
	y3.ReduceSoft() //
	_1.Mul(y3, _0)  // 4: cdxxyy = cdxxyy * xx
	_1.ReduceSoft() //
	y3.Sub(x3, _0)  // 14: y3 = yy - xx
	_0.Mul(_1, x3)  // 5: cdxxyy = cdxxyy * yy
	_0.ReduceSoft() //
	x3.Add(c, _0)   // 6: _0 = c + cdxxyy
	_1.Sub(c, _0)   // 12: _2 = c - cdxxyy
	_0.Inv(x3)      // 7: _0 = _0**-1
	x3.Inv(_1)      // 13: _2 = _2**-1
	_1.Mul(y1, x1)  // 8: _1 = y1 * x1
	_1.ReduceSoft() //
	y3.Mul(y3, x3)  // 15: y3 = y3 * _2
	y3.Reduce()     //
	x3.Mul(x1, y1)  // 9: x3 = x1 * y1
	x3.ReduceSoft() //
	x3.Add(x3, _1)  // 10: x3 = x3 + _1
	x3.Mul(x3, _0)  // 11: x3 = x3 * _0
	x3.Reduce()     //
}
