// Code generated by curve_generator. DO NOT EDIT.
package edwards

import (
	"github.com/RyuaNerin/elliptic2/internal/curve"
)

func (op *projectiveOp) madd2007bl2(dst, p1, p2 *curve.GFpCoordinate) {
	/**
	https://hyperelliptic.org/EFD/g1p/auto-edwards-projective.html#addition-madd-2007-bl-2

	Assumptions: Z2=1.
	Cost: 9M + 1S + 1*c + 1*d + 7add.
	Cost: 9M + 1S + 1*c + 1*d + 6add dependent upon the first point.
	Source: 2007 Bernstein-Lange.
	Strongly unified.
	Explicit formulas:
	R1 = X1
	R2 = Y1
	R3 = Z1
	R4 = X2
	R5 = Y2
	R7 = R1+R2
	R6 = R4+R5
	R1 = R1*R4
	R2 = R2*R5
	R7 = R7*R6
	R7 = R7-R1
	R7 = R7-R2
	R7 = R7*R3
	R6 = R1*R2
	R6 = d*R6
	R2 = R2-R1
	R2 = R2*R3
	R3 = R3**2
	R1 = R3-R6
	R3 = R3+R6
	R2 = R2*R3
	R3 = R3*R1
	R1 = R1*R7
	R3 = c*R3
	X3 = R1
	Y3 = R2
	Z3 = R3

	| Operation                 | Expression
	|  1: _0 = Y1 * Y2          |
	|  2: _1 = X1 * X2          |
	|  3: _2 = X2 + Y2          |
	|  4: R7 = X1 + Y1          |
	|  5: R7 = R7 * _2          |
	|  6: R7 = R7 - _1          |
	|  7: R7 = R7 - _0          |
	|  8: R7 = R7 * Z1          | 1: R7 = ((X1 + Y1) * (X2 + Y2) - X1 * X2 - Y1 * Y2) * Z1
	|  9: _4 = Y1 * Y2          |
	| 10: _3 = X1 * X2          |
	| 11: _3 = _3 * _4          |
	| 12: R6 = d * _3           | 2: R6 = d * X1 * X2 * Y1 * Y2
	| 13: _5 = X1 * X2          |
	| 14: R2 = Y1 * Y2          |
	| 15: R2 = R2 - _5          |
	| 16: R2 = R2 * Z1          | 3: R2 = (Y1 * Y2 - X1 * X2) * Z1
	| 17: R1 = Z1**2            |
	| 18: R1 = R1 - R6          | 4: R1 = Z1**2 - R6
	| 19: R3 = Z1**2            |
	| 20: R3 = R3 + R6          |
	| 21: R3 = R3 * R1          | 5: R3 = (Z1**2 + R6) * R1
	| 22: X3 = R1 * R7          | 6: X3 = R1 * R7
	| 23: _6 = Z1**2            |
	| 24: _6 = _6 + R6          |
	| 25: Y3 = R2 * _6          | 7: Y3 = R2 * (Z1**2 + R6)
	| 26: Z3 = c * R3           | 8: Z3 = c * R3
	*/

	c, d := op.C, op.D

	X1, Y1, Z1 := &p1[0], &p1[1], &p1[2]
	X2, Y2 := &p2[0], &p2[1]
	X3, Y3, Z3 := &dst[0], &dst[1], &dst[2]

	_0, _1, _2 := &op.t[0], &op.t[1], &op.t[2]

	X3.Add(X2, Y2)  // 3: _2 = X2 + Y2
	Y3.Add(X1, Y1)  // 4: R7 = X1 + Y1
	Z3.Mul(X1, X2)  // 2: _1 = X1 * X2
	Z3.Reduce()     //
	_0.Mul(Y3, X3)  // 5: R7 = R7 * _2
	_0.ReduceSoft() //
	X3.Sub(_0, Z3)  // 6: R7 = R7 - _1
	X3.Reduce()     //
	Y3.Mul(Y1, Y2)  // 1: _0 = Y1 * Y2
	Y3.Reduce()     //
	Z3.Mul(X1, X2)  // 10: _3 = X1 * X2
	Z3.ReduceSoft() //
	_0.Sub(X3, Y3)  // 7: R7 = R7 - _0
	X3.Mul(Y1, Y2)  // 14: R2 = Y1 * Y2
	X3.Reduce()     //
	_1.Mul(_0, Z1)  // 8: R7 = R7 * Z1
	_1.ReduceSoft() //
	Y3.Mul(X1, X2)  // 13: _5 = X1 * X2
	Y3.Reduce()     //
	_0.Sqr(Z1)      // 19: R3 = Z1**2
	_0.ReduceSoft() //
	_2.Sub(X3, Y3)  // 15: R2 = R2 - _5
	X3.Mul(Y1, Y2)  // 9: _4 = Y1 * Y2
	X3.ReduceSoft() //
	Y3.Mul(Z3, X3)  // 11: _3 = _3 * _4
	Y3.ReduceSoft() //
	X3.Mul(d, Y3)   // 12: R6 = d * _3
	X3.Reduce()     //
	Y3.Sqr(Z1)      // 23: _6 = Z1**2
	Y3.Reduce()     //
	Z3.Add(_0, X3)  // 20: R3 = R3 + R6
	_0.Mul(_2, Z1)  // 16: R2 = R2 * Z1
	_0.ReduceSoft() //
	_2.Add(Y3, X3)  // 24: _6 = _6 + R6
	Y3.Mul(_0, _2)  // 25: Y3 = R2 * _6
	Y3.Reduce()     //
	_0.Sqr(Z1)      // 17: R1 = Z1**2
	_0.ReduceSoft() //
	_2.Sub(_0, X3)  // 18: R1 = R1 - R6
	_0.Mul(Z3, _2)  // 21: R3 = R3 * R1
	_0.ReduceSoft() //
	X3.Mul(_2, _1)  // 22: X3 = R1 * R7
	X3.Reduce()     //
	Z3.Mul(c, _0)   // 26: Z3 = c * R3
	Z3.Reduce()     //
}
