// Code generated by curve_generator. DO NOT EDIT.
package edwards

import (
	"github.com/RyuaNerin/elliptic2/internal/curve"
)

func (op *projectiveOp) dbl2007bl2(dst, p1 *curve.GFpCoordinate) {
	/**
	https://hyperelliptic.org/EFD/g1p/auto-edwards-projective.html#doubling-dbl-2007-bl-2

	The "dbl-2007-bl-2" doubling formulas [database entry; Sage verification script; Sage output; three-operand code]:

	Cost: 3M + 4S + 3*c + 5add + 1*2.
	Source: 2007 Bernstein-Lange; source comments that these formulas use two temporary registers.
	Explicit formulas:
	R1 = X1
	R2 = Y1
	R3 = Z1
	R4 = R1+R2
	R3 = c*R3
	R1 = R1**2
	R2 = R2**2
	R3 = R3**2
	R4 = R4**2
	R3 = 2*R3
	R5 = R1+R2
	R2 = R1-R2
	R4 = R4-R5
	R3 = R5-R3
	R1 = R3*R4
	R3 = R3*R5
	R2 = R2*R5
	R1 = c*R1
	R2 = c*R2
	X3 = R1
	Y3 = R2
	Z3 = R3

	| Operation                 | Expression
	|  1: _0 = Y1**2            |
	|  2: R5 = X1**2            |
	|  3: R5 = R5 + _0          | 1: R5 = X1**2 + Y1**2
	|  4: R4 = X1 + Y1          |
	|  5: R4 = R4**2            |
	|  6: R4 = R4 - R5          | 2: R4 = (X1 + Y1)**2 - R5
	|  7: _2 = c * Z1           |
	|  8: _2 = _2**2            |
	|  9: _1 = 2 * _2           |
	| 10: R3 = R5 - _1          | 3: R3 = R5 - 2 * (c * Z1)**2
	| 11: R1 = R3 * R4          | 4: R1 = R3 * R4
	| 12: _3 = Y1**2            |
	| 13: R2 = X1**2            |
	| 14: R2 = R2 - _3          |
	| 15: R2 = R2 * R5          | 5: R2 = (X1**2 - Y1**2) * R5
	| 16: X3 = c * R1           | 6: X3 = c * R1
	| 17: Y3 = c * R2           | 7: Y3 = c * R2
	| 18: Z3 = R3 * R5          | 8: Z3 = R3 * R5
	*/

	c := op.C

	X1, Y1, Z1 := &p1[0], &p1[1], &p1[2]
	X3, Y3, Z3 := &dst[0], &dst[1], &dst[2]

	_0, _1 := &op.t[0], &op.t[1]

	X3.Add(X1, Y1)  // 4: R4 = X1 + Y1
	Y3.Sqr(X1)      // 2: R5 = X1**2
	Y3.Reduce()     //
	Z3.Sqr(Y1)      // 1: _0 = Y1**2
	Z3.Reduce()     //
	_0.Sqr(X3)      // 5: R4 = R4**2
	_0.ReduceSoft() //
	_1.Add(Y3, Z3)  // 3: R5 = R5 + _0
	X3.Sqr(X1)      // 13: R2 = X1**2
	X3.Reduce()     //
	Y3.Sqr(Y1)      // 12: _3 = Y1**2
	Y3.Reduce()     //
	Z3.Sub(X3, Y3)  // 14: R2 = R2 - _3
	X3.Mul(c, Z1)   // 7: _2 = c * Z1
	X3.ReduceSoft() //
	Y3.Sub(_0, _1)  // 6: R4 = R4 - R5
	_0.Sqr(X3)      // 8: _2 = _2**2
	_0.ReduceSoft() //
	X3.Lsh(_0, 1)   // 9: _1 = 2 * _2
	X3.Reduce()     //
	_0.Sub(_1, X3)  // 10: R3 = R5 - _1
	X3.Mul(Z3, _1)  // 15: R2 = R2 * R5
	X3.ReduceSoft() //
	Z3.Mul(_0, Y3)  // 11: R1 = R3 * R4
	Z3.ReduceSoft() //
	Y3.Mul(c, X3)   // 17: Y3 = c * R2
	Y3.Reduce()     //
	X3.Mul(c, Z3)   // 16: X3 = c * R1
	X3.Reduce()     //
	Z3.Mul(_0, _1)  // 18: Z3 = R3 * R5
	Z3.Reduce()     //
}
