// Code generated by curve_generator. DO NOT EDIT.

/*
package oakley is a collection of named elliptic curves.

Oakley groups from <https://tools.ietf.org/html/rfc2409> and <https://tools.ietf.org/html/rfc5114>

https://neuromancer.sk/std/oakley/
*/
package oakley

import (
	"crypto/elliptic"

	"github.com/RyuaNerin/elliptic2/internal/curves"
)

// Oakley192BitRandomECPGroup returns a Curve which implements oakley/192-bit Random ECP Group
// https://neuromancer.sk/std/oakley/192-bit%20Random%20ECP%20Group
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Oakley192BitRandomECPGroup() elliptic.Curve {
	return curves.OakleyOakley192BitRandomECPGroup()
}

// Oakley224BitRandomECPGroup returns a Curve which implements oakley/224-bit Random ECP Group
// https://neuromancer.sk/std/oakley/224-bit%20Random%20ECP%20Group
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Oakley224BitRandomECPGroup() elliptic.Curve {
	return curves.OakleyOakley224BitRandomECPGroup()
}

// Oakley256BitRandomECPGroup returns a Curve which implements oakley/256-bit Random ECP Group
// https://neuromancer.sk/std/oakley/256-bit%20Random%20ECP%20Group
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Oakley256BitRandomECPGroup() elliptic.Curve {
	return curves.OakleyOakley256BitRandomECPGroup()
}

// Oakley384BitRandomECPGroup returns a Curve which implements oakley/384-bit Random ECP Group
// https://neuromancer.sk/std/oakley/384-bit%20Random%20ECP%20Group
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Oakley384BitRandomECPGroup() elliptic.Curve {
	return curves.OakleyOakley384BitRandomECPGroup()
}

// Oakley521BitRandomECPGroup returns a Curve which implements oakley/521-bit Random ECP Group
// https://neuromancer.sk/std/oakley/521-bit%20Random%20ECP%20Group
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Oakley521BitRandomECPGroup() elliptic.Curve {
	return curves.OakleyOakley521BitRandomECPGroup()
}

// OakleyGroup3 returns a Curve which implements oakley/Oakley Group 3
// https://neuromancer.sk/std/oakley/Oakley%20Group%203
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func OakleyGroup3() elliptic.Curve {
	return curves.OakleyOakleyGroup3()
}

// OakleyGroup4 returns a Curve which implements oakley/Oakley Group 4
// https://neuromancer.sk/std/oakley/Oakley%20Group%204
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func OakleyGroup4() elliptic.Curve {
	return curves.OakleyOakleyGroup4()
}
