// Code generated by curve_generator. DO NOT EDIT.

/*
package mnt is a collection of named elliptic curves.

MNT (Miyaji, Nakabayashi, and Takano curves) example curves from: New explicit conditions of elliptic curve traces for FR-reduction - https://dspace.jaist.ac.jp/dspace/bitstream/10119/4432/1/73-48.pdf.

https://neuromancer.sk/std/mnt/
*/
package mnt

import (
	"crypto/elliptic"
)

// Mnt1 returns a Curve which implements mnt/mnt1
// https://neuromancer.sk/std/mnt/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Mnt1() elliptic.Curve {
	mnt1Once.Do(initMnt1)
	return mnt1Curve
}

// Mnt2_1 returns a Curve which implements mnt/mnt2/1
// https://neuromancer.sk/std/mnt/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Mnt2_1() elliptic.Curve {
	mnt2_1Once.Do(initMnt2_1)
	return mnt2_1Curve
}

// Mnt2_2 returns a Curve which implements mnt/mnt2/2
// https://neuromancer.sk/std/mnt/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Mnt2_2() elliptic.Curve {
	mnt2_2Once.Do(initMnt2_2)
	return mnt2_2Curve
}

// Mnt3_1 returns a Curve which implements mnt/mnt3/1
// https://neuromancer.sk/std/mnt/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Mnt3_1() elliptic.Curve {
	mnt3_1Once.Do(initMnt3_1)
	return mnt3_1Curve
}

// Mnt3_2 returns a Curve which implements mnt/mnt3/2
// https://neuromancer.sk/std/mnt/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Mnt3_2() elliptic.Curve {
	mnt3_2Once.Do(initMnt3_2)
	return mnt3_2Curve
}

// Mnt3_3 returns a Curve which implements mnt/mnt3/3
// https://neuromancer.sk/std/mnt/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Mnt3_3() elliptic.Curve {
	mnt3_3Once.Do(initMnt3_3)
	return mnt3_3Curve
}

// Mnt4 returns a Curve which implements mnt/mnt4
// https://neuromancer.sk/std/mnt/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Mnt4() elliptic.Curve {
	mnt4Once.Do(initMnt4)
	return mnt4Curve
}

// Mnt5_1 returns a Curve which implements mnt/mnt5/1
// https://neuromancer.sk/std/mnt/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Mnt5_1() elliptic.Curve {
	mnt5_1Once.Do(initMnt5_1)
	return mnt5_1Curve
}

// Mnt5_2 returns a Curve which implements mnt/mnt5/2
// https://neuromancer.sk/std/mnt/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Mnt5_2() elliptic.Curve {
	mnt5_2Once.Do(initMnt5_2)
	return mnt5_2Curve
}

// Mnt5_3 returns a Curve which implements mnt/mnt5/3
// https://neuromancer.sk/std/mnt/
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func Mnt5_3() elliptic.Curve {
	mnt5_3Once.Do(initMnt5_3)
	return mnt5_3Curve
}
