name: Go Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    strategy:
      matrix:
        go-version:
          - '1.24'
          - '1.25'
          - '1.26'
        os:
          - ubuntu-latest
          - ubuntu-26.04-arm
          - windows-latest
          - windows-11-arm
          - macos-latest
            
    runs-on: ${{ matrix.os }}
    name: Lint and Test - Go ${{ matrix.go-version }} on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: go.sum
          
      - name: Set up gotestfmt
        uses: gotesttools/gotestfmt-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.9.0

      - name: golangci-lint (purego)
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.9.0
          args: --build-tags purego

      - name: Build
        run: go build -v ./...

      - name: Test
        run: |
          (go test -json -v              ./... 2>&1 | tee "${{ runner.temp }}/gotest.log"        | gotestfmt) || false
          (go test -json -v -tags purego ./... 2>&1 | tee "${{ runner.temp }}/gotest-purego.log" | gotestfmt) || false

      - name: Upload test log
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-log
          path: |
            ${{ runner.temp }}/gotest.log
            ${{ runner.temp }}/gotest-purego.log
          if-no-files-found: error

  cross-arch-test:
    needs: lint-and-test
    continue-on-error: true
    strategy:
      matrix:
        include:
        - platform: linux/arm/v6
          image: arm32v6/golang:1.26-alpine
        - platform: linux/arm/v6
          image: arm32v6/golang:1.25-alpine
        - platform: linux/arm/v6
          image: arm32v6/golang:1.24-alpine
        - platform: linux/arm/v7
          image: arm32v7/golang:1.26-alpine
        - platform: linux/arm/v7
          image: arm32v7/golang:1.25-alpine
        - platform: linux/arm/v7
          image: arm32v7/golang:1.24-alpine
        - platform: linux/arm64/v8
          image: arm64v8/golang:1.26-alpine
        - platform: linux/arm64/v8
          image: arm64v8/golang:1.25-alpine
        - platform: linux/arm64/v8
          image: arm64v8/golang:1.24-alpine
        - platform: linux/ppc64le
          image: ppc64le/golang:1.26-alpine
        - platform: linux/ppc64le
          image: ppc64le/golang:1.25-alpine
        - platform: linux/ppc64le
          image: ppc64le/golang:1.24-alpine
        - platform: linux/s390x
          image: s390x/golang:1.26-alpine
        - platform: linux/s390x
          image: s390x/golang:1.25-alpine
        - platform: linux/s390x
          image: s390x/golang:1.24-alpine
        - platform: linux/mips64le
          image: mips64le/golang:1.26-bookworm
        - platform: linux/mips64le
          image: mips64le/golang:1.25-bookworm
        - platform: linux/mips64le
          image: mips64le/golang:1.24-bookworm
        - platform: linux/riscv64
          image: riscv64/golang:1.26-alpine
        - platform: linux/riscv64
          image: riscv64/golang:1.25-alpine
        - platform: linux/riscv64
          image: riscv64/golang:1.24-alpine
        - platform: linux/386
          image: i386/golang:1.26-alpine
        - platform: linux/386
          image: i386/golang:1.25-alpine
        - platform: linux/386
          image: i386/golang:1.24-alpine
        - platform: linux/loong64
          image: ghcr.io/loong64/golang:1.26-alpine
        - platform: linux/loong64
          image: ghcr.io/loong64/golang:1.25-alpine
        - platform: linux/loong64
          image: ghcr.io/loong64/golang:1.24-alpine

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v6

      - name: Set git to use LF
        run: |
          git config core.autocrlf false
          git rm --cached -r .
          git reset --hard

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Test
        run: |
          cd bin/
          bash ./cross-arch-test.sh "${{ matric.platform }}" "${{ matrix.image }}"
