name: Go Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        go-version:
          - '1.22'
          - '1.23'
          - '1.24'
          - '1.25'
        os:
          - ubuntu-latest
          - macos-latest-large
          - windows-latest
            
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: go.sum

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...