// Code generated by curve_generator. DO NOT EDIT.

/*
package anssi is a collection of named elliptic curves.

Agence nationale de la sécurité des systèmes d'information: Publication d'un paramétrage de courbe elliptique visant des applications de passeport électronique et de l'administration électronique française. 21 November 2011

https://neuromancer.sk/std/anssi/
*/
package anssi

import (
	"crypto/elliptic"
)

// FRP256v1 returns a Curve which implements anssi/FRP256v1
// https://neuromancer.sk/std/anssi/
//
// OID: 1.2.250.1.223.101.256.1
//
// Multiple invocations of this function will return the same value, so it can
// be used for equality checks and switch statements.
func FRP256v1() elliptic.Curve {
	fRP256v1Once.Do(initFRP256v1)
	return fRP256v1Curve
}
