// Code generated by curve_generator. DO NOT EDIT.

package anssi

import (
	"crypto/elliptic"
	"sync"

	. "github.com/RyuaNerin/elliptic2/internal"
	. "github.com/RyuaNerin/elliptic2/internal/curve"
	wp "github.com/RyuaNerin/elliptic2/internal/curve/weierstrassprime"
	. "github.com/RyuaNerin/elliptic2/internal/field"
)

var (
	fRP256v1Once sync.Once

	fRP256v1Curve elliptic.Curve
)

// https://neuromancer.sk/std/anssi/FRP256v1
func initFRP256v1() {
	fRP256v1Curve = NewCurve(
		wp.Build(&wp.CurveParams{
			Name:    `FRP256v1`,
			BitSize: 256,
			P:       NewGFpModulusFromHex(`f1fd178c0b3ad58f10126de8ce42435b3961adbcabc8ca6de8fcf353d86e9c03`),
			A:       ParseGFpHex(`f1fd178c0b3ad58f10126de8ce42435b3961adbcabc8ca6de8fcf353d86e9c00`),
			B:       ParseGFpHex(`ee353fca5428a9300d4aba754a44c00fdfec0c9ae4b1a1803075ed967b7bb73f`),
			N:       ParseGFpHex(`f1fd178c0b3ad58f10126de8ce42435b53dc67e140d2bf941ffdd459c6d655e1`),
			Gx:      HI(`b6b3d4c356c139eb31183d4749d423958c27d2dcaf98b70164c97a2dd98f5cff`),
			Gy:      HI(`6142e0f7c8b204911f9271f0f3ecef8c2701c307e8e4c9e183115a1554062cfb`),
		}),
		WithOID(`1.2.250.1.223.101.256.1`),
	)
}
